/** Paquete editorial. Agosto 2026. Daniel Pinto. Cierre de datos: 22 de agosto de 2026. */

import type { Article } from "./content";

export const AGOSTO_ARTICLES: Article[] = [
  {
    slug: "tmec-horizonte-doce-meses",
    title: "El T-MEC no se murió. Se le acortó el horizonte a doce meses.",
    dek: "Estados Unidos rechazó extender el tratado por dieciséis años. Lo que quedó no es incertidumbre jurídica: es una planificación de capital que ahora se revisa cada año.",
    kicker: "Comercio",
    section: "ideas",
    authorId: "daniel-pinto",
    signedName: "Daniel Pinto",
    publishedAt: "2026-08-22",
    updatedAt: "2026-08-22",
    readMinutes: 9,
    image: "/photos/tmec-border.jpg",
    imageAlt: "Fila de camiones de carga en un cruce fronterizo México–Estados Unidos",
    caption: "El horizonte del T-MEC ahora se revisa cada julio.",
    featured: true,
    city: "Ciudad de México",
    pace: "fondo",
    tags: ["industria", "nearshoring", "fondo"],
    pullQuote: "El horizonte corto favorece al que ya está instalado y castiga al que estaba evaluando entrar.",
    body: [
      { type: "p", text: "El 1 de julio de 2026, a las nueve de la mañana, tres personas se conectaron a una videollamada: Jamieson Greer por Estados Unidos, Dominic LeBlanc por Canadá y Marcelo Ebrard por México. Era la revisión conjunta que el artículo 34.7 del T-MEC había agendado seis años antes, el día que el tratado entró en vigor. La reunión duró poco. Greer comunicó que Estados Unidos no estaba en posición de extender el acuerdo por dieciséis años adicionales." },
      { type: "stat", value: "12 meses", label: "Horizonte de revisión" },
      { type: "stat", value: "16 años", label: "Lo que no se extendió" },
      { type: "stat", value: "2036", label: "Vigencia del tratado" },
      { type: "quote", text: "El horizonte corto favorece al que ya está instalado y castiga al que estaba evaluando entrar.", cite: "Daniel Pinto" },
      { type: "p", text: "Con eso, el T-MEC se fue por el carril alternativo que el propio texto contempla: sigue vigente hasta 2036, pero se revisa cada doce meses." },
      { type: "p", text: "La discusión pública de las semanas siguientes se dedicó, previsiblemente, a determinar si eso era una derrota. El gobierno mexicano sostuvo que no: el tratado se mantiene, no puede cancelarse por decreto —haría falta pasar por los tres congresos— y en cualquier momento de la próxima década los tres países pueden acordar la extensión de dieciséis años. La oposición sostuvo lo contrario, que se estaba vendiendo como triunfo el rechazo de exactamente lo que México y Canadá habían ido a pedir." },
      { type: "p", text: "Ambas lecturas son correctas y ninguna de las dos es la noticia." },
      { type: "p", text: "La noticia es lo que le pasa a una decisión de inversión cuando el marco que la sostiene deja de tener un horizonte de dieciséis años y pasa a tener uno de doce meses." },
      { type: "h2", text: "El cálculo de una planta" },
      { type: "p", text: "Una planta de manufactura automotriz de escala tiene un período de recuperación que se mide en décadas. La decisión de instalarla en Monterrey y no en Carolina del Sur descansa sobre un supuesto que rara vez se escribe en el memorándum de inversión porque se da por evidente: que las reglas bajo las cuales ese producto cruza la frontera van a seguir siendo aproximadamente las mismas cuando la línea esté produciendo a capacidad." },
      { type: "p", text: "Ese supuesto ya no se puede escribir. Cada julio, a partir de ahora, la Comisión de Libre Comercio se sienta a evaluar el funcionamiento del acuerdo, y las reglas de origen —el mecanismo que determina qué producto califica para trato preferencial y cuál no— son el punto central de la agenda estadounidense." },
      { type: "p", text: "En las consultas públicas que el USTR abrió en septiembre de 2025, el reclamo se repitió con consistencia entre los actores industriales: las reglas deben cambiar para asegurar que el beneficio arancelario se quede sustancialmente dentro del bloque. La Alianza para la Manufactura Estadounidense fue explícita sobre su preocupación de fondo, que es el uso de México como plataforma de ensamblaje para insumos de terceros países. Y el USTR planteó que el endurecimiento de reglas de origen para bienes industriales no automotrices —es decir, más allá del sector que ya tenía reglas duras— se abordaría de manera trilateral." },
      { type: "p", text: "Traducido: la conversación sobre contenido regional se va a repetir todos los años, y va a ir ampliándose de categoría en categoría." },
      { type: "h2", text: "Lo que ya cambió antes de la revisión" },
      { type: "p", text: "Vale la pena notar algo que se pierde en la cobertura de la revisión: los cambios fiscales y arancelarios de enero de 2026 —nuevas retenciones de ISR e IVA, ajustes en el tratamiento de importaciones— ya están vigentes y no dependen del resultado de ninguna negociación. Operan hoy sobre el margen de cualquier empresa que importe o exporte." },
      { type: "p", text: "El capítulo 19, sobre comercio digital, también está en la agenda: tributación de plataformas, tratamiento de datos transfronterizos, inteligencia artificial. Ese capítulo se negoció en 2018 para un mundo que ya no existe, y es probable que sea el terreno donde la revisión anual produzca cambios más rápidos que en manufactura, simplemente porque hay menos capital hundido defendiendo el statu quo." },
      { type: "h2", text: "Cómo se opera con esto" },
      { type: "p", text: "Hay tres consecuencias prácticas para cualquier empresa con exposición al bloque." },
      { type: "p", text: "La primera es que la certificación de origen dejó de ser un trámite de compliance y pasó a ser una función estratégica. Si su estructura de proveedores no está documentada al nivel de poder demostrar contenido regional bajo un criterio más estricto que el actual, ese trabajo hay que empezarlo ahora, no cuando cambie la regla." },
      { type: "p", text: "La segunda es que el ciclo de decisión de inversión debe internalizar una fecha nueva. Julio es ahora un evento de calendario corporativo, como lo es el cierre fiscal. Las rondas se están agendando con anticipación —la primera bilateral post-revisión se hizo la semana del 20 de julio en Ciudad de México— y el contenido de cada una es información material." },
      { type: "p", text: "La tercera es la más incómoda: el horizonte corto favorece al que ya está instalado y castiga al que estaba evaluando entrar. Profundizar una operación existente en México es una apuesta que se puede hacer con visibilidad de doce meses. Construir una planta nueva desde cero, no." },
      { type: "p", text: "Esa asimetría no es una hipótesis. Ya está en los datos de inversión extranjera, y es el tema de la pieza siguiente." },
    ],
  },
  {
    slug: "ied-noventa-y-cuatro",
    title: "El 94% que nadie lee en el récord de inversión extranjera",
    dek: "México captó 23.591 millones de dólares en el primer trimestre. Es el mejor arranque de año de la historia. También es el que menos capital nuevo trajo en una década.",
    kicker: "Industria",
    section: "ideas",
    authorId: "daniel-pinto",
    signedName: "Daniel Pinto",
    publishedAt: "2026-08-21",
    updatedAt: "2026-08-22",
    readMinutes: 8,
    image: "/photos/monterrey-factory.jpg",
    imageAlt: "Planta industrial en el corredor manufacturero del norte de México",
    caption: "El récord es real. El capital nuevo, no tanto.",
    city: "Ciudad de México",
    pace: "fondo",
    tags: ["industria", "nearshoring", "fondo"],
    pullQuote: "Un titular de récord con 94% de reinversión describe un país donde el capital que ya llegó se está quedando quieto.",
    body: [
      { type: "p", text: "El dato del titular es real: 23.591 millones de dólares de inversión extranjera directa en el primer trimestre de 2026, un alza de 10,4% interanual, máximo histórico para un primer trimestre. México cerró 2025 con 40.900 millones, quinto año consecutivo de récord, y subió del puesto 25 al 19 en el Índice de Confianza de IED de Kearney." },
      { type: "stat", value: "94,2%", label: "Reinversión de utilidades" },
      { type: "stat", value: "US$ 1.705 M", label: "Inversión nueva 1T" },
      { type: "stat", value: "−26,6%", label: "Caída de greenfield" },
      { type: "quote", text: "Un titular de récord con 94% de reinversión describe un país donde el capital que ya llegó se está quedando quieto.", cite: "Daniel Pinto" },
      { type: "p", text: "El dato del subtítulo también es real, y viene de la misma tabla." },
      { type: "p", text: "De esos 23.591 millones, 22.222 corresponden a reinversión de utilidades: ganancias generadas por empresas extranjeras que ya operan en el país y que deciden no repatriarlas. Es el 94,2% del total. Las nuevas inversiones —capital fresco de empresas que entran, plantas que se construyen desde cero— sumaron 1.705 millones, el 7,2%. Las cuentas entre compañías restaron 336 millones." },
      { type: "p", text: "El IMCO, comparando contra cifras actualizadas del mismo trimestre de 2025, encuentra que las nuevas inversiones cayeron 26,6% mientras la reinversión creció 14,35%." },
      { type: "h2", text: "Por qué la distinción importa" },
      { type: "p", text: "No toda la IED hace el mismo trabajo. La reinversión de utilidades es una señal de confianza genuina: una multinacional que gana dinero en México y elige dejarlo acá está diciendo algo. Pero no genera necesariamente capacidad productiva nueva, ni empleo nuevo, ni transferencia de tecnología al ritmo en que lo hace una planta greenfield. Puede ser mantenimiento. Puede ser capital de trabajo. Puede ser, simplemente, un balance que no se movió." },
      { type: "p", text: "El IMCO ofrece la comparación histórica que ordena el asunto: entre 2015 y 2017, las nuevas inversiones representaban entre 20,2% y 36,3% del total de la IED. Hoy están en 7,2%." },
      { type: "p", text: "Es decir: el flujo total subió y su composición se degradó. Estamos recibiendo más dinero de gente que ya estaba, y menos de gente que no estaba." },
      { type: "p", text: "La UNCTAD, en su World Investment Report 2026, dijo lo mismo con más diplomacia: México captó 41.000 millones en 2025 contra 38.000 el año previo, pero la incertidumbre comercial sigue frenando decisiones sobre plantas nuevas." },
      { type: "h2", text: "Los tres cuellos de botella que ya no son de demanda" },
      { type: "p", text: "Acá está la parte que las presentaciones de nearshoring omiten. El problema dejó de ser convencer a las empresas de que México es el lugar. Buena parte ya está convencida. El problema es que el país no puede absorber lo que llegaría si dijeran que sí." },
      { type: "p", text: "Energía. La AMPIP reportó que el 91% de los parques industriales tuvo fallas eléctricas en 2023. Energía limpia agregada en una planilla nacional no sirve: los proyectos industriales necesitan potencia firme en un nodo específico de la red, en una fecha específica. Ese es un problema de infraestructura física, no de política energética." },
      { type: "p", text: "Agua. Varias zonas del norte —justamente las del corredor manufacturero— están bajo estrés hídrico. Y el agua es el insumo donde la conversación pasa de técnica a social más rápido que cualquier otra." },
      { type: "p", text: "Talento. ManpowerGroup reporta que en 2026 el 67% de los empleadores tiene dificultad para llenar vacantes. Ese número no se resuelve con incentivos fiscales." },
      { type: "h2", text: "El vínculo con el T-MEC" },
      { type: "p", text: "La composición de la IED y la decisión del 1 de julio no son dos historias. Son la misma." },
      { type: "p", text: "Un horizonte de planificación de doce meses es suficiente para justificar ampliar una línea que ya existe. No es suficiente para justificar una planta nueva de 800 millones de dólares con recuperación a quince años. La reinversión de utilidades sube y las nuevas inversiones caen porque eso es exactamente lo que hace el capital cuando no sabe cuáles van a ser las reglas de origen en 2029." },
      { type: "p", text: "La encuesta de expectativas empresariales del IPADE lo confirma desde el lado local: sólo el 40% de los empresarios considera que es buen momento para invertir en México, contra 54,4% en el primer semestre de 2024. La cautela no es sólo extranjera." },
      { type: "h2", text: "El indicador que hay que mirar" },
      { type: "p", text: "México ¿Cómo Vamos? lanzó un semáforo específico de nuevas inversiones para monitorear si el país está capitalizando la segunda ola de nearshoring. Es la métrica correcta y debería reemplazar al total de IED en cualquier conversación seria." },
      { type: "p", text: "Un titular de récord con 94% de reinversión no describe un país que está atrayendo capital. Describe un país donde el capital que ya llegó se está quedando quieto y esperando." },
    ],
  },
  {
    slug: "pix-problema-comercial",
    title: "Pix es el mayor caso de política industrial digital de la región. Por eso es ahora un problema comercial.",
    dek: "Movió 35,3 billones de reales en 2025 y cobra 0,33% donde las tarjetas cobran 2% a 5%. Washington abrió una investigación. La pelea de fondo no es por comisiones.",
    kicker: "Brasil",
    section: "ideas",
    authorId: "daniel-pinto",
    signedName: "Daniel Pinto",
    publishedAt: "2026-08-20",
    updatedAt: "2026-08-22",
    readMinutes: 10,
    image: "/photos/saopaulo-fintech.jpg",
    imageAlt: "Pagos digitales en São Paulo",
    caption: "0,33% contra 2% a 5%. El diferencial es el hecho económico.",
    city: "São Paulo",
    pace: "fondo",
    tags: ["fintech", "pagos", "fondo"],
    pullQuote: "Visa y Mastercard no están perdiendo su negocio en Brasil. Están perdiendo el control del riel.",
    body: [
      { type: "p", text: "Cuando el Banco Central de Brasil lanzó Pix en noviembre de 2020, la ambición declarada era modesta: transferencias instantáneas, 24 horas, siete días. Cinco años y medio después, el sistema procesó 35,3 billones de reales en 2025, con un crecimiento cercano al 34% respecto del año anterior, según datos oficiales del propio Banco Central. Los usuarios superan los 180 millones, de los cuales más de 162 millones son personas físicas. En un país de 215 millones de habitantes, eso significa que Pix es prácticamente universal entre adultos." },
      { type: "stat", value: "R$ 35,3 bi", label: "Volumen Pix 2025" },
      { type: "stat", value: "0,33%", label: "Comisión al comercio" },
      { type: "stat", value: "180 M", label: "Usuarios" },
      { type: "quote", text: "Visa y Mastercard no están perdiendo su negocio en Brasil. Están perdiendo el control del riel.", cite: "Daniel Pinto" },
      { type: "p", text: "La cifra que le importa a cualquiera que venda algo: para personas físicas el servicio es gratuito, y para comercios la comisión ronda el 0,33%, contra el 2% a 5% de las tarjetas tradicionales." },
      { type: "p", text: "Ese diferencial es el hecho económico central de la última década en pagos latinoamericanos, y explica por qué el asunto escaló a mesa de gobierno en Washington." },
      { type: "h2", text: "La cronología del conflicto" },
      { type: "p", text: "En septiembre de 2025, la administración Trump respaldó abiertamente a Visa y Mastercard, y el Representante Comercial de Estados Unidos abrió una investigación formal contra Pix argumentando que el sistema genera una desventaja competitiva injusta para empresas estadounidenses del sector. Un informe de la Casa Blanca de abril de 2026 volvió a señalarlo como perjudicial para las compañías globales de tarjetas." },
      { type: "p", text: "Brasil respondió con una campaña de comunicación gubernamental cuya traducción aproximada es \"el Pix es nuestro, amigo\". Lula fue directo: nadie va a hacer que el gobierno brasileño cambie el Pix. El gobierno trata el asunto como soberanía tecnológica, no como política de competencia." },
      { type: "p", text: "Es una posición sólida, pero conviene entender por qué el argumento comercial estadounidense es más incómodo de lo que parece: Pix no es un competidor privado que ganó. Es una infraestructura estatal, gratuita para el consumidor, que desplazó a operadores privados en un mercado donde esos operadores pagaban impuestos y hacían inversión. Que el resultado sea bueno para el consumidor brasileño no responde la pregunta de si es una barrera comercial. Ambas cosas pueden ser ciertas." },
      { type: "h2", text: "El dato que desarma la narrativa de canibalización" },
      { type: "p", text: "Acá está lo que casi nadie reporta, y que complica las dos versiones." },
      { type: "p", text: "Las tarjetas de crédito y débito en Brasil no se murieron. Alcanzaron el equivalente al 35,1% del PIB en el primer trimestre de 2026, y el volumen de tarjetas activas creció 47,5% entre 2020 y 2025 —es decir, durante exactamente el período de expansión de Pix." },
      { type: "p", text: "La lectura más razonable de esos números: Pix funciona como puerta de entrada a la bancarización, y una parte de esa población recién bancarizada accede después a productos de crédito. No es sustitución pura. Es un mercado que se agrandó, con dos rieles conviviendo, uno para transaccionar y otro para financiar." },
      { type: "p", text: "Lo cual reformula la pelea. Visa y Mastercard no están perdiendo su negocio en Brasil. Están perdiendo el control del riel. Y eso, para una red de pagos, es peor." },
      { type: "h2", text: "Las tres funciones que cambian el juego" },
      { type: "p", text: "La agenda evolutiva del Banco Central es donde hay que mirar en los próximos dieciocho meses." },
      { type: "p", text: "Pix Automático. Débito recurrente. Cumplió su primer año en 2026 y todavía tiene base chica, pero los datos de PagBrasil —primera procesadora en habilitarlo para e-commerce— muestran entre el cuarto trimestre de 2025 y el primero de 2026 un salto de 181% en nuevos usuarios, 182% en transacciones y 170% en ingresos procesados. El punto técnico que importa para cualquier negocio de suscripción: el débito recurrente sobre Pix elimina el churn involuntario —esas cancelaciones que no reflejan una decisión del cliente sino una tarjeta vencida o una autorización rechazada. Desde octubre de 2026, las cuentas salario también pueden operar con Pix Automático, lo que amplía de golpe la base elegible." },
      { type: "p", text: "Pix Parcelado. Pagos en cuotas sin depender de la tarjeta. Alrededor de 60 millones de brasileños no tienen acceso a tarjeta de crédito. Si el Banco Central estandariza esta modalidad, esa población accede a compra financiada por una vía que el sistema bancario nunca le ofreció." },
      { type: "p", text: "Pix internacional. Previsto para 2027, con la ambición de interconectar sistemas de pago instantáneo entre países. Ahí es donde el conflicto con Washington deja de ser doméstico." },
      { type: "h2", text: "Lo que esto significa fuera de Brasil" },
      { type: "p", text: "El efecto demostración ya está corriendo. Durante el primer bimestre de 2026, el volumen de operaciones mediante sistemas similares a Pix en Chile se multiplicó por doce respecto del año anterior. Google integró Pix en Google Pay y Chrome, con más de 21,4 millones de transacciones diarias por API." },
      { type: "p", text: "La lección para cualquier país de la región no es \"copien Pix\". Es más específica y más difícil: Brasil demostró que un regulador puede iterar producto a velocidad de startup. Cinco años, cuatro funcionalidades mayores, adopción universal. Ese es el activo, no el sistema." },
      { type: "p", text: "Y para cualquier empresa que cobre en la región, la pregunta operativa es una sola: cuánto de su estructura de costos está construida sobre un interchange que en Brasil ya bajó al 0,33% y que en el resto de la región sigue en 2% a 5% únicamente porque todavía no llegó el equivalente." },
    ],
  },
  {
    slug: "mercado-libre-dejo-de-ser-ecommerce",
    title: "Mercado Libre dejó de ser una empresa de e-commerce",
    dek: "Superó los 10.000 millones de dólares de ingresos trimestrales. El comercio electrónico se desacelera en sus dos mercados clave. Las dos cosas son ciertas y no se contradicen.",
    kicker: "Negocios",
    section: "ideas",
    authorId: "daniel-pinto",
    signedName: "Daniel Pinto",
    publishedAt: "2026-08-19",
    updatedAt: "2026-08-22",
    readMinutes: 9,
    image: "/photos/buenos-aires.jpg",
    imageAlt: "Buenos Aires, hora laboral",
    caption: "En Argentina, el 64% de la facturación ya es Mercado Pago.",
    city: "Buenos Aires",
    pace: "fondo",
    tags: ["fintech", "retail", "fondo"],
    pullQuote: "El marketplace dejó de ser el negocio y pasó a ser el canal de adquisición.",
    body: [
      { type: "p", text: "En el segundo trimestre de 2026, Mercado Libre reportó ingresos por 10.200 millones de dólares, un crecimiento de 50% interanual y la primera vez que la compañía supera los diez mil millones en un trimestre." },
      { type: "stat", value: "US$ 10.200 M", label: "Ingresos 2T 2026" },
      { type: "stat", value: "64%", label: "Facturación argentina en Pago" },
      { type: "stat", value: "73%", label: "Alza de publicidad" },
      { type: "quote", text: "El marketplace dejó de ser el negocio y pasó a ser el canal de adquisición.", cite: "Daniel Pinto" },
      { type: "p", text: "En el mismo formulario 10-Q presentado ante la SEC, la empresa dejó constancia de algo que no suele decir explícitamente: demanda de consumo más débil en Argentina y México." },
      { type: "p", text: "Las dos frases describen la misma compañía en el mismo trimestre. Entender por qué no se contradicen es entender qué es Mercado Libre hoy." },
      { type: "h2", text: "Los números de la parte que crece" },
      { type: "p", text: "Mercado Pago superó por primera vez los 100.000 millones de dólares de volumen total de pagos, con un crecimiento de 56% interanual en dólares. Los usuarios activos mensuales llegaron a 88 millones, un 30% más. Los activos bajo gestión subieron 68% hasta 23.000 millones. La cartera de crédito se expandió 75% y superó los 16.000 millones, con 2,6 millones de tarjetas emitidas sólo en ese trimestre." },
      { type: "p", text: "Y el negocio que casi nadie mira: los ingresos por publicidad crecieron 73% interanual en dólares, y la participación de Mercado Ads superó por primera vez el 10% de todo el mercado de publicidad digital de América Latina. En retail media específicamente, datos compilados por eMarketer ubican a Mercado Libre en torno al 55,6% del mercado regional, contra 17,7% de Amazon." },
      { type: "h2", text: "Los números de la parte que se frena" },
      { type: "p", text: "Argentina es el mejor lugar para ver la transición porque es donde está más avanzada." },
      { type: "p", text: "El GMV argentino creció 38% interanual en dólares constantes entre abril y junio de 2026. Suena bien hasta que se compara: en el mismo período de 2025 había crecido 75%, y en el primer trimestre de 2026 había sido 41%. La cantidad de artículos vendidos cuenta la historia con más claridad todavía: 22% de crecimiento, contra 35% el trimestre previo y 46% un año atrás." },
      { type: "p", text: "Ahora el dato que explica por qué eso no aparece en la línea final. De los 1.839 millones de dólares que facturó la operación argentina entre abril y junio, los servicios financieros liderados por Mercado Pago aportaron 1.182 millones. El 64%." },
      { type: "p", text: "En Argentina, Mercado Libre ya es una empresa financiera con un marketplace adjunto." },
      { type: "h2", text: "La tesis, dicha sin eufemismos" },
      { type: "p", text: "El marketplace dejó de ser el negocio y pasó a ser el canal de adquisición. Es el lugar donde se conoce al usuario, se le observa el comportamiento de compra, se le estima capacidad de pago y se le origina crédito. Después ese mismo tráfico se le vende a las marcas como inventario publicitario." },
      { type: "p", text: "Es, estructuralmente, el modelo de Amazon —donde el margen viene de AWS y de publicidad, no de vender cosas— pero con una diferencia relevante: en América Latina el sustituto de AWS es el sistema financiero, porque la penetración bancaria dejó un hueco mucho más grande que el de la infraestructura cloud." },
      { type: "p", text: "Eso hace que la desaceleración del e-commerce sea, hasta cierto punto, tolerable. Y también hace que el riesgo cambie de naturaleza." },
      { type: "h2", text: "Dónde está el riesgo real" },
      { type: "p", text: "Una cartera de crédito que crece 75% interanual en un entorno donde la propia empresa reporta demanda de consumo más débil es la línea que hay que vigilar. No porque haya evidencia de deterioro —no la hay en los datos públicos—, sino porque es la combinación que históricamente produce sorpresas: originación acelerada sobre una base de consumidores cuyo ingreso real está bajo presión." },
      { type: "p", text: "El segundo frente es competitivo y llega desde afuera. Shein, Temu y Tiendamia disputan hoy al mismo consumidor que hace tres años sólo tenía a Mercado Libre. La respuesta de la compañía fue abrir en diciembre de 2025 su primer centro de fulfillment en China, que ya despacha a sus cinco principales mercados bajo un modelo fulfilled-from-China." },
      { type: "p", text: "Esa jugada es simultáneamente defensiva y ofensiva: defiende precio frente a los entrantes asiáticos y, si escala, mejora margen por control de cadena. Pero también significa que Mercado Libre eligió competir en el terreno del rival en lugar de diferenciarse de él, lo cual es una apuesta a la escala logística pura." },
      { type: "h2", text: "Para quien vende en la plataforma" },
      { type: "p", text: "Hay una consecuencia práctica que los vendedores todavía no terminan de digerir. Si el margen de la plataforma migra hacia crédito y publicidad, la presión sobre el vendedor deja de ser la comisión de venta y pasa a ser el costo de visibilidad. Un marketplace donde la publicidad crece 73% anual es un marketplace donde el tráfico orgánico vale cada vez menos." },
      { type: "p", text: "Ese es el número que cualquier marca con operación en Mercado Libre debería estar midiendo trimestre a trimestre: qué porcentaje de sus ventas en la plataforma requiere inversión publicitaria hoy, contra hace dos años. Es la métrica que anticipa el margen del año que viene." },
    ],
  },
  {
    slug: "chile-vertimiento-6000-gwh",
    title: "Chile botó más de 6.000 GWh de energía limpia el año pasado",
    dek: "Es cerca del 18% de todo lo que produjeron el sol y el viento. El país resolvió cómo generar y no resolvió cómo transportar. Las baterías están arbitrando una falla de infraestructura.",
    kicker: "Clima",
    section: "climate",
    authorId: "daniel-pinto",
    signedName: "Daniel Pinto",
    publishedAt: "2026-08-18",
    updatedAt: "2026-08-22",
    readMinutes: 11,
    image: "/photos/climate-atacama.jpg",
    imageAlt: "Campo solar en el desierto de Atacama",
    caption: "Chile resolvió cómo generar. No resolvió cómo transportar.",
    city: "Santiago",
    pace: "fondo",
    tags: ["energia", "clima-tech", "fondo"],
    pullQuote: "Un mercado eléctrico donde el mismo producto vale casi nada a 1.300 kilómetros de donde vale mucho no es un mercado.",
    body: [
      { type: "p", text: "Hay una palabra técnica para esto y conviene aprenderla: vertimiento. En inglés se llama curtailment; en España, restricciones técnicas; en Alemania, Einspeisemanagement. Es la desconexión deliberada de una central generadora cuando la red no puede absorber ni transportar lo que produce." },
      { type: "stat", value: "6.084 GWh", label: "Vertimiento 2025" },
      { type: "stat", value: "18,1%", label: "De la generación variable" },
      { type: "stat", value: "3 GW", label: "Baterías en operación" },
      { type: "quote", text: "Un mercado eléctrico donde el mismo producto vale casi nada a 1.300 kilómetros de donde vale mucho no es un mercado.", cite: "Daniel Pinto" },
      { type: "p", text: "En Chile, en 2025, el vertimiento superó los 6 TWh —6.084 GWh según la Asociación Chilena de Energías Renovables y Almacenamiento—, alrededor de 8% más que el año anterior. En 2024 habían sido 5.908 GWh, equivalentes al 18,1% de toda la generación renovable variable del país. Ember, midiendo sólo solar y eólica, calculó 5.642 GWh vertidos ese año: el 19% de todo lo que esas dos fuentes entregaron, y el 6,6% de toda la electricidad generada en Chile." },
      { type: "p", text: "Para dimensionar: la tasa de vertimiento chilena de 18,1% está entre las más altas documentadas en sistemas eléctricos consolidados. China, en el mismo período, reportó cifras en torno al 6,6% en solar y 5,7% en eólica." },
      { type: "p", text: "Y el año en curso viene peor. Entre enero y febrero de 2026, el vertimiento de eólica, solar e hidro en el SEN totalizó unos 1.402 GWh, un alza de 29,3% frente al mismo período de 2025 y 44,1% sobre 2024." },
      { type: "h2", text: "Lo que este número significa en pesos" },
      { type: "p", text: "Cada GWh vertido es energía que existía, que tenía costo marginal cercano a cero, que nadie pagó y que se perdió. Un cálculo de mercado sitúa el problema de vertimiento chileno en torno a los 562 millones de dólares." },
      { type: "p", text: "Pero el costo directo es sólo la mitad. La otra mitad es el desacople de precios: en el norte, con factores de planta excepcionales y transmisión saturada, los costos marginales caen cerca de cero; en la zona central, donde está la demanda, los precios se mantienen altos y el sistema sigue dependiendo de generación térmica para cubrir carga y aportar inercia." },
      { type: "p", text: "Un mercado eléctrico donde el mismo producto vale casi nada a 1.300 kilómetros de donde vale mucho no es un mercado. Es dos mercados con un cable insuficiente en el medio." },
      { type: "h2", text: "La respuesta que funcionó" },
      { type: "p", text: "Chile se puso como meta 2 GW de almacenamiento a 2030. Los alcanzó cinco años antes. A junio de 2026 el país tenía más de 3 GW de baterías en operación y más de 1 GW en pruebas, con más de 20 GWh en construcción y una proyección de superar los 28 GWh a 2030, según S&P Global." },
      { type: "p", text: "Las instalaciones son de escala global, no regional. Grenergy inauguró en junio de 2026 el BESS Elena, de 3,5 GWh en el desierto de Atacama, actualmente la mayor planta de baterías en operación en las Américas por capacidad energética, integrada a su complejo híbrido Oasis de Atacama. Copenhagen Infrastructure Partners puso en operación comercial el BESS Arena, 220 MW y 1,1 GWh, también en Atacama y en modalidad standalone." },
      { type: "p", text: "El impacto es medible: sin los sistemas de almacenamiento operativos, el vertimiento de 2025 habría llegado a unos 8 TWh en lugar de 6." },
      { type: "p", text: "Brasil, Colombia y Argentina están siguiendo el marco regulatorio chileno de cerca, porque van camino al mismo problema. Brasil ya vertió el 20,6% de su generación solar y eólica en 2025, más del doble que el 9,3% del año previo, con pérdidas sectoriales estimadas por Volt Robotics en 1.230 millones de dólares." },
      { type: "h2", text: "La trampa que nadie está pricing" },
      { type: "p", text: "Acá está el punto que debería incomodar a quien esté evaluando un proyecto de almacenamiento en Chile hoy." },
      { type: "p", text: "El negocio de las baterías chilenas se sostiene sobre un spread: comprar energía a costo casi cero al mediodía en el norte y venderla cara en las horas de punta. Ese spread existe porque la transmisión está saturada. Es, literalmente, la monetización de una falla de infraestructura." },
      { type: "p", text: "La solución estructural a esa falla ya está proyectada. La línea Kimal-Lo Aguirre, unos 1.350 kilómetros y 3.000 MW en tecnología HVDC —corriente continua de alta tensión—, va a permitir mover volúmenes grandes de generación solar del norte directamente a los centros de consumo del centro y sur. Está proyectada para alrededor de 2030." },
      { type: "p", text: "Cuando llegue, dos cosas van a pasar simultáneamente: el volumen de vertimiento que las baterías tienen que resolver se va a reducir, y los spreads de arbitraje que hacen atractiva la economía de los BESS se van a comprimir." },
      { type: "p", text: "Un proyecto de almacenamiento con período de recuperación que se extienda más allá de 2030 y que esté modelado sobre los spreads actuales está asumiendo, implícitamente, que Kimal-Lo Aguirre se va a atrasar. Puede ser una apuesta razonable —expertos del sector señalan que la línea debió estar operativa hace años y que la planificación centralizada de transmisión avanzó más lento de lo esperado— pero es una apuesta, y debería figurar como tal en el modelo." },
      { type: "h2", text: "El dato que resume todo" },
      { type: "p", text: "En 2023, la generación renovable no convencional representaba alrededor del 36,5% de la matriz chilena. Ese año se vertió el 8,6% de lo que produjo. En 2024, con más capacidad instalada, se vertió el 18,1%." },
      { type: "p", text: "La curva de generación va más rápido que la curva de transmisión, y el diferencial entre ambas se llama energía tirada a la basura. Chile agregó paneles a una velocidad admirable y cables a una velocidad burocrática. El resultado es que el país tiene uno de los mejores recursos solares del mundo y no puede usarlo entero." },
    ],
  },
  {
    slug: "litio-no-volvio",
    title: "El litio no volvió, y eso es lo importante",
    dek: "El carbonato tocó un mínimo de cuatro años en 2025 y se recuperó a la mitad de lo que valía en 2022. El triángulo diseñó su política para un precio que no existe.",
    kicker: "Clima",
    section: "climate",
    authorId: "daniel-pinto",
    signedName: "Daniel Pinto",
    publishedAt: "2026-08-17",
    updatedAt: "2026-08-22",
    readMinutes: 9,
    image: "/photos/litio-salares.jpg",
    imageAlt: "Pozas de evaporación de litio en el desierto",
    caption: "El precio de equilibrio no es 80.000 dólares. Nunca lo fue.",
    city: "Santiago",
    pace: "fondo",
    tags: ["energia", "clima-tech", "fondo"],
    pullQuote: "Chile tiene el mejor recurso del mundo y una posición marginal en la cadena que gana dinero.",
    body: [
      { type: "p", text: "A fines de 2022, el carbonato de litio se transó cerca de los 80.000 dólares por tonelada y toda la conversación política del Cono Sur cambió de tema. Chile, Argentina y Bolivia dejaron de hablar de minería y empezaron a hablar de renta. Se diseñaron esquemas de participación estatal, se discutieron royalties, se anunciaron empresas nacionales. La palabra \"OPEP del litio\" apareció en portadas." },
      { type: "stat", value: "US$ 10.000", label: "Precio promedio 2025 / t" },
      { type: "stat", value: "US$ 80.000", label: "El pico de 2022" },
      { type: "stat", value: "−50%", label: "Capex sectorial" },
      { type: "quote", text: "Chile tiene el mejor recurso del mundo y una posición marginal en la cadena que gana dinero.", cite: "Daniel Pinto" },
      { type: "p", text: "Cuatro años después, los números son estos." },
      { type: "p", text: "Los precios promedio de 2025 se ubicaron en torno a los 10.000 dólares por tonelada, después de caer a un mínimo de cuatro años cerca de los 8.000 a comienzos de ese año. Bernstein calculó que a ese nivel los retornos de la industria quedaron en cero y el gasto de capital del sector se recortó aproximadamente a la mitad. En agosto de 2025, según Cochilco, el carbonato CIF Asia cotizaba a 10.100 dólares la tonelada y el hidróxido a 8.600." },
      { type: "p", text: "Después vino una recuperación parcial. Los precios spot se movieron hacia los 13.000 dólares por tonelada. SQM, por boca de su ejecutivo Carlos Díaz, proyectó en abril de 2026 un rango de 15 a 18 dólares por kilogramo para el año, con estabilización hacia el cierre. Bernstein fue más optimista: 17.000 dólares por tonelada en 2026 y 25.000 en 2027." },
      { type: "p", text: "Y hay una lectura contraria que conviene tener sobre la mesa. Rothschild & Co Redburn advirtió que la industria está respondiendo con producción elevada en 2026, adelantando demanda, y que una reversión de esa sobreproducción llevaría a una desaceleración el año siguiente. Su proyección: equivalentes de carbonato entre 15 y 16 dólares por kilogramo hacia fin de año, con retorno al superávit de mercado en 2027." },
      { type: "h2", text: "El punto que sobrevive a cualquier proyección" },
      { type: "p", text: "Se puede discutir si el litio va a 17.000 o a 25.000 dólares. Lo que no está en discusión es que no va a 80.000." },
      { type: "p", text: "Ese número era un artefacto de un shock de oferta y de un ciclo de acumulación de inventarios, no un precio de equilibrio. La oferta y demanda global estuvieron ampliamente equilibradas en los primeros nueve meses de 2025 —1,18 millones de toneladas LCE contra 1,15 millones—, y el mercado global de compuestos de litio alcanzó 430.172 toneladas en 2025 con proyecciones de crecimiento a una tasa compuesta de 7,5% anual." },
      { type: "p", text: "Un mercado que crece 7,5% al año con oferta elástica es un mercado de commodity industrial normal. No es un mercado de escasez estratégica." },
      { type: "h2", text: "Lo que eso le hace a la política pública del triángulo" },
      { type: "p", text: "Acá está la incomodidad. Los esquemas de participación estatal, los royalties progresivos y las estructuras de asociación público-privada que se diseñaron entre 2022 y 2024 fueron calibrados sobre un supuesto de renta extraordinaria. Cuando la renta extraordinaria no está, esos esquemas dejan de repartir un excedente y empiezan a competir con el retorno mínimo que exige el capital para desarrollar el proyecto." },
      { type: "p", text: "El resultado previsible es que los proyectos marginales no se hacen, y los que se hacen se hacen más lento. Con capex sectorial recortado a la mitad, la disciplina viene del mercado, no del regulador." },
      { type: "p", text: "Argentina, con el RIGI, tomó el camino opuesto: en lugar de capturar renta, subsidiar retorno. Es coherente con su punto de partida —un país que necesitaba atraer capital a cualquier costo— y es una decisión legítima. Pero significa que el triángulo ya no tiene una posición común, y que la competencia por inversión entre vecinos va a ser un tema de la próxima década." },
      { type: "h2", text: "Dónde se fue el valor" },
      { type: "p", text: "Hay un dato que el debate regional casi nunca incorpora. Los principales productores del mundo incluyen a Albemarle, SQM, Ganfeng, Tianqi y Arcadium —esta última hoy parte de Rio Tinto tras la adquisición. Es una lista de mineras y refinadoras, con presencia asiática significativa en la refinación." },
      { type: "p", text: "Y la volatilidad reciente del precio no la fijó Sudamérica. La subida de mediados de 2025 respondió a la paralización temporal del yacimiento Jianxiawo de CATL en China, que representa alrededor del 3% de la producción mundial y unas 46.000 toneladas anuales de LCE. Cuando CATL obtuvo el permiso de seguridad y reanudó operaciones tras casi un año de suspensión, la presión bajista volvió." },
      { type: "p", text: "El precio del litio latinoamericano se decide, en buena medida, por decisiones regulatorias en China." },
      { type: "p", text: "El carbonato de grado batería obtiene primas significativas sobre el grado industrial. Ahí está el margen. Y ahí es donde la región sigue sin construir capacidad relevante: el debate de los últimos cuatro años se consumió casi por completo discutiendo cómo repartir la renta de la extracción, mientras el valor migraba a la refinación, al cátodo y a la celda." },
      { type: "p", text: "Chile tiene el mejor recurso del mundo y una posición marginal en la cadena que gana dinero. Eso no lo arregla el precio." },
    ],
  },
  {
    slug: "vaca-muerta-sacar-del-pais",
    title: "Vaca Muerta ya produce. El problema ahora es sacarlo del país.",
    dek: "El superávit energético del primer semestre fue de 6.987 millones de dólares, el mayor de la historia. El cuello de botella dejó de ser geológico y pasó a ser de acero y puertos.",
    kicker: "Argentina",
    section: "climate",
    authorId: "daniel-pinto",
    signedName: "Daniel Pinto",
    publishedAt: "2026-08-16",
    updatedAt: "2026-08-22",
    readMinutes: 10,
    image: "/photos/lima-port.jpg",
    imageAlt: "Infraestructura de evacuación y puerto",
    caption: "El cuello de botella dejó de ser geológico. Pasó a ser de acero y puertos.",
    city: "Buenos Aires",
    pace: "fondo",
    tags: ["energia", "industria", "fondo"],
    pullQuote: "Producir sin ductos es producir para el mercado interno a precio interno.",
    body: [
      { type: "p", text: "Argentina tuvo en 2022 un déficit energético de unos 4.000 millones de dólares. Entre enero y junio de 2026, la balanza comercial energética registró un superávit de 6.987 millones, el mayor para un primer semestre desde que existen registros, con un crecimiento interanual de 87%, según la Bolsa de Comercio de Rosario." },
      { type: "stat", value: "US$ 6.987 M", label: "Superávit energético 1S" },
      { type: "stat", value: "790.000", label: "Barriles diarios 2025" },
      { type: "stat", value: "+21 pp", label: "Rentabilidad extra RIGI" },
      { type: "quote", text: "Producir sin ductos es producir para el mercado interno a precio interno.", cite: "Daniel Pinto" },
      { type: "p", text: "Es un giro de cuenta corriente que, en cualquier país, se estudiaría durante una década." },
      { type: "p", text: "Los fundamentos son productivos, no financieros. Más del 68% del petróleo y el 67% del gas natural que produce Argentina provienen hoy de desarrollos no convencionales de Vaca Muerta. Y más del 70% del incremento de las exportaciones se explica por aumento de producción, no por precio." },
      { type: "p", text: "La escala: el promedio diario de extracción superó los 790.000 barriles durante 2025, tras crecer 9,2% frente al año anterior. La BCR proyecta que la producción petrolera crezca 16% en 2026, lo que llevaría al país al mayor nivel de extracción de su historia." },
      { type: "p", text: "BBVA Research estima que el superávit energético podría escalar a 13.600 millones de dólares en 2026, después de cerrar 2025 en 7.900 millones. Sería un salto interanual de 72%." },
      { type: "h2", text: "El cuello de botella cambió de naturaleza" },
      { type: "p", text: "Durante quince años, la pregunta sobre Vaca Muerta fue si el recurso era comercialmente explotable. Esa pregunta está respondida. Según análisis técnico de la consultora Aleph Energy, hacia fines de 2025 y principios de 2026 la productividad de un pozo tipo en la cuenca neuquina se consolidó cerca de los 500 mil barriles en apenas tres años de operación." },
      { type: "p", text: "La pregunta hoy es distinta y mucho más aburrida: cómo se saca." },
      { type: "p", text: "El país tiene más de 16.000 kilómetros de gasoductos troncales, pero BBVA Research estima que hacen falta entre 15.000 y 20.000 millones de dólares adicionales en oleoductos, terminales portuarias y proyectos de exportación para acompañar la expansión." },
      { type: "p", text: "El proyecto que concentra las expectativas es Vaca Muerta Oil Sur. Conecta Allen, en Río Negro, con Punta Colorada, a lo largo de casi 600 kilómetros. Fue aprobado bajo el RIGI en marzo de 2025 y su puesta en marcha está prevista para noviembre de 2026. Permitiría evacuar inicialmente 190.000 barriles diarios adicionales, con capacidad de llegar hasta 550.000." },
      { type: "p", text: "Si esa infraestructura entra en operación según lo previsto, la BCR proyecta exportaciones energéticas por encima de 18.500 millones de dólares en 2027." },
      { type: "h2", text: "El número que nadie quiere poner en la conversación" },
      { type: "p", text: "El RIGI —Régimen de Incentivo para Grandes Inversiones— acumula proyectos presentados por más de 133.000 millones de dólares. Es, por lejos, la política de atracción de inversión más agresiva que Argentina haya implementado." },
      { type: "p", text: "Y hay un dato de Aleph Energy que permite dimensionar exactamente cuánto cuesta. En el escenario de marzo de 2026, con el Brent en 100 dólares tras el conflicto en Medio Oriente, la rentabilidad de un pozo petrolero promedio en Vaca Muerta era de 67% sin RIGI y de 88% bajo el esquema de incentivos." },
      { type: "p", text: "Veintiún puntos porcentuales de rentabilidad adicional. Eso es el tamaño del subsidio fiscal, medido en la única unidad que importa." },
      { type: "p", text: "Nada de esto significa que el RIGI esté mal diseñado. Un país que había perdido acceso a financiamiento internacional necesitaba una señal extrema, y la señal funcionó: la inversión llegó. Pero un régimen que entrega 21 puntos de rentabilidad con Brent a 100 dólares es un régimen que hay que evaluar contra el escenario contrario, y ese ejercicio no se está haciendo públicamente." },
      { type: "h2", text: "Los tres riesgos que sí importan" },
      { type: "p", text: "Precio. El superávit de 2026 se construyó, en parte, sobre un Brent alto por razones geopolíticas. La producción sostiene el volumen; el precio decide el valor. Argentina concentra el 46% de sus ventas de crudo en el bloque USMCA, lo que es una buena diversificación comercial y una mala diversificación de riesgo si Norteamérica ajusta." },
      { type: "p", text: "Secuencia. La captura de renta depende de la interconexión física. Producir sin ductos es producir para el mercado interno a precio interno. Cada mes de atraso en VMOS es margen que no se realiza." },
      { type: "p", text: "Concentración. El complejo petróleo y gas representa actualmente el 12,5% de las exportaciones argentinas, y el crudo por sí solo llegó al 5,4% en febrero de 2026. Es una proporción que crece rápido. Un país que reemplaza dependencia de la soja por dependencia del shale sigue siendo un país con exportaciones concentradas en un commodity de precio internacional. La lección de los últimos cincuenta años de historia económica argentina es que eso no es una solución estructural, es una tregua." },
      { type: "h2", text: "Lo que hay que mirar en los próximos doce meses" },
      { type: "p", text: "Noviembre, cuando VMOS debería entrar en operación. La Argentina Energy Week del 8 al 10 de septiembre, donde gobernadores, petroleras y fondos van a definir el tono. Y el volumen efectivamente evacuado versus el volumen producido, que es la única métrica que distingue un boom real de un anuncio." },
    ],
  },
  {
    slug: "vc-mas-dinero-menos-startups",
    title: "Más dinero, menos startups: qué dice realmente el venture capital latinoamericano",
    dek: "El capital desplegado subió 13,8%. El número de operaciones cayó al nivel más bajo desde 2017. Y las rondas de crecimiento se desplomaron 57%.",
    kicker: "Ideas",
    section: "ideas",
    authorId: "daniel-pinto",
    signedName: "Daniel Pinto",
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-22",
    readMinutes: 9,
    image: "/photos/boardroom.jpg",
    imageAlt: "Sala de directorio",
    caption: "Más dinero, menos deals. Eso no es recuperación. Es concentración.",
    city: "São Paulo",
    pace: "fondo",
    tags: ["fintech", "industria", "fondo"],
    pullQuote: "Si 2026 cierra con más dinero y otra vez menos deals, la región no está financiando más innovación. Está apostando más fuerte a menos fichas.",
    body: [
      { type: "p", text: "El venture capital latinoamericano cerró 2025 con 4.126 millones de dólares invertidos en 681 rondas, según el Latin America Venture Capital Report 2026 elaborado por Cuántico VP en colaboración con Startuplinks. Es un crecimiento de 13,8% frente a los 3.627 millones de 2024, y el tercer mejor año histórico, sólo detrás de 2021 y 2018." },
      { type: "stat", value: "US$ 4.126 M", label: "VC Latam 2025" },
      { type: "stat", value: "−56,8%", label: "Series C en adelante" },
      { type: "stat", value: "681", label: "Rondas, mínimo desde 2017" },
      { type: "quote", text: "Si 2026 cierra con más dinero y otra vez menos deals, la región no está financiando más innovación. Está apostando más fuerte a menos fichas.", cite: "Daniel Pinto" },
      { type: "p", text: "La lectura de titular fue \"el VC latinoamericano se recuperó\". La lectura correcta es otra." },
      { type: "p", text: "El número de operaciones cayó 1,9%, hasta su nivel más bajo desde 2017. El ticket promedio subió de 5,2 a 6,1 millones de dólares, un salto de casi 16%. Es decir: entró más dinero y se financiaron menos empresas, con cheques más grandes." },
      { type: "p", text: "Eso no es recuperación. Es concentración." },
      { type: "h2", text: "Las tres cifras que ordenan el panorama" },
      { type: "p", text: "El derrumbe del crecimiento. Las rondas Serie C en adelante cayeron 56,8%, de 1.798 millones a apenas 777 millones. También es su punto más bajo desde 2017. Esta es, de lejos, la cifra más grave del informe, y explica por qué la creación de unicornios sigue siendo marginal: sólo dos startups latinoamericanas superaron esa valuación en el año." },
      { type: "p", text: "El apagón del pre-seed. El pre-seed se contrajo 40% en capital y 39,4% en número de operaciones. Al mismo tiempo, las etapas tempranas en conjunto capturaron el 52% del capital regional —unos 2.200 millones—, la primera vez desde la corrección post-2021 que superan a las de crecimiento en distribución porcentual." },
      { type: "p", text: "Puestos juntos, esos dos datos describen una figura precisa: el capital se agolpó en seed y Serie A, se secó en pre-seed y desapareció en Serie C. No hay escalera. Hay un descanso amplio en el medio, sin peldaños arriba ni abajo." },
      { type: "p", text: "La concentración geográfica y sectorial. Brasil y México acumularon el 78,5% de toda la inversión —2.032 y 980 millones respectivamente. Fintech representó el 29% de las operaciones y el 61% del capital, impulsada por megarrondas en compañías mexicanas como Plata y Klar. Colombia registró más operaciones que Chile —62 contra 53— pero con tickets menores: 3,6 millones promedio contra 4,7. Argentina mantuvo tickets competitivos, 5,1 millones en promedio, con menor volumen de rondas por restricciones macroeconómicas." },
      { type: "h2", text: "Qué significa esto si usted está levantando capital" },
      { type: "p", text: "Cuatro consecuencias operativas, sin adorno." },
      { type: "p", text: "Los ciclos se estiraron a aproximadamente 20 meses promedio. Cualquier plan de caja construido sobre un fundraising de seis meses está mal construido." },
      { type: "p", text: "La deuda dejó de ser un instrumento exótico. Las startups respaldadas por capital de riesgo obtuvieron más de 2.000 millones de dólares en financiamiento a través de líneas de crédito. Esa cifra —la mitad del venture equity total de la región— es la señal más clara de que los founders están evitando dilución en un mercado donde levantar equity significa aceptar valuación castigada." },
      { type: "p", text: "Si su empresa está en pre-seed, el mercado se contrajo 40% debajo de usted. No es percepción." },
      { type: "p", text: "Y si su plan contempla una Serie C en 2027 y 2028, la pregunta que hay que responder ahora, no entonces, es de dónde va a salir. El mercado que financiaba esa etapa en la región se redujo a menos de la mitad, y buena parte de esos cheques históricamente venían de fondos internacionales que ajustaron exposición a mercados emergentes." },
      { type: "h2", text: "La contracara: 2026 arrancó distinto" },
      { type: "p", text: "Las startups latinoamericanas levantaron 1.300 millones de dólares en el primer trimestre de 2026, contra 978 millones en el mismo período de 2025, marcando el primer trimestre más fuerte desde 2022, según LAVCA." },
      { type: "p", text: "El dato regionalmente relevante de ese trimestre: México cerró la brecha con Brasil. Las compañías tecnológicas con sede en México levantaron 21% más capital que el año anterior y quedaron apenas 14% por detrás de las brasileñas en financiamiento total. Crunchbase, con metodología distinta, directamente ubicó a México primero." },
      { type: "p", text: "Y el Latam VC Confidence Index, construido sobre una muestra de más de 100 inversionistas entre fondos, ángeles, corporativos y family offices, reporta 58% con confianza medio-alta para los próximos 6 a 18 meses, y 47,2% planeando aumentar su actividad inversora en 2026." },
      { type: "h2", text: "Lo que hay que vigilar" },
      { type: "p", text: "Un trimestre no es una tendencia, y el primer trimestre de 2022 también se veía bien. La métrica que va a distinguir un rebote real de un rebote de titular no es el capital desplegado: es el número de operaciones. Si 2026 cierra con más dinero y otra vez menos deals, la región no está financiando más innovación. Está apostando más fuerte a menos fichas, que es lo que hace un mercado que no confía en su propio pipeline." },
    ],
  },
  {
    slug: "data-centers-cinco-por-ciento",
    title: "América Latina tiene el 5% de los data centers del mundo y el 100% de la discusión sobre el agua",
    dek: "Los cuatro mercados principales crecieron 41% en un año. La variable que decide dónde se construye ya no es el tamaño de la economía: es si hay potencia firme en un nodo específico.",
    kicker: "Ideas",
    section: "climate",
    authorId: "daniel-pinto",
    signedName: "Daniel Pinto",
    publishedAt: "2026-08-14",
    updatedAt: "2026-08-22",
    readMinutes: 10,
    image: "/photos/medellin-office.jpg",
    imageAlt: "Infraestructura tecnológica",
    caption: "La variable que decide ya no es el tamaño de la economía: es si hay potencia firme en un nodo.",
    city: "Querétaro",
    pace: "fondo",
    tags: ["energia", "infraestructura", "fondo"],
    pullQuote: "Cuando un operador tiene que construir su propia generación porque no confía en la red, eso es una falla del sistema eléctrico expresada como línea del presupuesto.",
    body: [
      { type: "p", text: "Los cuatro mayores mercados de data centers de América Latina —São Paulo, Querétaro, Santiago y Bogotá— alcanzaron un inventario mayorista combinado de 1.045 MW en el primer trimestre de 2026, un crecimiento agregado de 41,3% interanual, según el informe Global Data Center Trends 2026 de CBRE. En doce meses agregaron unos 306 MW, subiendo desde unos 739 MW." },
      { type: "stat", value: "5%", label: "Data centers del mundo" },
      { type: "stat", value: "1.045 MW", label: "Inventario mayorista 4 mercados" },
      { type: "stat", value: "+450%", label: "Querétaro, interanual" },
      { type: "quote", text: "Cuando un operador tiene que construir su propia generación porque no confía en la red, eso es una falla del sistema eléctrico expresada como línea del presupuesto.", cite: "Daniel Pinto" },
      { type: "p", text: "El crecimiento no está repartido. Querétaro fue el mercado de más rápida expansión de la región, con 450,2% interanual. São Paulo sigue siendo el mayor por capacidad instalada. México pasó de 115 MW en 2024 a cerca de 280 MW, un alza de 140%." },
      { type: "p", text: "Ahora la cifra que pone todo en perspectiva: alrededor del 5% de los data centers del mundo están en América Latina." },
      { type: "p", text: "Es una región con más del 8% de la población mundial y con las tasas de adopción de servicios digitales más altas del planeta en varias categorías. La brecha entre consumo de cómputo y producción de cómputo es, probablemente, el desbalance de infraestructura más grande que tiene la región y el que menos titulares genera." },
      { type: "h2", text: "El capital que está entrando" },
      { type: "p", text: "AWS avanza con una inversión de aproximadamente 4.000 millones de dólares en Chile y se comprometió con 5.000 millones para una nueva región de nube en México. Google construye un centro de 850 millones en Uruguay. En Colombia se prepara una zona local en Bogotá conectada a infraestructura en Estados Unidos, orientada a reducir latencia." },
      { type: "p", text: "La inversión anual regional se proyecta que casi se duplique: de unos 5.000 millones de dólares en 2023 a cerca de 10.000 millones en 2029." },
      { type: "h2", text: "El criterio de selección cambió" },
      { type: "p", text: "Esto es lo más interesante del ciclo actual y lo que menos se entiende en las conversaciones de promoción de inversión." },
      { type: "p", text: "La decisión de dónde instalar ya no depende del tamaño de la economía. Depende de tres cosas: energía confiable, agua y conectividad. Un país puede tener un PIB grande y quedar fuera de la lista si no puede entregar potencia firme en un nodo específico de la red, en una fecha específica." },
      { type: "p", text: "CBRE identifica los obstáculos con precisión: disponibilidad de energía, confiabilidad de la red y escasez de mano de obra calificada. Y añade un punto que rara vez aparece en los anuncios: los desarrolladores están recurriendo a proyectos de autogeneración, lo que agrega costo y riesgo al proyecto. Cuando un operador tiene que construir su propia generación porque no confía en la red, eso es una falla del sistema eléctrico expresada como línea del presupuesto." },
      { type: "p", text: "La proyección de CBRE es que el crecimiento del mercado va a tensar la disponibilidad de talento calificado, intensificando la competencia y potencialmente extendiendo los plazos de construcción." },
      { type: "h2", text: "La contradicción chilena" },
      { type: "p", text: "Chile es el caso más instructivo de la región porque tiene los dos lados del problema simultáneamente." },
      { type: "p", text: "Tiene uno de los mejores recursos solares del mundo y está vertiendo más de 6 TWh al año por falta de transmisión. Es decir: tiene energía limpia sobrante y no puede llevarla a donde se necesita. El gobierno lanzó un Plan Nacional de Data Centers con inversiones proyectadas por 4.000 millones de dólares y criterios de sostenibilidad obligatorios, y publicó lineamientos para descentralizar infraestructura hacia el desierto de Atacama y Magallanes." },
      { type: "p", text: "Esa decisión es técnicamente elegante: poner el cómputo donde está la generación, en lugar de mover la generación hasta donde está el cómputo. Resuelve el vertimiento y el consumo eléctrico del data center con el mismo movimiento." },
      { type: "p", text: "Y al mismo tiempo, en Cerrillos, hubo gente parada afuera de Google con carteles. El conflicto por el uso de agua en zonas urbanas es real y no lo resuelve un plan nacional." },
      { type: "h2", text: "El vacío regulatorio como ventaja competitiva frágil" },
      { type: "p", text: "Acá está la parte incómoda. Especialistas del sector señalan que la legislación latinoamericana sobre recursos hídricos y energéticos aplicada a infraestructura digital es débil y carece de estándares, a diferencia de la Unión Europea, donde las regulaciones son considerablemente más estrictas." },
      { type: "p", text: "Eso es, en términos estrictamente de atracción de inversión, una ventaja. Los proyectos se aprueban más rápido y con menos condiciones. Parte de la razón por la cual Querétaro creció 450% es exactamente esa." },
      { type: "p", text: "También es una ventaja que se agota sola. Grupos de activistas en Querétaro han tenido dificultades para acceder a información sobre cómo se están desarrollando los proyectos, y la falta de información pública es precisamente lo que impide una discusión con evidencia. Cuando la discusión llega igual —y llega— llega sin datos y con desconfianza acumulada, que es la peor combinación posible para cualquiera que necesite una licencia social para operar veinte años." },
      { type: "h2", text: "Lo que debería estar en cada anuncio y no está" },
      { type: "p", text: "Tres números, y ninguno es la inversión en dólares." },
      { type: "p", text: "Cuántos megavatios de potencia firme requiere el proyecto y de qué nodo salen. Cuántos litros de agua consume al año, con qué fuente y bajo qué esquema de reposición. Y cuántos empleos permanentes —no de construcción— genera por megavatio instalado." },
      { type: "p", text: "Ese último número es el que hace más ruido cuando se publica, porque un data center es una de las infraestructuras con menor intensidad de empleo permanente por dólar invertido que existe. Es una razón perfectamente válida para construirlos igual —la infraestructura digital habilita industrias enteras aguas abajo— pero no es el argumento que se está usando, y usar el argumento equivocado tiene costo cuando la comunidad hace la cuenta." },
      { type: "p", text: "México muestra el otro filo del problema: grupos de la industria advierten que hay proyectos que se están redirigiendo a Brasil y Chile porque la planificación energética no siguió el ritmo. La ventaja regulatoria no compensa la falta de electrones." },
    ],
  },
  {
    slug: "ia-purgatorio-del-piloto",
    title: "El purgatorio del piloto: por qué la adopción de IA no aparece en los estados financieros",
    dek: "América Latina adopta inteligencia artificial por encima del promedio global y captura el 1,1% de la inversión mundial. La brecha no es de tecnología ni de talento.",
    kicker: "Trabajo",
    section: "work",
    authorId: "daniel-pinto",
    signedName: "Daniel Pinto",
    publishedAt: "2026-08-13",
    updatedAt: "2026-08-22",
    readMinutes: 8,
    image: "/photos/analog-office.jpg",
    imageAlt: "Oficina y pantallas en una sala de trabajo",
    caption: "Adoptamos por encima de la media y financiamos por debajo de todo.",
    city: "Santiago",
    pace: "fondo",
    tags: ["ia", "software", "fondo"],
    pullQuote: "La probabilidad no condicionada de que una iniciativa de IA cualquiera genere retorno medible en doce meses está por debajo del 5%.",
    body: [
      { type: "p", text: "Hay dos números sobre inteligencia artificial en América Latina que conviene tener juntos." },
      { type: "stat", value: "47%", label: "Adopción regional" },
      { type: "stat", value: "1,1%", label: "De la inversión mundial en IA" },
      { type: "stat", value: "10%", label: "Escala más allá del piloto" },
      { type: "quote", text: "La probabilidad no condicionada de que una iniciativa de IA cualquiera genere retorno medible en doce meses está por debajo del 5%.", cite: "Daniel Pinto" },
      { type: "p", text: "El primero: la región adopta IA a un ritmo cercano al 47%, por encima del promedio global de 45%. El estudio CIO Playbook 2026 de Lenovo va más lejos y sitúa al 84% de las empresas latinoamericanas en fase piloto o adopción activa, contra 77% a nivel global. El 97% de las organizaciones de la región planea aumentar su inversión." },
      { type: "p", text: "El segundo: la región captura alrededor del 1,1% de la inversión global en inteligencia artificial." },
      { type: "p", text: "Adoptamos por encima de la media y financiamos por debajo de todo. Eso no es una contradicción; es la descripción exacta de un mercado que consume IA como servicio y no la produce." },
      { type: "h2", text: "El purgatorio" },
      { type: "p", text: "El número que realmente importa no es cuántas empresas adoptaron IA. Es cuántas iniciativas llegaron a producción." },
      { type: "p", text: "Ahí las cifras se vuelven duras. Un estudio de MIT Sloan Management Review encontró que sólo el 10% de las empresas logra escalar sus iniciativas de IA más allá del piloto. El informe State of AI 2026 de Deloitte identifica el mismo cuello de botella con otra métrica: globalmente, sólo una de cada cuatro organizaciones consigue llevar más del 40% de sus iniciativas de IA a producción." },
      { type: "p", text: "En la región, datos de Intel e IDC indican que el 58% de las organizaciones latinoamericanas están moviendo iniciativas desde la idea hacia etapas de desarrollo y producción. Es un avance real respecto de años anteriores, pero \"moviendo hacia\" no es lo mismo que \"en producción, con dueño y con presupuesto\"." },
      { type: "p", text: "IDC proyecta que el mercado de IA en América Latina crecerá a una tasa compuesta cercana al 30% anual hasta 2027, llegando a unos 6.000 millones de dólares. Es un mercado que crece rápido sobre una base chica." },
      { type: "h2", text: "Por qué se quedan atascadas" },
      { type: "p", text: "La explicación cómoda es que falta talento. Es parcialmente cierta y completamente insuficiente." },
      { type: "p", text: "La explicación real, en la mayoría de los casos que uno ve de cerca, es más simple y más incómoda: el proyecto de IA no tiene dueño en el estado de resultados." },
      { type: "p", text: "Un piloto de IA típicamente nace en un área de tecnología o innovación, se financia con un presupuesto de exploración, y demuestra que la tecnología funciona. Eso es exactamente lo que estaba diseñado para hacer. El problema es que \"la tecnología funciona\" no es un criterio de decisión para nadie que tenga responsabilidad sobre un P&L. La pregunta de quien firma el presupuesto operativo es otra: qué línea se mueve, cuánto, y quién responde si no se mueve." },
      { type: "p", text: "Cuando no hay respuesta a esas tres preguntas, el piloto no se cancela —cancelarlo sería reconocer algo— sino que entra en el estado que la industria llama, con precisión notable, proof of concept eterno." },
      { type: "h2", text: "El dato sobre las personas que nadie está usando" },
      { type: "p", text: "Hay un hallazgo de un estudio de WeWork y PageGroup que merece más atención de la que recibió: el 97% de los colaboradores en la región quiere capacitarse en IA, y la mayoría de las empresas todavía no ofrece programas formales." },
      { type: "p", text: "Un 97% de demanda interna insatisfecha es una anomalía. En cualquier otra categoría de capacitación corporativa, la queja habitual es la contraria: la empresa ofrece formación y nadie la toma." },
      { type: "p", text: "Las organizaciones que están resolviendo esto no están esperando a las universidades. Están armando academias internas para nivelar conocimiento en equipos no técnicos, que es donde está el cuello de botella real. La adopción de IA en una empresa no la decide el equipo de datos; la decide si la persona de finanzas, la de legal y la de operaciones saben qué pedirle a la herramienta." },
      { type: "h2", text: "El indicador de madurez que sugiero" },
      { type: "p", text: "Si tuviera que reducir todo esto a una sola métrica reportable a directorio, sería esta: porcentaje de iniciativas de IA en producción con dueño identificado en el estado de resultados y línea presupuestaria de operación, no de proyecto." },
      { type: "p", text: "No es elegante. Es la única que distingue una capacidad organizacional de una demostración técnica." },
      { type: "p", text: "Y sirve para calibrar expectativas. Colombia ofrece un contraste útil: sólo el 22% de las empresas invierte de manera sistemática, mientras un 29% experimenta sin dirección clara. Ese 29% es el grupo que en dos años va a concluir que \"la IA no funcionó\", cuando lo que no funcionó fue el diseño del programa." },
      { type: "h2", text: "Una advertencia sobre las cifras de ROI" },
      { type: "p", text: "El mercado está lleno de estadísticas de retorno que conviene leer con distancia. Circulan cifras de 3,7x por dólar invertido, de 340% de retorno a 18 meses, de 5,8x a 14 meses. Vienen de encuestas de autorreporte, con sesgo de supervivencia evidente: las empresas cuyos proyectos fracasaron no responden encuestas sobre el ROI de sus proyectos." },
      { type: "p", text: "Un dato más honesto, de Forrester: el 44% de los proyectos de IA que llegan a producción logra ROI positivo en doce meses." },
      { type: "p", text: "Léase con cuidado la condición: de los que llegan a producción. Si sólo el 10% escala más allá del piloto, y de ese 10% el 44% da retorno positivo en un año, la probabilidad no condicionada de que una iniciativa de IA cualquiera genere retorno medible en doce meses está por debajo del 5%." },
      { type: "p", text: "Ese es el número real. Y no es un argumento para no hacer IA. Es un argumento para hacer menos pilotos y llevar más cosas a producción." },
      { type: "p", text: "Daniel Pinto escribe sobre industria, energía y capital para We Are Vander. Cierre de datos: 22 de agosto de 2026." },
    ],
  },
];
