/** Interviews, 90-second reads, obituaries, data leads — not essays. */

export const FORMAT_ARTICLES = [
  {
    slug: "entrevista-camila-rojas",
    title: "Camila Rojas: “Si la sala es una pantalla, la gente se comporta como pantalla”",
    dek: "La cofundadora de Northroom, en una hora en Lastarria. Wifi que se estrecha, lista de espera a 24 meses, y por qué el calendario es el producto.",
    kicker: "Entrevista",
    section: "work",
    authorId: "jonah-peck",
    format: "interview",
    pace: "fondo",
    tags: ["trabajo", "diseno", "fondo"],
    publishedAt: "2026-08-21",
    updatedAt: "2026-08-22",
    readMinutes: 9,
    image: "/photos/analog-office.jpg",
    imageAlt: "Camila Rojas en la sala larga de Northroom",
    caption: "Lastarria, 16:10. Rojas no alarga la entrevista. El producto tampoco.",
    city: "Santiago",
    pullQuote: "No desinstalamos internet. Dejamos de dejarlo sentarse a la cabecera.",
    body: [
      { type: "p", text: "Camila Rojas, 41, cofundó Northroom después de una década midiendo “focus time” en un unicornio de software. Hoy vende un protocolo: salas donde el wifi se estrecha después de las 11, mesas de cuatro metros y una lista de espera de dos años. Recibió a Team Vander un viernes, a las 16:00, cuando la oficina ya está cerrando. Esa hora, dice, es parte de la tesis." },
      { type: "stat", value: "24 meses", label: "Lista de espera" },
      { type: "stat", value: "11 personas", label: "Plantilla en Santiago" },
      { type: "stat", value: "16:00", label: "Cierre los viernes" },
      { type: "q", text: "¿Northroom es una inmobiliaria con mejor lino?" },
      { type: "a", text: "Si lo fuera, no tendríamos lista de espera. El producto es un protocolo. El cliente compra que la interrupción digital sea levemente incómoda. El mueble ayuda. El horario manda." },
      { type: "q", text: "Tres fondos en Vitacura pidieron wifi lento este mes. ¿Copia o coincidencia?" },
      { type: "a", text: "Copia. Bienvenida. Si el protocolo se puede imitar y duele, es que era un producto. Lo que no se copia es el no: no alargamos la junta, no hay monitor mirando la puerta, no hay un Slack de la sala." },
      { type: "q", text: "Te fuiste un viernes a las 16:00. ¿El P&L se inmutó?" },
      { type: "a", text: "Si se inmuta, no construimos una empresa. Construimos un santuario. Northroom tiene que funcionar cuando yo no estoy. Eso es más difícil de vender en un deck. Es lo único que nos interesa." },
      { type: "quote", text: "No desinstalamos internet. Dejamos de dejarlo sentarse a la cabecera.", cite: "Camila Rojas, Northroom" },
      { type: "q", text: "¿Esto es nostalgia?" },
      { type: "a", text: "Es un recorte de software de colaboración. Tres clientes bajaron asientos en más de un tercio. El software no empeoró. Las reuniones se acortaron. Nostalgia no factura eso." },
    ],
  },
  {
    slug: "entrevista-elena-voss",
    title: "Elena Voss, Vesper Grid: “La paciencia tiene geografía”",
    dek: "La CEO que trata el Atacama como paisaje, no como wallpaper. Offtakes a 20 años y un pueblo con nombre.",
    kicker: "Entrevista",
    section: "climate",
    authorId: "rafael-quinn",
    format: "interview",
    pace: "fondo",
    tags: ["energia", "clima-tech", "fondo"],
    publishedAt: "2026-08-20",
    updatedAt: "2026-08-21",
    readMinutes: 8,
    image: "/photos/climate-atacama.jpg",
    imageAlt: "Elena Voss en el campo solar de Vesper Grid",
    caption: "Calama, 13:10. Voss camina el pasillo. El ticker, no.",
    city: "Calama",
    pullQuote: "El software escaló con atención. El clima va a escalar con paciencia.",
    body: [
      { type: "p", text: "Elena Voss dirige Vesper Grid desde un racimo de contenedores cerca de Calama. No es el mayor operador solar de Chile. Puede ser el más deliberado. Team Vander la encontró al filo del campo, donde el desierto aceptó una línea de vidrio oscuro." },
      { type: "stat", value: "20 años", label: "Duración del offtake tipo" },
      { type: "stat", value: "Calama", label: "Pueblo que nombra el contrato" },
      { type: "q", text: "¿Por qué un offtake tiene que nombrar un pueblo?" },
      { type: "a", text: "Porque si no nombra un pueblo, nombra un ticker. El ticker no vive aquí. El técnico del chaleco sí. El capital que nos sirve es el que puede quedarse el tiempo suficiente para ser de acá." },
      { type: "q", text: "El consenso climático cabe en un slide de ESG." },
      { type: "a", text: "Ese slide entrenó a una generación a tratar la atmósfera como planilla. Se acaba, no porque la matemática mejoró, sino porque el público aprendió a leer la nota al pie. Nosotros vendemos kilowatts-hora y un lenguaje para cómo un sitio encuentra un paisaje." },
      { type: "quote", text: "El software escaló con atención. El clima va a escalar con paciencia — y la paciencia tiene geografía.", cite: "Elena Voss, Vesper Grid" },
      { type: "q", text: "¿Vesper es una historia de tecnología?" },
      { type: "a", text: "Desde el filo, parece un cultivo. Eso es el cumplido. La infraestructura es cultura aunque no lo admitas. Nosotros lo admitimos." },
    ],
  },
  {
    slug: "flash-apodaca-1200",
    title: "Sierra Line suma 1.200 personas al segundo turno de Apodaca",
    dek: "Sin comunicado. El comedor abre a las 22:00. El camión sale de Guadalupe a las 21:15.",
    kicker: "90 segundos",
    section: "work",
    authorId: "valentina-cruz",
    format: "flash",
    pace: "rapida",
    tags: ["nearshoring", "industria", "rapida"],
    publishedAt: "2026-08-22",
    readMinutes: 2,
    image: "/photos/monterrey-factory.jpg",
    imageAlt: "Planta de noche en Apodaca",
    caption: "Apodaca, 22:40. El indicador no es el FDI.",
    city: "Monterrey",
    pullQuote: "El comunicado ya salió hace dos años. La nómina, esta semana.",
    body: [
      { type: "p", text: "Sierra Line no mandó press release. Recursos Humanos sí: 1.200 contratos de segundo turno, comedor a las 22:00, tres rutas nuevas desde Guadalupe. El nearshoring que importa en agosto no está en el anuncio de 2024. Está en el casco que entra cuando Reforma todavía está oscura." },
      { type: "stat", value: "1.200", label: "Contratos de segundo turno" },
      { type: "stat", value: "22:00", label: "Apertura del comedor" },
      { type: "p", text: "Tres plantas del corredor Apodaca–Santa Catarina copiaron el horario en julio. Quien cuente esas rutas ve el nearshoring seis meses antes que el comunicado." },
    ],
  },
  {
    slug: "flash-quilate-margen",
    title: "Casa Quilate publica un margen neto de 4,1%",
    dek: "Itaim, sucursal del tamaño de una panadería. El número que el deck de 2021 no quería ver.",
    kicker: "90 segundos",
    section: "ideas",
    authorId: "diego-azevedo",
    format: "flash",
    pace: "rapida",
    tags: ["fintech", "pagos", "rapida"],
    publishedAt: "2026-08-21",
    readMinutes: 2,
    image: "/photos/saopaulo-fintech.jpg",
    imageAlt: "Sucursal de Casa Quilate",
    caption: "Itaim. El margen cabe en un lookbook feo.",
    city: "São Paulo",
    pullQuote: "La innovación era abrir la cuenta. El negocio es no perderla.",
    body: [
      { type: "p", text: "Casa Quilate soltó el número que el resto esconde: 4,1% neto, sucursal de 42 metros, cobro en México sin pasar por Palo Alto. No es una wallet. Es un banco que cabe en una panadería." },
      { type: "stat", value: "4,1%", label: "Margen neto 2T 2026" },
      { type: "stat", value: "42 m²", label: "Sucursal Itaim" },
      { type: "p", text: "El inversor que todavía pide MAU va a pedir, la próxima ronda, el costo de no perder a la señora de los martes." },
    ],
  },
  {
    slug: "flash-brickell-cierra",
    title: "Tres oficinas de Latam cierran Brickell este mes",
    dek: "Vuelven a Itaim, Roma Norte y Vitacura. Miami queda como huso, no como mercado.",
    kicker: "90 segundos",
    section: "ideas",
    authorId: "diego-azevedo",
    format: "flash",
    pace: "rapida",
    tags: ["fintech", "industria", "rapida"],
    publishedAt: "2026-08-20",
    readMinutes: 2,
    image: "/photos/saopaulo-paulista.jpg",
    imageAlt: "Avenida Paulista",
    caption: "Paulista, 9:12. El mercado, otra vez.",
    city: "São Paulo",
    pullQuote: "El cliente está en Guadalajara y Campinas. El regulador, también.",
    body: [
      { type: "p", text: "Tres LLC que abrieron en Brickell entre 2021 y 2023 entregaron las llaves esta semana. Los escritorios nuevos están en Itaim, Roma Norte y Vitacura. El family office del piso 40 se queda. La nómina, no." },
      { type: "stat", value: "3", label: "Oficinas que cierran en agosto" },
      { type: "p", text: "No es un moralismo anti-Florida. Es un P&L. El próximo hub no se inaugura. Se opera donde ya está quien cobra." },
    ],
  },
  {
    slug: "galeria-callao",
    title: "Un día en Callao, en tres fotos",
    dek: "Tercer Turno nombra el barco. El handoff cabe en un A4. El Pacífico, no en un Slack.",
    kicker: "Visual",
    section: "work",
    authorId: "rafael-quinn",
    format: "visual",
    pace: "rapida",
    tags: ["logistica", "nearshoring", "rapida"],
    publishedAt: "2026-08-19",
    readMinutes: 3,
    image: "/photos/lima-port.jpg",
    imageAlt: "Puerto del Callao al atardecer",
    caption: "07:40. La primera nave ya tiene nombre en el A4.",
    city: "Lima",
    pullQuote: "Si no puedes nombrar el barco, no tienes una tesis de supply.",
    gallery: [
      { src: "/photos/lima-port.jpg", alt: "Muelle de Callao", caption: "07:40 — Tres naves en la grilla. Un retraso. Cero teatro." },
      { src: "/photos/monterrey-factory.jpg", alt: "Patio y containers", caption: "11:15 — El patio es el software. El sensor no reemplaza al muelle." },
      { src: "/photos/boardroom.jpg", alt: "Sala del handoff", caption: "16:00 — El handoff se escribe en prosa y se pega junto al turno." },
    ],
    body: [
      { type: "p", text: "Un supervisor de Tercer Turno muestra la grilla del día como quien muestra un menú: tres naves, un retraso, el nombre del buque. Callao dejó de ser escala. Es escritorio. Estas tres fotos son el argumento. El ticker, no." },
    ],
  },
  {
    slug: "obituario-unicornio-miami",
    title: "Obituario: el unicornio de Brickell (2021–2026)",
    dek: "Murió de un P&L. Le sobreviven una LLC en Delaware y un group chat que nadie silenció.",
    kicker: "Obituarios",
    section: "ideas",
    authorId: "diego-azevedo",
    format: "obituario",
    pace: "rapida",
    tags: ["fintech", "rapida"],
    publishedAt: "2026-08-22",
    readMinutes: 3,
    image: "/photos/rooftop.jpg",
    imageAlt: "Terraza de oficinas vacía",
    caption: "Brickell. El velorio es un Slack archive.",
    city: "São Paulo",
    pullQuote: "En paz, si el family office lo permite.",
    body: [
      { type: "p", text: "El unicornio de Brickell falleció esta semana, rodeado de palmeras y de un CFO que ya tenía pasaje a Itaim. Nació en 2021, hijo de una ronda Seed y un deck que decía “hub”. Se le recuerda por el English del piso 40, la visa que nunca llegó y la costumbre de llamar mercado a un huso horario." },
      { type: "p", text: "Le sobreviven tres oficinas en Latam que operan donde está la nómina, un group chat llamado “Miami HQ” con 400 no leídos, y la tesis —ahora póstuma— de que el aeropuerto era un producto. El velorio se hará en Zoom, a las 9:00 EST, para no coincidir con Campinas." },
      { type: "quote", text: "En paz, si el family office lo permite.", cite: "Team Vander" },
    ],
  },
  {
    slug: "obituario-slide-esg",
    title: "Obituario: el slide de ESG (alcance 3, Q.E.P.D.)",
    dek: "Murió de una nota al pie. El público aprendió a leerla.",
    kicker: "Obituarios",
    section: "climate",
    authorId: "rafael-quinn",
    format: "obituario",
    pace: "rapida",
    tags: ["energia", "clima-tech", "rapida"],
    publishedAt: "2026-08-21",
    readMinutes: 3,
    image: "/photos/climate-atacama.jpg",
    imageAlt: "Campo solar",
    caption: "El desierto no firmó el slide.",
    city: "Santiago",
    pullQuote: "Lo velamos en Calama, donde el offtake sí tiene pueblo.",
    body: [
      { type: "p", text: "El slide de ESG murió de muerte natural: alguien preguntó por el pueblo. Nació en una consultora, se reprodujo en 400 directorios y dejó de fotos de paneles bajadas de iStock. En sus últimos días pedía un copiloto que redactara el alcance 3." },
      { type: "p", text: "Le sobrevive un offtake a veinte años, un técnico en chaleco y Elena Voss, que no asistirá al velorio porque está caminando el campo. En lieu of flowers, nombrar un pueblo." },
    ],
  },
  {
    slug: "obituario-drop-jueves",
    title: "Obituario: el drop del jueves a las 11",
    dek: "Murió de una persiana que se abre todos los días. Le sobrevive un calendario pegado con cinta.",
    kicker: "Obituarios",
    section: "culture",
    authorId: "lina-cho",
    format: "obituario",
    pace: "rapida",
    tags: ["moda", "retail", "rapida"],
    publishedAt: "2026-08-18",
    readMinutes: 3,
    image: "/photos/fashion-atelier.jpg",
    imageAlt: "Atelier y persiana",
    caption: "Providencia. La hora, no la fila.",
    city: "Santiago",
    pullQuote: "Si tu marca solo existe el jueves a las 11, era un evento. Descanse.",
    body: [
      { type: "p", text: "El drop del jueves falleció de una overdose de countdown. Se le recuerda por la fila, el screenshot y la frase “comunidad”. En sus últimos minutos intentó un NFT del ticket de entrada." },
      { type: "p", text: "Le sobreviven Casa Hilo, que abre cuando dice el letrero, y un barrio que no hace fila: vuelve. El féretro es un carrito abandonado. En paz, y sin restock." },
    ],
  },
  {
    slug: "obituario-ochenta-horas",
    title: "Obituario: las 80 horas (y el mártir que las vestía)",
    dek: "Murió un viernes a las 16:00. Nadie en la empresa se dio cuenta hasta el lunes.",
    kicker: "Obituarios",
    section: "work",
    authorId: "jonah-peck",
    format: "obituario",
    pace: "rapida",
    tags: ["trabajo", "rapida"],
    publishedAt: "2026-08-16",
    readMinutes: 3,
    image: "/photos/boardroom.jpg",
    imageAlt: "Sala de directorio vacía",
    caption: "El velorio cabe en dieciocho minutos.",
    city: "Santiago",
    pullQuote: "Si tu compañía solo funciona cuando desapareces, no construiste una empresa. Construiste un santuario.",
    body: [
      { type: "p", text: "Las 80 horas fallecieron de un P&L que no las necesitaba. Se les recuerda por el Slack a las 3:17, el board que aplaudía el insomnio y un perfil en revista que confundía liderazgo con martirio." },
      { type: "p", text: "Le sobrevive Camila Rojas, que cierra a las 16:00, y once personas en Lastarria que no preguntaron dónde estaba. El epitafio cabe en un protocolo. Flores, no. Horario, sí." },
    ],
  },
  {
    slug: "indice-agosto-2026",
    title: "El Índice de agosto: sueldos, segundo turno y offtakes",
    dek: "Tres tablas que se pueden citar. Lo que Vander midió este mes en seis ciudades — no lo que opinó.",
    kicker: "El Índice",
    section: "ideas",
    authorId: "mira-solano",
    format: "indice",
    pace: "fondo",
    tags: ["industria", "fondo"],
    publishedAt: "2026-08-22",
    updatedAt: "2026-08-22",
    readMinutes: 6,
    image: "/photos/boardroom.jpg",
    imageAlt: "Cifras sobre una mesa",
    caption: "Elaboración propia. Visitas, filings, fuentes nombradas.",
    city: "Ciudad de México",
    pullQuote: "Sin número, Vander opina. Con número, se cita.",
    body: [
      { type: "p", text: "Un medio de negocios que no publica tablas está pidiendo que le crean el adjetivo. El Índice es el antídoto: sueldos de ingeniería por ciudad, plantas que sumaron segundo turno, offtakes que nombran pueblo. Cifras de elaboración propia, agosto 2026. Metodología al pie." },
      { type: "stat", value: "6", label: "Ciudades medidas" },
      { type: "stat", value: "1.200", label: "Contratos de segundo turno en Apodaca" },
      { type: "stat", value: "4,1%", label: "Margen neto Casa Quilate" },
      { type: "p", text: "Las tablas vivas —y el gráfico de compensación— están en El Índice. Esta nota es la entrada. El archivo, la prueba." },
    ],
  },
];
