export const FRANCHISE_ARTICLES = [
  {
    slug: "el-founder-no-es-un-santo",
    title: "El founder no es un santo. Dejen de tratarlo como uno.",
    dek: "La mitología del fundador inalcanzable es una estetización del control. El P&L no necesita un mártir.",
    kicker: "Contra la corriente",
    section: "ideas",
    authorId: "mira-solano",
    signedName: "Mira Solano",
    franchise: "contra",
    pace: "fondo",
    tags: ["trabajo", "industria", "fondo"],
    publishedAt: "2026-08-21",
    updatedAt: "2026-08-22",
    readMinutes: 8,
    image: "/photos/boardroom.jpg",
    imageAlt: "Sala de directorio vacía",
    caption: "Un directorio no es un altar. CDMX, agosto.",
    city: "Ciudad de México",
    pullQuote: "Si tu compañía solo funciona cuando desapareces, no construiste una empresa. Construiste un santuario.",
    body: [
      { type: "p", text: "Cada temporada aparece un perfil que convierte al founder en reliquia: duerme cuatro horas, responde Slack a las 3:17, y el board aplaude el sacrificio como si fuera un KPI. Es una religión barata. El consenso —en LinkedIn, en las aceleradoras, en las cenas de Brickell— sigue siendo que el martirio es liderazgo. No lo es. Es una estetización del control." },
      { type: "quote", text: "Si tu compañía solo funciona cuando desapareces, no construiste una empresa. Construiste un santuario.", cite: "Mira Solano" },
      { type: "p", text: "En Latam el mito pega más porque el capital todavía pide un cuerpo que culpar. Preferimos un nombre a un sistema. El resultado es previsible: compañías que no sobreviven a las vacaciones de su fundador, juntas que no deciden sin su visto bueno, y un talento que aprende a esperar en vez de operar." },
      { type: "h2", text: "El carácter no es el burnout" },
      { type: "p", text: "Hay otra tesis, menos fotogénica: una empresa es un protocolo que se puede dejar en una mesa. Northroom lo entiende. Sierra Line también. El founder que se va el viernes y vuelve el lunes sin que el P&L se inmute no es menos ambicioso. Es más difícil de copiar. Contra el consenso: dejen de celebrar al que no duerme. Pregunten quién firma cuando él no está." },
    ],
  },
  {
    slug: "miami-no-es-el-mercado",
    title: "Miami no es el mercado. Es un huso horario con piscina.",
    dek: "Brickell vendió una geografía emocional. El P&L volvió a Paulista y a Roma Norte.",
    kicker: "Contra la corriente",
    section: "ideas",
    authorId: "diego-azevedo",
    signedName: "Diego Azevedo",
    franchise: "contra",
    pace: "fondo",
    tags: ["fintech", "industria", "fondo"],
    publishedAt: "2026-08-19",
    updatedAt: "2026-08-20",
    readMinutes: 7,
    image: "/photos/saopaulo-paulista.jpg",
    imageAlt: "Avenida Paulista",
    caption: "Paulista, 9:12. El mercado, otra vez.",
    city: "São Paulo",
    pullQuote: "Miami era un huso. No era un mercado.",
    body: [
      { type: "p", text: "El consenso de 2021 a 2024 fue simple: si levantas en español y portugués, abres una LLC en Delaware y una oficina con palmeras. Miami era el hub. El aeropuerto, el English, el family office del piso 40. Una cohorte entera compró la tesis. Esta semana, tres de esas oficinas cierran Brickell y vuelven a Itaim, a Roma Norte, a Vitacura." },
      { type: "quote", text: "Miami era un huso. No era un mercado.", cite: "Diego Azevedo" },
      { type: "p", text: "No es un moralismo anti-Florida. Es un P&L. El cliente está en Guadalajara y Campinas. El regulador, también. El talento de producto que importa no pidió visa: pidió una mesa a las 9:00 y un banco que cobre sin teatro. Contra la corriente: el próximo hub no se inaugura. Se opera donde ya está la nómina." },
    ],
  },
  {
    slug: "la-ia-no-reemplaza-la-junta",
    title: "La IA no reemplaza la junta. Reemplaza el acta mala.",
    dek: "El consenso vende copilots en el directorio. El criterio sigue siendo humano, lento y con nombre.",
    kicker: "Contra la corriente",
    section: "ideas",
    authorId: "valentina-cruz",
    signedName: "Valentina Cruz",
    franchise: "contra",
    pace: "fondo",
    tags: ["ia", "software", "fondo"],
    publishedAt: "2026-08-16",
    updatedAt: "2026-08-18",
    readMinutes: 7,
    image: "/photos/rooftop.jpg",
    imageAlt: "Reunión en una terraza de oficinas",
    caption: "Reforma, después de la junta. El modelo no se quedó.",
    city: "Ciudad de México",
    pullQuote: "Si el modelo escribe el acta, alguien todavía tiene que haber estado en la sala.",
    body: [
      { type: "p", text: "Hay un slide que recorre los directorios de la región: un copiloto que resume, vota y redacta. El consenso lo trata como inevitabilidad. Es un atajo. Una junta no es un corpus. Es una habitación con conflictos de interés, silencios y un presidente que decide cuándo se acaba la conversación." },
      { type: "quote", text: "Si el modelo escribe el acta, alguien todavía tiene que haber estado en la sala.", cite: "Valentina Cruz" },
      { type: "p", text: "La IA sirve cuando el acta era floja: timestamps, votos, un PDF que no miente. No sirve para el criterio. Contra la corriente: compren menos magia y más secretaría. El modelo no firma. Ustedes sí." },
    ],
  },
  {
    slug: "escalar-ya-no-es-virtud",
    title: "Escalar ya no es una virtud. Es una opción.",
    dek: "El hype convirtió el headcount en moral. Hay compañías que ganan precisamente porque no crecen.",
    kicker: "Contra la corriente",
    section: "work",
    authorId: "jonah-peck",
    signedName: "Jonah Peck",
    franchise: "contra",
    pace: "fondo",
    tags: ["trabajo", "industria", "fondo"],
    publishedAt: "2026-08-14",
    updatedAt: "2026-08-15",
    readMinutes: 8,
    image: "/photos/analog-office.jpg",
    imageAlt: "Oficina analógica",
    caption: "Santiago. Menos sillas, más protocolo.",
    city: "Santiago",
    pullQuote: "Escalar fue una religión. La parroquia es una calle.",
    body: [
      { type: "p", text: "Durante una década, no crecer era fracasar. El consenso todavía lo susurra: si no contratas, no crees. En 2026 las compañías más interesantes de Latam tienen listas de espera y menos gente que en 2022. No es decrecimiento romántico. Es un margen que no cabe en un tuit." },
      { type: "quote", text: "Escalar fue una religión. La parroquia es una calle.", cite: "Jonah Peck" },
      { type: "p", text: "Bruma Studio, Casa Hilo, Mesa Radio: el brief llega incompleto y el equipo cabe en una mesa. Contra la corriente: el headcount no es carácter. El carácter es un no a tiempo." },
    ],
  },
  {
    slug: "el-clima-no-es-un-esg-slide",
    title: "El clima no es un slide de ESG. Es un pueblo con nombre.",
    dek: "El consenso habla de transiciones. Las compañías serias hablan de offtakes, tierra y un dirigente que no sale en el deck.",
    kicker: "Contra la corriente",
    section: "climate",
    authorId: "rafael-quinn",
    signedName: "Rafael Quinn",
    franchise: "contra",
    pace: "fondo",
    tags: ["energia", "clima-tech", "fondo"],
    publishedAt: "2026-08-11",
    updatedAt: "2026-08-13",
    readMinutes: 9,
    image: "/photos/climate-atacama.jpg",
    imageAlt: "Campo solar en el Atacama",
    caption: "Atacama. El ticker no nombra este pueblo.",
    city: "Santiago",
    pullQuote: "Si tu tesis de litio no nombra un pueblo, no es una tesis. Es un ticker.",
    body: [
      { type: "p", text: "El consenso climático corporativo cabe en una diapositiva: net zero, alcance 3, una foto de un panel. Es una cortesía. El negocio está en un offtake a veinte años, un camino de tierra y un dirigente en San Pedro que no va a firmar porque el deck es bonito." },
      { type: "quote", text: "Si tu tesis de litio no nombra un pueblo, no es una tesis. Es un ticker.", cite: "Rafael Quinn" },
      { type: "p", text: "Vesper Grid y Páramo Grid lo entienden: paciencia, red, paisaje. Contra la corriente: dejen de medir el clima en slides. Mídanlo en kilómetros de camino que no aparecen en Google Maps." },
    ],
  },
  {
    slug: "signal-nomina-nocturna",
    title: "La nómina que entra de noche es el nuevo leading indicator",
    dek: "Apodaca, 22:40. El segundo turno adelanta al comunicado de nearshoring.",
    kicker: "Signals",
    section: "work",
    authorId: "valentina-cruz",
    franchise: "signals",
    pace: "rapida",
    tags: ["nearshoring", "industria", "rapida"],
    publishedAt: "2026-08-22",
    updatedAt: "2026-08-22",
    readMinutes: 2,
    image: "/photos/monterrey-factory.jpg",
    imageAlt: "Planta de noche en Monterrey",
    caption: "Segundo turno, Apodaca.",
    city: "Monterrey",
    pullQuote: "El anuncio ya fue. La nómina, no.",
    body: [
      { type: "p", text: "Tres plantas del corredor Apodaca–Santa Catarina agregaron un segundo turno en julio sin mandar un press release. El indicador no es el FDI. Es el comedor que abre a las 22:00 y el camión que sale de Guadalupe a las 21:15. Quien cuente esas rutas va a ver el nearshoring seis meses antes que el comunicado." },
      { type: "p", text: "Sierra Line no es un caso. Es un patrón: proveedores a menos de una hora, supervisor que habla inglés de piso, y un P&L que no cabe en un tuit. Todavía no es tendencia. Va a serlo cuando Recursos Humanos deje de preguntar por el ‘employer brand’ y empiece a preguntar por el tercer turno." },
    ],
  },
  {
    slug: "signal-sucursal-panaderia",
    title: "La sucursal del tamaño de una panadería",
    dek: "Itaim. El banco que cabe en un local chico deja de ser anécdota.",
    kicker: "Signals",
    section: "ideas",
    authorId: "diego-azevedo",
    franchise: "signals",
    pace: "rapida",
    tags: ["fintech", "pagos", "rapida"],
    publishedAt: "2026-08-22",
    updatedAt: "2026-08-22",
    readMinutes: 2,
    image: "/photos/saopaulo-fintech.jpg",
    imageAlt: "Sucursal financiera pequeña",
    caption: "Casa Quilate, Itaim.",
    city: "São Paulo",
    pullQuote: "La innovación era abrir la cuenta. El negocio es no perderla.",
    body: [
      { type: "p", text: "En Itaim hay una sucursal que no parece banco. Parece panadería: mostrador, dos sillas, un número que se saca. Casa Quilate publica márgenes feos a propósito. El patrón se copia en Providencia y en Condesa: menos app, más cobro difícil de screenshotear." },
      { type: "p", text: "Todavía no es tendencia porque el deck sigue pidiendo usuarios. Va a serlo cuando el inversor pida el costo de no perder a la señora que entra los martes. El hype abrió la cuenta. El negocio es la sucursal chica." },
    ],
  },
  {
    slug: "signal-wifi-lento",
    title: "Wifi lento como feature, no como falla",
    dek: "Vitacura y Lastarria. El protocolo analógico deja de ser moodboard.",
    kicker: "Signals",
    section: "work",
    authorId: "jonah-peck",
    franchise: "signals",
    pace: "rapida",
    tags: ["trabajo", "diseno", "rapida"],
    publishedAt: "2026-08-21",
    updatedAt: "2026-08-21",
    readMinutes: 2,
    image: "/photos/analog-office.jpg",
    imageAlt: "Oficina con mesa larga",
    caption: "Northroom, Santiago.",
    city: "Santiago",
    pullQuote: "Si la superficie por defecto es una pantalla, la sala se comporta como pantalla.",
    body: [
      { type: "p", text: "Tres fondos en Vitacura pidieron, en el mismo mes, salas con wifi que se estrecha después de las 11. No es nostalgia. Es un recorte de software de colaboración. Northroom tiene lista de espera a 24 meses. El protocolo se está volviendo un line item." },
      { type: "p", text: "Todavía se ríe en las agencias. Va a dejar de reírse cuando el ‘focus time’ salga del dashboard y entre al contrato de arriendo. Lo analógico, aquí, es una restricción. Las restricciones son cómo sobrevive el criterio." },
    ],
  },
  {
    slug: "signal-offtake-pueblo",
    title: "El offtake que nombra un pueblo",
    dek: "San Pedro, Chapinero, Calama. La tesis climática se pone geográfica.",
    kicker: "Signals",
    section: "climate",
    authorId: "rafael-quinn",
    franchise: "signals",
    pace: "rapida",
    tags: ["clima-tech", "energia", "rapida"],
    publishedAt: "2026-08-21",
    updatedAt: "2026-08-21",
    readMinutes: 2,
    image: "/photos/bogota.jpg",
    imageAlt: "Bogotá y cielo",
    caption: "Páramo Grid, Chapinero.",
    city: "Bogotá",
    pullQuote: "Sin puerto, con red.",
    body: [
      { type: "p", text: "Los decks de energía que cierran ronda en 2026 tienen una línea nueva: el nombre del pueblo. No el del fondo. Páramo Grid firma viento en Chapinero y nombra la red que no se cae. Vesper Grid trata el Atacama como paisaje, no como wallpaper." },
      { type: "p", text: "Todavía no es tendencia porque el ticker es más fácil. Va a serlo cuando el LP pregunte por el dirigente, no por el slide de ESG. El clima, como negocio, cabe en un offtake a veinte años. No en un alcance 3." },
    ],
  },
  {
    slug: "signal-brief-incompleto",
    title: "El brief que llega incompleto a propósito",
    dek: "Buenos Aires. La restricción de material se vuelve código de casa.",
    kicker: "Signals",
    section: "design",
    authorId: "camila-ferrer",
    franchise: "signals",
    pace: "rapida",
    tags: ["diseno", "hardware", "rapida"],
    publishedAt: "2026-08-20",
    updatedAt: "2026-08-20",
    readMinutes: 2,
    image: "/photos/workshop.jpg",
    imageAlt: "Taller de diseño",
    caption: "Bruma Studio, Buenos Aires.",
    city: "Buenos Aires",
    pullQuote: "Si el material no llega, el diseño tiene que haber llegado antes.",
    body: [
      { type: "p", text: "Bruma Studio corta con lo que hay. El brief llega incompleto y el objeto se diseña alrededor del faltante. No es romanticismo de escasez. Es un lead time que el studio de Berlín no puede copiar. En Palermo hay tres talleres más que copiaron el protocolo este invierno." },
      { type: "p", text: "Todavía parece anécdota argentina. Va a ser tendencia cuando el director creativo de São Paulo pida el mismo recorte: menos moodboard, más lista de lo que no va a llegar. La restricción es el producto." },
    ],
  },
  {
    slug: "signal-mural-afuera",
    title: "El mural se queda afuera del producto",
    dek: "Medellín. Altura Code publica por temporadas y saca el arte del pitch.",
    kicker: "Signals",
    section: "design",
    authorId: "andres-molina",
    franchise: "signals",
    pace: "rapida",
    tags: ["software", "diseno", "rapida"],
    publishedAt: "2026-08-19",
    updatedAt: "2026-08-19",
    readMinutes: 2,
    image: "/photos/medellin-office.jpg",
    imageAlt: "Oficina en Medellín",
    caption: "Altura Code. El mural, en la calle.",
    city: "Medellín",
    pullQuote: "Si necesitas un mural para explicar el producto, el producto no está listo.",
    body: [
      { type: "p", text: "Altura Code sacó el mural del lobby y lo dejó en la calle. El producto se publica por temporadas, como una colección. El deck ya no abre con la foto del grafiti. Abre con el changelog. Tres estudios del Poblado copiaron el gesto este mes." },
      { type: "p", text: "Todavía no es tendencia porque el mural vende. Va a serlo cuando el comprador corporativo pida el changelog antes que el mood. Medellín sin brochure: el arte afuera, el software adentro." },
    ],
  },
  {
    slug: "signal-callao-barco",
    title: "Si no puedes nombrar el barco, no tienes tesis de supply",
    dek: "Callao. El Pacífico deja de ser escala y empieza a ser contrato.",
    kicker: "Signals",
    section: "work",
    authorId: "rafael-quinn",
    franchise: "signals",
    pace: "rapida",
    tags: ["logistica", "nearshoring", "rapida"],
    publishedAt: "2026-08-18",
    updatedAt: "2026-08-18",
    readMinutes: 2,
    image: "/photos/lima-port.jpg",
    imageAlt: "Puerto del Callao",
    caption: "Callao. El barco tiene nombre.",
    city: "Lima",
    pullQuote: "Nombra el barco.",
    body: [
      { type: "p", text: "Tercer Turno nombra el barco en el handoff. No es poesía. Es un protocolo de supply que un 3PL de Miami no puede copiar sin estar en el muelle. En Callao hay dos operadores más que empezaron a redactar el turno en prosa." },
      { type: "p", text: "Todavía parece detalle de puerto. Va a ser tendencia cuando el CFO de São Paulo pida el nombre del buque en el QBR. El Pacífico se firma en Lima. El ticker, no." },
    ],
  },
  {
    slug: "signal-calendario-pared",
    title: "El calendario que se pega en la pared",
    dek: "Providencia. El estatus dejó el escenario y volvió al horario de apertura.",
    kicker: "Signals",
    section: "culture",
    authorId: "lina-cho",
    franchise: "signals",
    pace: "rapida",
    tags: ["retail", "moda", "rapida"],
    publishedAt: "2026-08-17",
    updatedAt: "2026-08-17",
    readMinutes: 2,
    image: "/photos/fashion-atelier.jpg",
    imageAlt: "Atelier y calendario",
    caption: "Casa Hilo. Tres metros, persiana que se abre.",
    city: "Santiago",
    pullQuote: "El estatus era el escenario. Ahora es el calendario.",
    body: [
      { type: "p", text: "Casa Hilo cabe en tres metros. Hay un calendario pegado a la pared y una persiana que se abre a la hora que dice. Cero drop. Cero lista de espera teatral. El barrio es el canal. Tres tiendas en Lastarria copiaron el letrero este mes: hora, no vibe." },
      { type: "p", text: "Todavía no es tendencia porque el drop vende screenshots. Va a serlo cuando la gerenta de retail pida un horario que se pueda fotografiar sin filtro. El estatus, otra vez, es aparecer." },
    ],
  },
];
