/**
 * Responsabilidad: la nota de portada de este número.
 * Usado por: lib/content.ts, que la une al resto en ARTICLES.
 * NO hace: no ordena ni consulta; es archivo, no lógica.
 *
 * Se guarda en la forma del CONTRATO y no en un modelo propio porque es la
 * misma nota que el sitio dibuja y que le entrega al orquestador: con dos
 * formas haría falta un adaptador de ida y otro de vuelta, y cada campo que el
 * adaptador no cubriera se perdería en silencio al corregir una nota ya
 * publicada. Lo propio de We Are Vander —kicker, epígrafe, ciudad, ritmo,
 * franquicia, cita destacada— viaja en `extra`, y se lee con los accesores de
 * lib/content.ts, nunca a mano.
 */
import type { WiwoSiteArticle } from "@wiwo/contract";

export const MELIMAFIA: WiwoSiteArticle = {
  id: "melimafia",
  title: "MeliMafia",
  summary: "Kaszek levantó más de tres mil millones de dólares. Un ex CFO conduce una compañía pública en Nasdaq. Doscientos ochenta y dos fundadores salieron de sus filas. Mercado Libre nunca fue vendida, nunca expulsó a su plana mayor y todavía crece al cincuenta por ciento. Su mafia no se parece a ninguna otra. Ese es exactamente el punto.",
  section: { id: "ideas", label: "Ideas" },
  author: { name: "Daniel Pinto", slug: "daniel-pinto", role: "Editor" },
  publishedAt: "2026-08-23",
  updatedAt: "2026-08-23",
  readingMinutes: 18,
  image: { url: "/photos/meli-office.jpg", alt: "Oficina de Mercado Libre en Buenos Aires, con la rampa de madera y la instalación de globos de colores" },
  tags: ["fintech", "pagos", "fondo"],
  featured: true,
  rank: null,
  body: {
    format: "blocks",
    blocks: [
      { type: "p", text: "La MeliMafia es el término que We Are Vander acuña para la red de capital, operadores y método que salió de Mercado Libre sin que la compañía fuera vendida. Kaszek levantó más de US$3.000 millones. Forbes Colombia (2024) reportó 282 fundadores salidos de sus filas. Mercado Libre nunca expulsó a su plana mayor y en 2025 facturó US$28.893 millones, según su 10-K ante la SEC." },
      { type: "p", text: "Empecemos por lo incómodo." },
      { type: "p", text: "El término no existe. Lo buscamos en español, en inglés y en portugués. No hay un solo artículo de prensa que hable de la «MeliMafia». Los inventarios latinoamericanos del género —y hay varios— listan a Rappi, a Nubank, a Gympass, a 99, a Glovo, a Linio. Ninguno menciona a Mercado Libre. La mafia latinoamericana con cobertura seria es la de Rappi: más de cien compañías desde 2015, mapeadas país por país, cuarenta y seis en Colombia, veintitrés en México, veinte en Brasil." },
      { type: "p", text: "Así que lo estamos acuñando nosotros. Conviene decirlo antes de seguir, porque el resto del artículo depende de que quede claro qué se está afirmando y qué no." },
      { type: "p", text: "Lo acuñamos igual, por dos razones. La primera es que el fenómeno existe y es grande. La segunda, más interesante, es que no se parece a nada de lo que la palabra «mafia» sugiere. Y esa diferencia es la nota." },
      { type: "h2", text: "Una mafia necesita una diáspora. Mercado Libre nunca la tuvo." },
      { type: "p", text: "El molde de todas estas historias es la PayPal Mafia, y el molde tiene una condición de origen que casi nadie menciona: PayPal fue vendida. eBay la compró en 2002 por mil quinientos millones de dólares y la plana mayor se fue. Cuando Fortune publicó en noviembre de 2007 la nota que popularizó el término, con la foto del grupo vestido de gánsteres, estaba retratando a un conjunto de personas expulsadas de su propia compañía cinco años antes, con dinero fresco en el bolsillo y nada que hacer. Thiel, Musk, Levchin, Chen, Hurley, Sacks. La cifra que hoy circula —Dealroom cuenta doscientas cincuenta y ocho compañías fundadas por alumni, un billón y medio de dólares de valor combinado en veintiséis países— es el resultado acumulado de ese despido colectivo." },
      { type: "p", text: "Una mafia, en el sentido en que la usa el negocio tecnológico, es una diáspora con liquidez. Necesita dos cosas: gente que salga y plata para que salga." },
      { type: "p", text: "Mercado Libre no tuvo ni la primera." },
      { type: "p", text: "Nunca fue vendida. Salió a bolsa el 9 de agosto de 2007 a dieciocho dólares por acción, la primera tecnológica latinoamericana en Nasdaq, y desde entonces no hizo otra cosa que componer. En 2025 facturó 28.893 millones de dólares, treinta y nueve por ciento más que el año anterior. El GMV llegó a 65.037 millones. Mercado Pago procesó 277.823 millones en pagos. La compañía cerró el año con 123.670 empleados: 61.139 en Brasil, 34.336 en México, 16.726 en Argentina. En el segundo trimestre de 2026 pasó por primera vez los diez mil millones de dólares en un solo trimestre. Vale alrededor de noventa y siete mil millones." },
      { type: "stat", value: "US$28.893 M", label: "Ingresos 2025" },
      { type: "stat", value: "123.670", label: "Empleados al cierre" },
      { type: "stat", value: "US$97.000 M", label: "Valor de mercado" },
      { type: "p", text: "Y su plana mayor sigue adentro. Osvaldo Giménez, que entró en enero de 2000 como country manager de Argentina y Chile, es hoy President of Fintech. Juan Martín de la Serna, que entró en 1999 como gerente de desarrollo de negocios, preside Argentina. Daniel Rabinovich entró en marzo de 2000 como desarrollador de aplicaciones y hoy es Presidente de Tecnología y Operaciones. Martín de los Santos es el CFO. Y Ariel Szarfsztejn, que llegó en 2017 desde Despegar y el Boston Consulting Group como VP de Estrategia, es el CEO global desde el 1 de enero de 2026." },
      { type: "p", text: "Marcos Galperín, que escribió el plan de negocios en marzo de 1999 mientras cursaba su MBA en Stanford, se corrió a Executive Chairman después de veintiséis años. Lo dijo así en su primera entrevista junto a su sucesor: «Si tenía que dar un paso al costado sin alguien listo, habría fallado en contratar gente mejor que yo»." },
      { type: "quote", text: "Si tenía que dar un paso al costado sin alguien listo, habría fallado en contratar gente mejor que yo.", cite: "Marcos Galperín" },
      { type: "p", text: "Szarfsztejn, sobre esa decisión: «No hay muchos ejemplos de CEO y fundadores que decidan dar un paso al costado en el mejor momento de la compañía». La llamó «una de las genialidades de Marcos»." },
      { type: "p", text: "Es una compañía que retiene. Eso, en la lógica de las mafias, debería ser el final del artículo. Por tamaño, Mercado Libre tampoco entra al Vander 20: esa lista es de compañías que ganan plata y todavía se pueden comparar como promesa." },
      { type: "p", text: "No lo es. Porque la influencia salió igual, solo que por otras tres puertas." },
      { type: "h2", text: "Primera puerta: el capital" },
      { type: "p", text: "En 2011, dos hombres que habían pasado la década anterior dentro de Mercado Libre fundaron un fondo y lo llamaron con la primera sílaba de cada apellido." },
      { type: "p", text: "Hernán Kazah cofundó Mercado Libre en 1999 y estuvo doce años adentro: nueve como COO y tres como CFO. Nicolás Szekasy se sumó como CFO a comienzos de los dos mil y condujo la salida a Nasdaq de 2007. Kaszek nació con noventa y cinco millones de dólares." },
      { type: "p", text: "Quince años después, el boilerplate corporativo de la firma dice: más de tres mil millones de dólares levantados a través de nueve fondos, más de ciento treinta compañías respaldadas. Su propio sitio contabiliza 131 compañías y 303 emprendedores. En 2022 tenían participación en dieciséis de los cuarenta y dos unicornios de la región." },
      { type: "stat", value: "US$3.000 M+", label: "Levantados por Kaszek" },
      { type: "stat", value: "131", label: "Compañías en portafolio" },
      { type: "stat", value: "303", label: "Emprendedores respaldados" },
      { type: "p", text: "La lista del portafolio es, básicamente, el índice de la década tecnológica latinoamericana: Nubank, QuintoAndar, Kavak, Creditas, Bitso, Wellhub, Nuvemshop, Loggi, NotCo, Xepelin, Kushki." },
      { type: "p", text: "Vale la pena detenerse en una anécdota que Szekasy contó cuando explicó por qué en 2019 empezaron a levantar fondos de oportunidad además de los de etapa temprana: «Invertimos en Nubank desde etapas tempranas, pero en la serie C nos quedamos sin capital»." },
      { type: "quote", text: "Invertimos en Nubank desde etapas tempranas, pero en la serie C nos quedamos sin capital.", cite: "Nicolás Szekasy" },
      { type: "p", text: "Es una frase de operador, no de inversor. Kaszek no fue castigado por elegir mal. Fue castigado por no tener suficiente balance para sostener lo que había elegido bien. La solución —levantar vehículos de continuación para no diluirse en sus propios aciertos— es exactamente el tipo de problema que un CFO que sacó una compañía a bolsa reconoce antes que un capitalista de riesgo." },
      { type: "p", text: "Cuando les preguntaron qué se llevaron de haber atravesado el estallido puntocom desde adentro de Mercado Libre, los dos dieron la misma respuesta en tres partes: evitar atajos, pensar a largo plazo y minimizar la dependencia del capital externo." },
      { type: "p", text: "Esa última es notable viniendo de dos personas cuyo oficio actual es dar capital externo. Y describe con precisión lo que hizo Mercado Libre en 2001, cuando el mercado se cayó encima de la región: mientras los competidores quemaban caja, MELI se sentó sobre cuarenta millones de dólares en reservas. Galperín lo resumió años después en Stanford con una frase que no tiene ninguna elegancia y por eso funciona: «Realmente guardamos la plata para los días de lluvia»." },
      { type: "quote", text: "Realmente guardamos la plata para los días de lluvia.", cite: "Marcos Galperín" },
      { type: "p", text: "Con esa caja compró después a los rivales que no habían guardado nada." },
      { type: "h2", text: "Segunda puerta: el mando" },
      { type: "p", text: "El 15 de agosto de 2023, dLocal anunció que Pedro Arnt sería su co-CEO. Arnt había entrado a Mercado Libre en diciembre de 1999 y había sido su CFO durante más de doce años. Siete meses después, en marzo de 2024, quedó como CEO único." },
      { type: "p", text: "El cofundador de dLocal, Sergio Fogel, explicó el traspaso con una frase que debería estar enmarcada en toda sala de directorio de la región: «El liderazgo que se necesita para ir de cero a uno no es el mismo que para ir de uno a cien»." },
      { type: "quote", text: "El liderazgo que se necesita para ir de cero a uno no es el mismo que para ir de uno a cien.", cite: "Sergio Fogel" },
      { type: "p", text: "Ese es el segundo canal, y es el menos discutido: Mercado Libre no solo produce fundadores. Produce gente capaz de conducir compañías que otros fundaron. Es una categoría distinta y, para un ecosistema, probablemente más escasa. Fundadores hay muchos. Operadores que sepan tomar una compañía de mil millones de dólares y llevarla a diez mil, sin haberla creado, casi no hay." },
      { type: "p", text: "Los resultados de dLocal bajo Arnt son de manual de escala: en el segundo trimestre de 2026 el volumen procesado llegó a 17.700 millones de dólares, noventa y dos por ciento más que un año antes, con siete trimestres consecutivos creciendo por encima del cincuenta por ciento. Los ingresos subieron cincuenta y seis por ciento; la utilidad neta, veintiocho." },
      { type: "p", text: "El mismo patrón se repite más abajo en la escala. Justo Ferraro, que se sumó a Mercado Libre en 2015 y lideró el crecimiento de Mercado Pago Point en la región, es hoy CEO de Fudo, el software de gestión para restaurantes fundado en Argentina en 2014 por Juan Manuel Cuello. Ferraro no lo fundó: lo tomó y lo escaló. Fudo llegó bootstrapped hasta 2022 con ocho mil restaurantes; hoy tiene más de veinticinco mil clientes activos en Argentina, Chile, México y Brasil, con una ronda semilla de siete millones y medio de dólares codirigida por a16z. Su COO, Rafael Teles, también viene de Mercado Pago." },
      { type: "p", text: "Y cuando sí fundan, fundan sobre lo que aprendieron. Hernán Corral pasó doce años en Mercado Pago liderando cuentas digitales y tarjetas. En 2021 cofundó Pomelo, la infraestructura de emisión de tarjetas para fintechs latinoamericanas. En enero de 2026 Pomelo cerró una Serie C de cincuenta y cinco millones de dólares liderada por Kaszek e Insight Partners, con lo que acumula ciento sesenta millones levantados y alrededor de ciento cincuenta clientes, entre ellos Santander, BBVA, Bancolombia y Western Union." },
      { type: "p", text: "Corral es uno de tres cofundadores. Los otros dos vienen de Google, de Naranja X y de Mastercard. Lo aclaramos porque importa: la red no es un club cerrado, y presentar a Pomelo como «la fintech de los de Mercado Libre» sería falso." },
      { type: "p", text: "Pero notemos el circuito completo. Un hombre que pasó doce años construyendo la capa de tarjetas de Mercado Pago funda la compañía que le vende esa capa a los bancos de la región, y la financia el fondo de los dos hombres que construyeron Mercado Libre. Ese circuito no existía en América Latina hace quince años." },
      { type: "h2", text: "Tercera puerta: el método" },
      { type: "p", text: "Esta es la más difícil de medir y probablemente la más valiosa." },
      { type: "p", text: "Un estudio de Gilgamesh Ventures con investigadores de Wharton, publicado en agosto de 2024, midió cuántos fundadores salieron de quince compañías fintech del mundo. Según el desglose que reportó Forbes Colombia, Mercado Libre produjo doscientos ochenta y dos fundadores; Rappi, doscientos noventa; Nubank, ciento veintiséis; Creditas, setenta y tres. Endeavor Argentina, por su lado, contó en mayo de 2023 alrededor de noventa startups fundadas por ex empleados de MELI, y a Galperín asesorando a más de veinte emprendedores por fuera de la compañía." },
      { type: "stat", value: "282", label: "Fundadores salidos de MELI" },
      { type: "stat", value: "90", label: "Startups según Endeavor AR" },
      { type: "p", text: "Ninguna de estas cifras es del todo dura —Endeavor advierte que sus mapas no son exhaustivos, y el desglose por compañía del estudio de Wharton lo tomamos de la cobertura, no del documento original—. Pero el orden de magnitud es consistente y apunta a lo mismo: de esta compañía sale gente que después construye." },
      { type: "p", text: "La pregunta es qué se aprende adentro. Y acá hay testimonio de primera mano." },
      { type: "p", text: "Sebastián Barrios fue Head of Product and Engineering de Mercado Libre; hoy es SVP of Engineering en Roblox. Su descripción de cómo opera la compañía por dentro es lo más útil que se ha publicado sobre el tema. Dieciocho mil ingenieros en dieciocho países. Treinta mil despliegues de código por día. Y alrededor de mil product managers, cerca del cinco por ciento del cuerpo de ingeniería, cuando la industria tecnológica trabaja con veinte o treinta por ciento." },
      { type: "p", text: "Ese ratio no es un ahorro. Es una decisión de diseño. Con cinco por ciento de PMs, el producto no puede pensarlo el PM. Lo tiene que pensar el ingeniero. Barrios lo dice en una línea: «No dejamos que los títulos determinen quién es dueño del producto»." },
      { type: "quote", text: "No dejamos que los títulos determinen quién es dueño del producto.", cite: "Sebastián Barrios" },
      { type: "p", text: "Tampoco usan OKRs en cascada. El liderazgo fija de tres a cinco objetivos de compañía, los refresca cada trimestre, y los equipos operan con autonomía casi total. La rendición de cuentas es por presión de pares y por presentar resultados en público, no por control jerárquico. Las revisiones de producto son brutalmente francas, con una regla explícita que hace que se puedan sostener: «Esto es sobre el producto, no sobre vos»." },
      { type: "p", text: "Y sobre Galperín, un detalle que dice más que cualquier declaración de misión: antes de discutir ingresos o métricas, pregunta siempre lo mismo. Cómo va a experimentar esto el usuario." },
      { type: "p", text: "En la contratación hay un mecanismo equivalente. Mercado Libre usa un entrevistador bar raiser —externo al área que contrata— cuya única función en la entrevista final es evaluar encaje cultural. El Chief People Officer, Sebastián Fernández Silva, lo describe sin adornos: «Su rol es mirar que la gente que sumamos vibre con nuestra cultura». El equipo de reclutamiento es cien por ciento interno, sin tercerización. Y priorizan agilidad de aprendizaje por sobre credenciales técnicas, con el argumento de que hoy la tecnología es la inteligencia artificial y mañana va a ser otra." },
      { type: "p", text: "No es retórica. En su reporte anual la compañía declara que alrededor del noventa y cinco por ciento de sus empleados adoptó herramientas de IA generativa, que cerca del treinta por ciento del código que llega a producción se escribe con asistencia de IA, y que entrenó a más de veintitrés mil personas en resolución de problemas de negocio con esas herramientas. En 2025 incorporó más de treinta y nueve mil personas y formó a tres mil ciento cincuenta líderes como, textualmente, multiplicadores de su ADN." },
      { type: "p", text: "Hay algo más, y es estructural. Desde el prospecto de su salida a bolsa, Mercado Libre declara una arquitectura poco intuitiva: una sola plataforma tecnológica, pero cada país operado como un mercado separado, sin interacción con los demás. Sede societaria en Delaware, sede operativa en Montevideo, reporte en dólares, licencias fintech tramitadas jurisdicción por jurisdicción, resultados segmentados por país y no por línea de producto. Cuando el régimen cambiario venezolano se volvió irreconciliable, desconsolidó el país del perímetro contable y siguió." },
      { type: "p", text: "Un gerente formado ahí acumula, en cinco años, decisiones que en una multinacional tradicional toma un comité en otro continente: operar con dieciocho marcos regulatorios, dos negocios estructuralmente distintos en el mismo estado de resultados —comercio y crédito—, monedas que se rompen, y una cultura que no le da cobertura jerárquica para no decidir." },
      { type: "p", text: "Eso es lo que se exporta. No una lista de contactos. Un estándar de operación." },
      { type: "h2", text: "Lo que no funcionó, porque también cuenta" },
      { type: "p", text: "Un artículo que solo suma no sirve de nada." },
      { type: "p", text: "En septiembre de 2021, Mercado Libre y Kaszek se juntaron después de catorce años para lanzar MELI Kaszek Pioneer Corp, una SPAC que levantó doscientos ochenta y siete millones de dólares en Nasdaq para comprar compañías tecnológicas latinoamericanas. Galperín era asesor. Pedro Arnt, entonces CFO en ejercicio de Mercado Libre, era co-CEO del vehículo junto a Kazah y Szekasy." },
      { type: "p", text: "En junio de 2023 se liquidó sin haber comprado absolutamente nada. Todos los accionistas recuperaron su dinero." },
      { type: "p", text: "Kazah lo explicó con una franqueza que no abunda: salieron con el mercado recalentado y, cuando el ciclo se dio vuelta, las compañías que valían la pena no quisieron fusionarse a lo que consideraban precios injustos. «El problema no fue el vehículo en sí», dijo. Puede ser. También puede ser que la red más poderosa del negocio latinoamericano, con la mejor información disponible, se haya equivocado de timing como cualquiera." },
      { type: "p", text: "dLocal tampoco es una línea recta. La acción cotiza alrededor de quince dólares, por debajo de los veintiuno de su salida a bolsa de 2021. El margen bruto se comprimió de treinta y nueve a treinta y dos por ciento en un año: el volumen crece al noventa y dos por ciento pero la utilidad bruta crece al veintinueve, lo que significa que buena parte del crecimiento se está comprando barato. Y la compañía carga desde 2022 con el antecedente de un informe de vendedor en corto que la acusó de fraude y le borró la mitad del valor en una jornada, acusación que dLocal rechazó por infundada." },
      { type: "p", text: "Y no toda salida se convierte en algo. Alan Meyer, el ejecutivo que lideró la expansión de Mercado Libre en Chile y la región andina, renunció en junio de 2026 después de doce años. Un mes después no había fundado nada. Estaba escribiendo un libro." },
      { type: "p", text: "Está bien que así sea. La narrativa de que cada persona que sale de una gran compañía funda un unicornio es exactamente el tipo de relato que este medio existe para no repetir." },
      { type: "h2", text: "El contraargumento que hay que tomar en serio" },
      { type: "p", text: "El más fuerte es de tamaño. Rappi tiene más de cien compañías mapeadas y desagregadas por país. Mercado Libre tiene una cifra de Endeavor de hace tres años, no verificada compañía por compañía, y un estudio académico cuyo desglose llega por prensa. Nosotros mismos verificamos diecisiete pistas de startups supuestamente fundadas por ex MELI y sobrevivieron cuatro. Tiendanube, Melonn, Increase, Nuvocargo, Tapi, Kavak, Nubank, Ualá: ninguna tiene fundadores que hayan pasado por Mercado Libre. Varias están en el portafolio de Kaszek, que es un vínculo de capital y no de linaje." },
      { type: "p", text: "El segundo contraargumento es más de fondo, y viene de la literatura académica. El trabajo canónico sobre por qué ciertas empresas engendran emprendedores —Gompers, Lerner y Scharfstein, en el Journal of Finance de 2005— encontró que las compañías que más fundadores producen no son las más grandes ni las más exitosas, sino las que ellas mismas estuvieron inmersas en el circuito del capital de riesgo. Gana la hipótesis del aprendizaje y las redes por sobre la de la frustración." },
      { type: "p", text: "Aplicado acá, eso relativiza el mito: si Mercado Libre produce operadores, no es únicamente por su cultura. Es también porque en noviembre de 1999 y mayo de 2000 levantó capital de riesgo de J.P. Morgan, Goldman Sachs, Hicks Muse y el Santander, y expuso a toda una generación de gerentes latinoamericanos a cómo funciona ese circuito por dentro." },
      { type: "p", text: "Y hay un tercero, incómodo. La evidencia de los estudios de efecto multiplicador —el de Cabify es el más explícito— muestra que quienes fundan las compañías de mayor impacto son los ejecutivos, no la plantilla. El multiplicador no multiplica parejo. Multiplica hacia arriba. Mercado Libre cerró 2025 con 123.670 empleados y una red de última milla que, por diseño, opera con transportistas de terceros y no con nómina propia. Las doscientas ochenta y dos personas que fundaron algo no salieron de esa capa." },
      { type: "h2", text: "Lo que queda" },
      { type: "p", text: "La MeliMafia no es una diáspora. Es lo contrario: una compañía que retuvo a casi todos sus cuadros durante veintisiete años y que aun así reordenó el negocio latinoamericano por tres vías laterales. Un fondo que hoy financia a media región. Un puñado de operadores que conducen compañías que no fundaron. Y un estándar de operación —autonomía sin cobertura, producto sin jerarquía, país por país con P&L propio— que viaja en la cabeza de cada persona que se va." },
      { type: "p", text: "Para 2026 anunció inversiones por cincuenta y siete mil millones de reales en Brasil, cuatro mil seiscientos millones de dólares en México y tres mil cuatrocientos millones en Argentina. Sigue contratando de a decenas de miles." },
      { type: "p", text: "La pregunta interesante no es cuántas startups salieron de Mercado Libre. Es qué pasa el día que sí haya una diáspora." },
      { type: "p", text: "Porque las mafias, en el sentido técnico del término, se forman cuando alguien vende. Y a esta compañía no la compró nadie." },
      { type: "h2", text: "Fuentes" },
      { type: "p", text: "MercadoLibre Inc., Formulario 10-K del ejercicio 2025 (SEC, 25/02/2026) — https://www.sec.gov/Archives/edgar/data/1099590/000109959026000006/meli-20251231.htm" },
      { type: "p", text: "MercadoLibre Inc., Proxy Statement 2026 (SEC) — https://www.sec.gov/Archives/edgar/data/1099590/000109959026000010/meli-20260423.htm" },
      { type: "p", text: "MercadoLibre Inc., prospecto final de oferta pública inicial, Formulario 424B1 (SEC, 09/08/2007) — https://www.sec.gov/Archives/edgar/data/1099590/000119312507178904/d424b1.htm" },
      { type: "p", text: "«Marcos Galperin: Growing Latin America's Online Marketplace», Stanford Graduate School of Business (01/03/2011) — https://www.gsb.stanford.edu/insights/marcos-galperin-growing-latin-americas-online-marketplace" },
      { type: "p", text: "«Kaszek closes on $975M across two new funds to back Latin American startups», TechCrunch (03/04/2023) — https://techcrunch.com/2023/04/03/kaszek-closes-on-975m-across-two-new-funds-to-back-latin-american-startups/" },
      { type: "p", text: "«Still Betting Big: Argentine Venture Capitalists Hernán Kazah and Nicolás Szekasy», Americas Quarterly (26/07/2022) — https://www.americasquarterly.org/article/still-betting-big-argentine-venture-capitalists-hernan-kazah-and-nicolas-szekasy/" },
      { type: "p", text: "Kaszek, sitio institucional — https://www.kaszek.com/" },
      { type: "p", text: "«dLocal Appoints Pedro Arnt as Co-Chief Executive Officer», comunicado oficial (15/08/2023) — https://dlocal.gcs-web.com/news-releases/news-release-details/dlocal-appoints-pedro-arnt-co-chief-executive-officer-alongside/" },
      { type: "p", text: "«Exclusive: dLocal Appoints Pedro Arnt As CEO As Sebastián Kanovich Steps Back», Forbes (18/03/2024) — https://www.forbes.com/sites/danielwebber/2024/03/18/exclusive-dlocal-appoints-pedro-arnt-as-ceo-as-sebastin-kanovich-steps-back/" },
      { type: "p", text: "«dLocal Reports Second Quarter 2026 Financial Results» (13/08/2026) — https://www.globenewswire.com/news-release/2026/08/13/3344936/0/en/dlocal-reports-second-quarter-2026-financial-results.html" },
      { type: "p", text: "«Inside Mercado Libre» — entrevista a Sebastián Barrios, Lenny's Newsletter (08/06/2025) — https://www.lennysnewsletter.com/p/inside-mercado-libre-sebastian-barrios" },
      { type: "p", text: "«Por qué todos quieren trabajar en Mercado Libre», El Cronista / Apertura (17/10/2025) — https://www.cronista.com/apertura/empresas/por-que-todos-quieren-trabajar-en-mercado-libre-que-diferencia-su-cultura-de-la-de-otras-empresas/" },
      { type: "p", text: "«Mapas interactivos del Efecto Multiplicador», Endeavor Argentina (04/05/2023) — https://www.endeavor.org.ar/blog-article-novedades-mapas-interactivos-efecto-multiplicador-emprendedores-endeavor/" },
      { type: "p", text: "«Rappi, Mercado Libre y Nu, entre las fintech que más han formado a fundadores», Forbes Colombia (25/10/2024) — https://forbes.co/emprendedores/rappi-mercado-libre-y-nu-entre-las-fintech-que-mas-han-formado-a-fundadores-de-nuevas-companias-en-america" },
      { type: "p", text: "«LatAm fintech Pomelo secures $55m Series C», FinTech Futures (23/01/2026) — https://www.fintechfutures.com/venture-capital-funding/latam-fintech-pomelo-secures-55m-series-c" },
      { type: "p", text: "«Argentina's Pomelo raises $9M to build a new payments infrastructure for LatAm fintechs», TechCrunch (12/05/2021) — https://techcrunch.com/2021/05/12/argentinas-pomelo-raises-9m-to-build-a-new-payments-infrastructure-for-latam-fintechs" },
      { type: "p", text: "«Andreessen, Atlántico, Maya Capital back Fudo's seed round», TechCrunch (19/08/2022) — https://techcrunch.com/2022/08/19/andreessen-atlantico-maya-capital-fudos-seed-restaurant-tech" },
      { type: "p", text: "«Hernán Kazah says SPACs remain on the radar even if MEKA was shut down», Bloomberg Línea — https://www.bloomberglinea.com/english/hernan-kazah-says-spacs-remain-on-the-radar-even-if-meka-was-shut-down/" },
      { type: "p", text: "«The PayPal Mafia», Jeffrey M. O'Brien, Fortune (13/11/2007) — https://money.cnn.com/2007/11/13/magazines/fortune/paypal_mafia.fortune/index.htm" },
      { type: "p", text: "Dealroom, ficha «PayPal founder mafia» — https://dealroom.co/talent/founder-mafias/paypal/" },
      { type: "p", text: "«Qué es la Rappi Mafia y cómo impulsa startups en América Latina», Infobae (05/08/2026) — https://www.infobae.com/tecno/2026/08/05/que-es-la-rappi-mafia-y-como-impulsa-startups-en-america-latina-desde-energia-hasta-ciberseguridad/" },
      { type: "p", text: "Gompers, Lerner y Scharfstein, «Entrepreneurial Spawning», Journal of Finance 60(2), 2005 — https://www.nber.org/papers/w9816" },
      { type: "p", text: "«El impacto global de los ex empleados de Cabify», Endeavor Spain — https://spain.endeavor.org/el-impacto-global-de-los-ex-empleados-de-cabify/" },
      { type: "p", text: "«MercadoLibre (MELI) Q2 2026 Earnings Call Transcript» (12/08/2026) — https://www.fool.com/earnings/call-transcripts/2026/08/12/mercadolibre-meli-q2-2026-earnings-call-transcript/" },
      { type: "p", text: "«Renuncia Alan Meyer, histórico ejecutivo que lideró la expansión de Mercado Libre en Chile», El Mostrador (26/06/2026) — https://www.elmostrador.cl/mercados/2026/06/26/renuncia-alan-meyer-historico-ejecutivo-que-lidero-la-expansion-de-mercado-libre-en-chile/" },
      { type: "p", text: "«La primera entrevista de Marcos Galperin y su sucesor Ariel Szarfsztejn», Forbes Argentina (11/2025) — https://www.forbesargentina.com/negocios/la-primera-entrevista-marcos-galperin-su-sucesor-ariel-szarfsztejn-planes-mercadolibre-2026-n82509" },
    ],
  },
  seo: {
    title: "MeliMafia: la red de Mercado Libre, sin venta",
    description: "We Are Vander acuña MeliMafia: Kaszek, dLocal y 282 fundadores salieron de Mercado Libre sin que la compañía fuera vendida. Cifras del 10-K 2025.",
    tldr: [
      "We Are Vander acuña «MeliMafia» para la red de Mercado Libre: no es una diáspora, porque la compañía nunca fue vendida.",
      "Kaszek, el fondo de Hernán Kazah y Nicolás Szekasy, levantó más de US$3.000 millones y respaldó 131 compañías.",
      "Pedro Arnt, ex CFO de MELI, es CEO de dLocal. Hernán Corral cofundó Pomelo. Justo Ferraro es CEO de Fudo.",
      "Forbes Colombia (2024) reportó 282 fundadores salidos de Mercado Libre, según Gilgamesh Ventures y Wharton. La cifra no está auditada compañía por compañía.",
      "Las mafias, en el sentido técnico, se forman cuando alguien vende. A Mercado Libre no la compró nadie.",
    ],
    faq: [
      {
        question: "¿Qué es la MeliMafia?",
        answer: "Es el término que We Are Vander acuña en 2026 para la red de capital, operadores y método que salió de Mercado Libre sin una venta. No aparece en la prensa previa. No es una diáspora: la plana mayor sigue adentro.",
      },
      {
        question: "¿Kaszek salió de Mercado Libre?",
        answer: "Sí. Hernán Kazah cofundó MELI y fue COO y CFO. Nicolás Szekasy fue CFO y condujo el IPO de 2007. En 2011 fundaron Kaszek. El sitio de la firma cuenta 131 compañías y 303 emprendedores respaldados.",
      },
      {
        question: "¿Cuántos fundadores salieron de Mercado Libre?",
        answer: "Forbes Colombia (octubre 2024) reportó 282 a partir de un estudio de Gilgamesh Ventures con Wharton. Endeavor Argentina (mayo 2023) contó alrededor de 90 startups. Ninguna de las dos cifras es un censo auditado.",
      },
      {
        question: "¿Por qué Mercado Libre no está en el Vander 20?",
        answer: "Por tamaño. El Vander 20 excluye consolidadas. Mercado Libre facturó US$28.893 millones en 2025 y vale alrededor de US$97.000 millones. Ya no es promesa: es resultado.",
      },
    ],
  },
  extra: {
    kicker: "Ideas",
    caption: "Una compañía que retiene. La influencia salió igual, por otras tres puertas.",
    city: "Buenos Aires",
    pace: "fondo",
    pullQuote: "Las mafias se forman cuando alguien vende. Y a esta compañía no la compró nadie.",
    signedName: "Daniel Pinto",
    ogTitle: "La mafia de Mercado Libre, sin venta",
    ogDescription: "Kaszek salió. Galperin no. Acuñamos MeliMafia para la red que no es una diáspora.",
    ogImage: "/og/melimafia.jpg",
  },
};
