export const VOLUME_PHOTO_SLUGS = {
  cl: [
    "cristina-etcheberry", "francisca-noguera", "cristobal-griffero", "lukas-zorich", "omar-larre", "andres-marinkovic",
    "guillermo-torrealba", "sebastian-kreis", "nicolas-de-camino", "martin-del-castillo", "ramon-echeverria", "ignacio-detmer-latorre",
    "polo-diaz", "nicolas-camhi-guerrero", "ian-lee", "ignacio-ponce-castro", "isis-riquelme-arredondo", "cristobal-valenzuela-barrera",
    "jaime-arrieta-boetsch", "felipe-torres", "francesco-crivelli", "matias-muchnick", "francisca-castillo-castro", "daniel-norero",
    "jose-del-solar", "rocio-espinoza", "kris-blanchard", "carolina-aguila-diaz", "leonardo-alvarez", "claudio-pedreros",
    "diego-gutierrez", "alejandra-allendes", "pamela-salazar-cifuentes", "melissa-munoz-flandez", "ricardo-susaeta", "manuel-aguirre-olivares",
    "andres-kemeny", "nicolas-uribe-espinoza", "eloisa-koch", "carolina-cabalin", "alejandra-gatica-salgado", "beatriz-palma",
    "felipe-prado-gilles", "natalia-perez", "komal-dadlani", "carlos-aravena", "elisa-torres-durney", "francisca-koppmann-kuester",
    "melania-sanhueza", "martin-seguel", "izumi-nakagawa", "maria-ignacia-urzua-reyes", "alejandra-acevedo", "valentina-barna-fermandois",
    "aline-israel", "benjamin-labra", "alvaro-echeverria", "benjamin-santa-maria", "rodrigo-segal", "kim-maturana",
    "diego-pradenas-espinoza", "raimundo-zamora-baeza", "rodrigo-haydar", "constanza-levican-cardenas", "ignacio-parada-da-fonseca", "oscar-munoz-cofre",
    "matias-moya", "paloma-gonzalez-rojas", "fernando-ojeda-soto", "felipe-nunez-lopez", "valentina-veloso", "jennifer-araya-venegas",
    "nadac-reales-del-canto", "camila-briceno-albages", "joaquin-gonzalez", "diego-siguelnitzky", "jose-manuel-moller", "thomas-kimber",
    "isidora-uribe-silva", "samuel-santa-cruz", "angela-astudillo", "bernardita-frez", "ismaela-magliotto-quevedo", "alvaro-silberstein",
    "diego-antonio-gonzalez", "antonia-rojas-eing", "paula-enei", "maria-jose-alvarez", "andres-matte", "damian-panes",
    "manuel-concha", "jose-manuel-jimenez-marin", "andres-ugarte", "pier-paolo-colonnello", "felipe-cevallos-becker", "barbarita-lara-martinez",
    "andrea-donoso-youlton", "florencia-alamos-grau", "melissa-jeldes", "daniela-fernandez-rosso", "marcela-ruiz-aguilar",
  ],
  ar: [
    "pierpaolo-barbieri", "ariel-sbdar", "marcelo-cavazzoli", "borja-martel-seward", "tomas-mindlin", "federico-ogue",
    "helena-polyblank", "mercedes-bidart", "rodrigo-vidal", "guillermo-rauch", "nicolas-benenzon", "geronimo-maspero",
    "albert-gozzi", "demian-brener", "franco-rodriguez-viau", "maria-cristina-soraires", "ricky-cassini", "franco-martinez-levis",
    "juan-manuel-baruffaldi", "julieta-porta", "daniela-teplitzki", "mateo-salvatto", "ingrid-briggiler", "keila-barral-masri",
    "juan-belmont", "matias-massotti", "ramiro-gonzalez-forcada", "veronica-silva", "ignacio-gorriti", "lautaro-loguzzo",
    "violeta-munoz", "benjamin-korach", "facundo-rancano", "felipe-ojeda", "leandro-lima", "sofia-contreras",
    "maritsa-puma", "marcos-galperin", "hernan-kazah", "nicolas-szekasy", "martin-migoya", "guibert-englebienne",
    "wenceslao", "alec-oxenford", "emiliano-kargieman", "matias-woloski", "mariano-suarez-battan", "santiago-sosa",
    "federico-trucco", "santiago-bilinkis", "marta-cruz", "ariel-arrieta", "mariano-mayer", "luis-bermejo",
    "lorena-suarez", "andrea-grobocopatel",
  ],
  co: [
    "santiago-suarez-vallejo", "daniel-bilbao", "alejandro-casas", "jose-vicente-gedeon", "julian-nunez", "christian-knudsen-daccach",
    "marcela-santiago-rizo", "juan-pisco", "felipe-chavez-cortes", "laura-velasquez-herrera", "nicolas-rojas-nino", "luis-ricardo-almanza-herazo",
    "marybel-montoya-alvarez", "eduardo-andres-ospina", "simon-borrero", "jeronimo-uribe-moreno", "freddy-vega", "enrique-villamarin-lafaurie",
    "juan-pablo-ortega", "daniela-izquierdo", "alexander-torrenegra", "david-velez-osorno", "manuela-sanchez", "jose-fernando-velez",
    "julian-torres-gomez", "paula-barrientos-moreno", "felipe-santamaria", "andres-barreto", "miguel-mcallister", "felipe-ossa",
    "laura-forero", "andres-vejarano", "paula-marcela-moreno-zapata", "catalina-escobar",
  ],
} as const;
