export const VOLUME_PHOTO_SLUGS = {
  cl: [
    "cristina-etcheberry", "francisca-noguera", "cristobal-griffero", "lukas-zorich", "omar-larre", "andres-marinkovic",
    "guillermo-torrealba", "sebastian-kreis", "nicolas-de-camino", "martin-del-castillo", "ramon-echeverria", "ignacio-detmer-latorre",
    "polo-diaz", "nicolas-camhi-guerrero", "ian-lee", "ignacio-ponce-castro", "isis-riquelme-arredondo", "cristobal-valenzuela-barrera",
    "jaime-arrieta-boetsch", "felipe-torres", "francesco-crivelli", "matias-muchnick", "francisca-castillo-castro", "daniel-norero",
    "jose-del-solar", "rocio-espinoza", "kris-blanchard", "carolina-aguila-diaz", "leonardo-alvarez", "claudio-pedreros",
    "diego-gutierrez", "alejandra-allendes", "pamela-salazar-cifuentes", "melissa-munoz-flandez", "ricardo-susaeta", "manuel-aguirre-olivares",
    "andres-kemeny", "nicolas-uribe-espinoza", "eloisa-koch", "carolina-cabalin", "alejandra-gatica-salgado", "beatriz-palma",
    "felipe-prado-gilles", "natalia-perez", "komal-dadlani", "carlos-aravena", "elisa-torres-durney", "francisca-koppmann-kuester",
    "melania-sanhueza", "martin-seguel", "izumi-nakagawa", "maria-ignacia-urzua-reyes", "alejandra-acevedo", "valentina-barna-fermandois",
    "aline-israel", "benjamin-labra", "alvaro-echeverria", "benjamin-santa-maria", "rodrigo-segal", "kim-maturana",
    "diego-pradenas-espinoza", "raimundo-zamora-baeza", "rodrigo-haydar", "constanza-levican-cardenas", "ignacio-parada-da-fonseca", "oscar-munoz-cofre",
    "matias-moya", "paloma-gonzalez-rojas", "fernando-ojeda-soto", "felipe-nunez-lopez", "valentina-veloso", "jennifer-araya-venegas",
    "nadac-reales-del-canto", "camila-briceno-albages", "joaquin-gonzalez", "diego-siguelnitzky", "jose-manuel-moller", "thomas-kimber",
    "isidora-uribe-silva", "samuel-santa-cruz", "angela-astudillo", "bernardita-frez", "ismaela-magliotto-quevedo", "alvaro-silberstein",
    "diego-antonio-gonzalez", "antonia-rojas-eing", "paula-enei", "maria-jose-alvarez", "andres-matte", "damian-panes",
    "manuel-concha", "jose-manuel-jimenez-marin", "andres-ugarte", "pier-paolo-colonnello", "felipe-cevallos-becker", "barbarita-lara-martinez",
    "andrea-donoso-youlton", "florencia-alamos-grau", "melissa-jeldes", "daniela-fernandez-rosso", "marcela-ruiz-aguilar",
  ],
  ar: [
    "pierpaolo-barbieri", "ariel-sbdar", "marcelo-cavazzoli", "borja-martel-seward", "tomas-mindlin", "federico-ogue",
    "helena-polyblank", "mercedes-bidart", "bianca-sassoon", "nahuel-candia", "rodrigo-vidal", "guillermo-rauch",
    "nicolas-benenzon", "geronimo-maspero", "mateo-cavasotto", "albert-gozzi", "demian-brener", "luciana-reznik",
    "bruno-calcagno", "gonzalo-waisman", "marcos-bruno", "matias-bonfigli", "ignacio-belieres-montero", "franco-rodriguez-viau",
    "maximo-salzmann", "alejandro-bisi", "maria-cristina-soraires", "franco-kraiselburd", "ricky-cassini", "franco-martinez-levis",
    "juan-manuel-baruffaldi", "guadalupe-murga", "julieta-porta", "maria-paz-alvarez", "daniela-teplitzki", "federico-wajnerman",
    "matias-viel", "tatiana-malvasio", "mateo-salvatto", "ingrid-briggiler", "keila-barral-masri", "juan-belmont",
    "matias-massotti", "sofia-di-franco", "ramiro-gonzalez-forcada", "veronica-silva", "luciana-gasser", "ignacio-gorriti",
    "franco-forte", "lautaro-loguzzo", "violeta-munoz", "ivan-buhajeruk", "benjamin-korach", "facundo-rancano",
    "stefania-kessel", "delfina-ferro", "felipe-ojeda", "leandro-lima", "paula-gianserra", "nicki-becker",
    "martin-vazquez-jones", "sofia-contreras", "maritsa-puma", "marcos-galperin", "hernan-kazah", "nicolas-szekasy",
    "martin-migoya", "guibert-englebienne", "martin-umaran", "wenceslao", "alec-oxenford", "emiliano-kargieman",
    "matias-woloski", "eugenio-pace", "mariano-suarez-battan", "santiago-sosa", "roberto-souviron", "federico-trucco",
    "santiago-bilinkis", "andy-freire", "marta-cruz", "ariel-arrieta", "mariano-mayer", "patricio-jutard",
    "luis-bermejo", "lorena-suarez", "nicolas-tognalli", "julia-bearzi", "silvia-torres-carbonell", "andrea-grobocopatel",
    "paula-arregui",
  ],
  co: [
    "santiago-suarez-vallejo", "daniel-bilbao", "maite-muniz-telleria", "alejandro-casas", "jose-vicente-gedeon", "julian-nunez",
    "vanessa-rodriguez", "cipriano-echavarria", "christian-knudsen-daccach", "marcela-santiago-rizo", "juan-pisco", "felipe-chavez-cortes",
    "laura-velasquez-herrera", "jose-david-gomez-zea", "nicolas-rojas-nino", "valentina-valencia", "santiago-rodriguez", "pablo-sanchez-villamarin",
    "maria-camila-rueda", "viviana-gomez", "luis-ricardo-almanza-herazo", "melina-cruz", "daniela-barrios", "vanessa-jadad",
    "isabella-espinosa", "angela-maria-acosta", "stephanie-gomez", "cristina-char", "jose-ricardo-betancur", "camilo-mejia-plata",
    "jaime-giraldo", "andres-sarrazola", "santiago-acevedo", "andres-felipe-garcia", "beatriz-dager", "camilo-olarte",
    "valentina-agudelo", "catalina-isaza", "francisco-jassir", "carolina-gonzalez", "juan-echeverri", "marco-osorio",
    "maria-carolina-angulo", "cristal-carvajal-giraldo", "maria-del-mar-velez", "stephany-carvajalino", "andrea-garcia-gomez", "valentina-gonzalez-ramirez",
    "sebastian-fernando-florez-duarte", "isabel-pulido", "marybel-montoya-alvarez", "alejandro-rendon-alvarez", "alejandro-caiaffa", "eduardo-andres-ospina",
    "luis-carlos-parra-raffan", "juan-sebastian-ruales", "tania-rosas", "juan-pablo-ospina-yepes", "gabriela-casuso", "maria-jose-charris",
    "luisa-fernanda-lopez-torres", "simon-borrero", "sebastian-mejia", "andres-bilbao", "brynne-mcnulty-rojas", "sebastian-noguera-escallon",
    "jeronimo-uribe-moreno", "freddy-vega", "enrique-villamarin-lafaurie", "juan-pablo-ortega", "daniela-izquierdo", "alexander-torrenegra",
    "david-velez-osorno", "manuela-sanchez", "jose-fernando-velez", "julian-torres-gomez", "adriana-suarez-pardo", "paula-barrientos-moreno",
    "santiago-alvarez-patron", "felipe-santamaria", "wenyi-cai", "andres-barreto", "miguel-mcallister", "felipe-ossa",
    "gabriel-santos-garcia", "maria-fernanda-quinones", "paola-garcia-barreneche", "laura-forero", "andres-vejarano", "paula-marcela-moreno-zapata",
    "catalina-escobar",
  ],
} as const;
