/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnunciaRouteImport } from './routes/anuncia'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as ContraRouteImport } from './routes/contra'
import { Route as InnovativesRouteImport } from './routes/innovatives'
import { Route as ListRouteImport } from './routes/list'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as InnovativesIndexRouteImport } from './routes/innovatives/index'
import { Route as InnovativesSlugRouteImport } from './routes/innovatives/$slug'
import { Route as ListIndexRouteImport } from './routes/list/index'
import { Route as ListSlugRouteImport } from './routes/list/$slug'
import { Route as SectionSectionRouteImport } from './routes/section/$section'
import { Route as StorySlugRouteImport } from './routes/story/$slug'
import { Route as TagTagRouteImport } from './routes/tag/$tag'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciaRoute = AnunciaRouteImport.update({
  id: '/anuncia',
  path: '/anuncia',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContraRoute = ContraRouteImport.update({
  id: '/contra',
  path: '/contra',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovativesRoute = InnovativesRouteImport.update({
  id: '/innovatives',
  path: '/innovatives',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovativesIndexRoute = InnovativesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InnovativesRoute,
} as any)
const InnovativesSlugRoute = InnovativesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InnovativesRoute,
} as any)
const ListIndexRoute = ListIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListRoute,
} as any)
const ListSlugRoute = ListSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ListRoute,
} as any)
const SectionSectionRoute = SectionSectionRouteImport.update({
  id: '/section/$section',
  path: '/section/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const StorySlugRoute = StorySlugRouteImport.update({
  id: '/story/$slug',
  path: '/story/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anuncia': typeof AnunciaRoute
  '/briefing': typeof BriefingRoute
  '/contra': typeof ContraRoute
  '/innovatives': typeof InnovativesRouteWithChildren
  '/list': typeof ListRouteWithChildren
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/signals': typeof SignalsRoute
  '/innovatives/$slug': typeof InnovativesSlugRoute
  '/list/$slug': typeof ListSlugRoute
  '/section/$section': typeof SectionSectionRoute
  '/story/$slug': typeof StorySlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/innovatives/': typeof InnovativesIndexRoute
  '/list/': typeof ListIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anuncia': typeof AnunciaRoute
  '/briefing': typeof BriefingRoute
  '/contra': typeof ContraRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/signals': typeof SignalsRoute
  '/innovatives/$slug': typeof InnovativesSlugRoute
  '/list/$slug': typeof ListSlugRoute
  '/section/$section': typeof SectionSectionRoute
  '/story/$slug': typeof StorySlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/innovatives': typeof InnovativesIndexRoute
  '/list': typeof ListIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anuncia': typeof AnunciaRoute
  '/briefing': typeof BriefingRoute
  '/contra': typeof ContraRoute
  '/innovatives': typeof InnovativesRouteWithChildren
  '/list': typeof ListRouteWithChildren
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/signals': typeof SignalsRoute
  '/innovatives/$slug': typeof InnovativesSlugRoute
  '/list/$slug': typeof ListSlugRoute
  '/section/$section': typeof SectionSectionRoute
  '/story/$slug': typeof StorySlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/innovatives/': typeof InnovativesIndexRoute
  '/list/': typeof ListIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/anuncia'
    | '/briefing'
    | '/contra'
    | '/innovatives'
    | '/list'
    | '/login'
    | '/saved'
    | '/search'
    | '/signals'
    | '/innovatives/$slug'
    | '/list/$slug'
    | '/section/$section'
    | '/story/$slug'
    | '/tag/$tag'
    | '/innovatives/'
    | '/list/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/anuncia'
    | '/briefing'
    | '/contra'
    | '/login'
    | '/saved'
    | '/search'
    | '/signals'
    | '/innovatives/$slug'
    | '/list/$slug'
    | '/section/$section'
    | '/story/$slug'
    | '/tag/$tag'
    | '/innovatives'
    | '/list'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/anuncia'
    | '/briefing'
    | '/contra'
    | '/innovatives'
    | '/list'
    | '/login'
    | '/saved'
    | '/search'
    | '/signals'
    | '/innovatives/$slug'
    | '/list/$slug'
    | '/section/$section'
    | '/story/$slug'
    | '/tag/$tag'
    | '/innovatives/'
    | '/list/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnunciaRoute: typeof AnunciaRoute
  BriefingRoute: typeof BriefingRoute
  ContraRoute: typeof ContraRoute
  InnovativesRoute: typeof InnovativesRouteWithChildren
  ListRoute: typeof ListRouteWithChildren
  LoginRoute: typeof LoginRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SignalsRoute: typeof SignalsRoute
  SectionSectionRoute: typeof SectionSectionRoute
  StorySlugRoute: typeof StorySlugRoute
  TagTagRoute: typeof TagTagRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncia': {
      id: '/anuncia'
      path: '/anuncia'
      fullPath: '/anuncia'
      preLoaderRoute: typeof AnunciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contra': {
      id: '/contra'
      path: '/contra'
      fullPath: '/contra'
      preLoaderRoute: typeof ContraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovatives': {
      id: '/innovatives'
      path: '/innovatives'
      fullPath: '/innovatives'
      preLoaderRoute: typeof InnovativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovatives/': {
      id: '/innovatives/'
      path: '/'
      fullPath: '/innovatives/'
      preLoaderRoute: typeof InnovativesIndexRouteImport
      parentRoute: typeof InnovativesRoute
    }
    '/innovatives/$slug': {
      id: '/innovatives/$slug'
      path: '/$slug'
      fullPath: '/innovatives/$slug'
      preLoaderRoute: typeof InnovativesSlugRouteImport
      parentRoute: typeof InnovativesRoute
    }
    '/list/': {
      id: '/list/'
      path: '/'
      fullPath: '/list/'
      preLoaderRoute: typeof ListIndexRouteImport
      parentRoute: typeof ListRoute
    }
    '/list/$slug': {
      id: '/list/$slug'
      path: '/$slug'
      fullPath: '/list/$slug'
      preLoaderRoute: typeof ListSlugRouteImport
      parentRoute: typeof ListRoute
    }
    '/section/$section': {
      id: '/section/$section'
      path: '/section/$section'
      fullPath: '/section/$section'
      preLoaderRoute: typeof SectionSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$slug': {
      id: '/story/$slug'
      path: '/story/$slug'
      fullPath: '/story/$slug'
      preLoaderRoute: typeof StorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InnovativesRouteChildren {
  InnovativesSlugRoute: typeof InnovativesSlugRoute
  InnovativesIndexRoute: typeof InnovativesIndexRoute
}

const InnovativesRouteChildren: InnovativesRouteChildren = {
  InnovativesSlugRoute: InnovativesSlugRoute,
  InnovativesIndexRoute: InnovativesIndexRoute,
}

const InnovativesRouteWithChildren = InnovativesRoute._addFileChildren(
  InnovativesRouteChildren,
)

interface ListRouteChildren {
  ListSlugRoute: typeof ListSlugRoute
  ListIndexRoute: typeof ListIndexRoute
}

const ListRouteChildren: ListRouteChildren = {
  ListSlugRoute: ListSlugRoute,
  ListIndexRoute: ListIndexRoute,
}

const ListRouteWithChildren = ListRoute._addFileChildren(ListRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnunciaRoute: AnunciaRoute,
  BriefingRoute: BriefingRoute,
  ContraRoute: ContraRoute,
  InnovativesRoute: InnovativesRouteWithChildren,
  ListRoute: ListRouteWithChildren,
  LoginRoute: LoginRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SignalsRoute: SignalsRoute,
  SectionSectionRoute: SectionSectionRoute,
  StorySlugRoute: StorySlugRoute,
  TagTagRoute: TagTagRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
