/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnunciaRouteImport } from './routes/anuncia'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as ContraRouteImport } from './routes/contra'
import { Route as IndiceRouteImport } from './routes/indice'
import { Route as InnovativesRouteImport } from './routes/innovatives'
import { Route as ListRouteImport } from './routes/list'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ObituariosRouteImport } from './routes/obituarios'
import { Route as PisoRouteImport } from './routes/piso'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as Under40RouteImport } from './routes/under40'
import { Route as VisionariosRouteImport } from './routes/visionarios'
import { Route as ApiMarketsRouteImport } from './routes/api/markets'
import { Route as ContraIndexRouteImport } from './routes/contra/index'
import { Route as ContraAutorRouteImport } from './routes/contra/autor'
import { Route as ContraTagRouteImport } from './routes/contra/tag'
import { Route as InnovativesIndexRouteImport } from './routes/innovatives/index'
import { Route as InnovativesSlugRouteImport } from './routes/innovatives/$slug'
import { Route as InnovativesMetodologiaRouteImport } from './routes/innovatives/metodologia'
import { Route as InnovativesPaisRouteImport } from './routes/innovatives/pais'
import { Route as InnovativesSectorRouteImport } from './routes/innovatives/sector'
import { Route as ListIndexRouteImport } from './routes/list/index'
import { Route as ListSlugRouteImport } from './routes/list/$slug'
import { Route as ListCiudadRouteImport } from './routes/list/ciudad'
import { Route as ListMetodologiaRouteImport } from './routes/list/metodologia'
import { Route as ListSectorRouteImport } from './routes/list/sector'
import { Route as SectionSectionRouteImport } from './routes/section/$section'
import { Route as SignalsIndexRouteImport } from './routes/signals/index'
import { Route as SignalsTagRouteImport } from './routes/signals/tag'
import { Route as StorySlugRouteImport } from './routes/story/$slug'
import { Route as TagTagRouteImport } from './routes/tag/$tag'
import { Route as Under40IndexRouteImport } from './routes/under40/index'
import { Route as Under40SlugRouteImport } from './routes/under40/$slug'
import { Route as Under40MetodologiaRouteImport } from './routes/under40/metodologia'
import { Route as VisionariosIndexRouteImport } from './routes/visionarios/index'
import { Route as VisionariosArgentinaRouteImport } from './routes/visionarios/argentina'
import { Route as VisionariosColombiaRouteImport } from './routes/visionarios/colombia'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMarketsHealthRouteImport } from './routes/api/markets.health'
import { Route as ApiMarketsIngestRouteImport } from './routes/api/markets.ingest'
import { Route as ContraAutorIndexRouteImport } from './routes/contra/autor/index'
import { Route as ContraAutorAutorRouteImport } from './routes/contra/autor/$autor'
import { Route as ContraTagIndexRouteImport } from './routes/contra/tag/index'
import { Route as ContraTagTagRouteImport } from './routes/contra/tag/$tag'
import { Route as InnovativesPaisIndexRouteImport } from './routes/innovatives/pais/index'
import { Route as InnovativesPaisPaisRouteImport } from './routes/innovatives/pais/$pais'
import { Route as InnovativesSectorIndexRouteImport } from './routes/innovatives/sector/index'
import { Route as InnovativesSectorSectorRouteImport } from './routes/innovatives/sector/$sector'
import { Route as ListCiudadIndexRouteImport } from './routes/list/ciudad/index'
import { Route as ListCiudadCityRouteImport } from './routes/list/ciudad/$city'
import { Route as ListSectorIndexRouteImport } from './routes/list/sector/index'
import { Route as ListSectorSectorRouteImport } from './routes/list/sector/$sector'
import { Route as SignalsTagIndexRouteImport } from './routes/signals/tag/index'
import { Route as SignalsTagTagRouteImport } from './routes/signals/tag/$tag'
import { Route as VisionariosArgentinaIndexRouteImport } from './routes/visionarios/argentina/index'
import { Route as VisionariosArgentinaSlugRouteImport } from './routes/visionarios/argentina/$slug'
import { Route as VisionariosArgentinaMetodologiaRouteImport } from './routes/visionarios/argentina/metodologia'
import { Route as VisionariosColombiaIndexRouteImport } from './routes/visionarios/colombia/index'
import { Route as VisionariosColombiaSlugRouteImport } from './routes/visionarios/colombia/$slug'
import { Route as VisionariosColombiaMetodologiaRouteImport } from './routes/visionarios/colombia/metodologia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciaRoute = AnunciaRouteImport.update({
  id: '/anuncia',
  path: '/anuncia',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ContraRoute = ContraRouteImport.update({
  id: '/contra',
  path: '/contra',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiceRoute = IndiceRouteImport.update({
  id: '/indice',
  path: '/indice',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovativesRoute = InnovativesRouteImport.update({
  id: '/innovatives',
  path: '/innovatives',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ObituariosRoute = ObituariosRouteImport.update({
  id: '/obituarios',
  path: '/obituarios',
  getParentRoute: () => rootRouteImport,
} as any)
const PisoRoute = PisoRouteImport.update({
  id: '/piso',
  path: '/piso',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const Under40Route = Under40RouteImport.update({
  id: '/under40',
  path: '/under40',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionariosRoute = VisionariosRouteImport.update({
  id: '/visionarios',
  path: '/visionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsRoute = ApiMarketsRouteImport.update({
  id: '/api/markets',
  path: '/api/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ContraIndexRoute = ContraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContraRoute,
} as any)
const ContraAutorRoute = ContraAutorRouteImport.update({
  id: '/autor',
  path: '/autor',
  getParentRoute: () => ContraRoute,
} as any)
const ContraTagRoute = ContraTagRouteImport.update({
  id: '/tag',
  path: '/tag',
  getParentRoute: () => ContraRoute,
} as any)
const InnovativesIndexRoute = InnovativesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InnovativesRoute,
} as any)
const InnovativesSlugRoute = InnovativesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InnovativesRoute,
} as any)
const InnovativesMetodologiaRoute = InnovativesMetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => InnovativesRoute,
} as any)
const InnovativesPaisRoute = InnovativesPaisRouteImport.update({
  id: '/pais',
  path: '/pais',
  getParentRoute: () => InnovativesRoute,
} as any)
const InnovativesSectorRoute = InnovativesSectorRouteImport.update({
  id: '/sector',
  path: '/sector',
  getParentRoute: () => InnovativesRoute,
} as any)
const ListIndexRoute = ListIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListRoute,
} as any)
const ListSlugRoute = ListSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ListRoute,
} as any)
const ListCiudadRoute = ListCiudadRouteImport.update({
  id: '/ciudad',
  path: '/ciudad',
  getParentRoute: () => ListRoute,
} as any)
const ListMetodologiaRoute = ListMetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => ListRoute,
} as any)
const ListSectorRoute = ListSectorRouteImport.update({
  id: '/sector',
  path: '/sector',
  getParentRoute: () => ListRoute,
} as any)
const SectionSectionRoute = SectionSectionRouteImport.update({
  id: '/section/$section',
  path: '/section/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsIndexRoute = SignalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignalsRoute,
} as any)
const SignalsTagRoute = SignalsTagRouteImport.update({
  id: '/tag',
  path: '/tag',
  getParentRoute: () => SignalsRoute,
} as any)
const StorySlugRoute = StorySlugRouteImport.update({
  id: '/story/$slug',
  path: '/story/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const Under40IndexRoute = Under40IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Under40Route,
} as any)
const Under40SlugRoute = Under40SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => Under40Route,
} as any)
const Under40MetodologiaRoute = Under40MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => Under40Route,
} as any)
const VisionariosIndexRoute = VisionariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VisionariosRoute,
} as any)
const VisionariosArgentinaRoute = VisionariosArgentinaRouteImport.update({
  id: '/argentina',
  path: '/argentina',
  getParentRoute: () => VisionariosRoute,
} as any)
const VisionariosColombiaRoute = VisionariosColombiaRouteImport.update({
  id: '/colombia',
  path: '/colombia',
  getParentRoute: () => VisionariosRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsHealthRoute = ApiMarketsHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ApiMarketsRoute,
} as any)
const ApiMarketsIngestRoute = ApiMarketsIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => ApiMarketsRoute,
} as any)
const ContraAutorIndexRoute = ContraAutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContraAutorRoute,
} as any)
const ContraAutorAutorRoute = ContraAutorAutorRouteImport.update({
  id: '/$autor',
  path: '/$autor',
  getParentRoute: () => ContraAutorRoute,
} as any)
const ContraTagIndexRoute = ContraTagIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContraTagRoute,
} as any)
const ContraTagTagRoute = ContraTagTagRouteImport.update({
  id: '/$tag',
  path: '/$tag',
  getParentRoute: () => ContraTagRoute,
} as any)
const InnovativesPaisIndexRoute = InnovativesPaisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InnovativesPaisRoute,
} as any)
const InnovativesPaisPaisRoute = InnovativesPaisPaisRouteImport.update({
  id: '/$pais',
  path: '/$pais',
  getParentRoute: () => InnovativesPaisRoute,
} as any)
const InnovativesSectorIndexRoute = InnovativesSectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InnovativesSectorRoute,
} as any)
const InnovativesSectorSectorRoute = InnovativesSectorSectorRouteImport.update({
  id: '/$sector',
  path: '/$sector',
  getParentRoute: () => InnovativesSectorRoute,
} as any)
const ListCiudadIndexRoute = ListCiudadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListCiudadRoute,
} as any)
const ListCiudadCityRoute = ListCiudadCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => ListCiudadRoute,
} as any)
const ListSectorIndexRoute = ListSectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListSectorRoute,
} as any)
const ListSectorSectorRoute = ListSectorSectorRouteImport.update({
  id: '/$sector',
  path: '/$sector',
  getParentRoute: () => ListSectorRoute,
} as any)
const SignalsTagIndexRoute = SignalsTagIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignalsTagRoute,
} as any)
const SignalsTagTagRoute = SignalsTagTagRouteImport.update({
  id: '/$tag',
  path: '/$tag',
  getParentRoute: () => SignalsTagRoute,
} as any)
const VisionariosArgentinaIndexRoute =
  VisionariosArgentinaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => VisionariosArgentinaRoute,
  } as any)
const VisionariosArgentinaSlugRoute =
  VisionariosArgentinaSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => VisionariosArgentinaRoute,
  } as any)
const VisionariosArgentinaMetodologiaRoute =
  VisionariosArgentinaMetodologiaRouteImport.update({
    id: '/metodologia',
    path: '/metodologia',
    getParentRoute: () => VisionariosArgentinaRoute,
  } as any)
const VisionariosColombiaIndexRoute =
  VisionariosColombiaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => VisionariosColombiaRoute,
  } as any)
const VisionariosColombiaSlugRoute = VisionariosColombiaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VisionariosColombiaRoute,
} as any)
const VisionariosColombiaMetodologiaRoute =
  VisionariosColombiaMetodologiaRouteImport.update({
    id: '/metodologia',
    path: '/metodologia',
    getParentRoute: () => VisionariosColombiaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anuncia': typeof AnunciaRoute
  '/briefing': typeof BriefingRoute
  '/channels': typeof ChannelsRoute
  '/contra': typeof ContraRouteWithChildren
  '/indice': typeof IndiceRoute
  '/innovatives': typeof InnovativesRouteWithChildren
  '/list': typeof ListRouteWithChildren
  '/login': typeof LoginRoute
  '/obituarios': typeof ObituariosRoute
  '/piso': typeof PisoRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/signals': typeof SignalsRouteWithChildren
  '/under40': typeof Under40RouteWithChildren
  '/visionarios': typeof VisionariosRouteWithChildren
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/contra/autor': typeof ContraAutorRouteWithChildren
  '/contra/tag': typeof ContraTagRouteWithChildren
  '/innovatives/$slug': typeof InnovativesSlugRoute
  '/innovatives/metodologia': typeof InnovativesMetodologiaRoute
  '/innovatives/pais': typeof InnovativesPaisRouteWithChildren
  '/innovatives/sector': typeof InnovativesSectorRouteWithChildren
  '/list/$slug': typeof ListSlugRoute
  '/list/ciudad': typeof ListCiudadRouteWithChildren
  '/list/metodologia': typeof ListMetodologiaRoute
  '/list/sector': typeof ListSectorRouteWithChildren
  '/section/$section': typeof SectionSectionRoute
  '/signals/tag': typeof SignalsTagRouteWithChildren
  '/story/$slug': typeof StorySlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/under40/$slug': typeof Under40SlugRoute
  '/under40/metodologia': typeof Under40MetodologiaRoute
  '/visionarios/argentina': typeof VisionariosArgentinaRouteWithChildren
  '/visionarios/colombia': typeof VisionariosColombiaRouteWithChildren
  '/contra/': typeof ContraIndexRoute
  '/innovatives/': typeof InnovativesIndexRoute
  '/list/': typeof ListIndexRoute
  '/signals/': typeof SignalsIndexRoute
  '/under40/': typeof Under40IndexRoute
  '/visionarios/': typeof VisionariosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/markets/health': typeof ApiMarketsHealthRoute
  '/api/markets/ingest': typeof ApiMarketsIngestRoute
  '/contra/autor/$autor': typeof ContraAutorAutorRoute
  '/contra/tag/$tag': typeof ContraTagTagRoute
  '/innovatives/pais/$pais': typeof InnovativesPaisPaisRoute
  '/innovatives/sector/$sector': typeof InnovativesSectorSectorRoute
  '/list/ciudad/$city': typeof ListCiudadCityRoute
  '/list/sector/$sector': typeof ListSectorSectorRoute
  '/signals/tag/$tag': typeof SignalsTagTagRoute
  '/visionarios/argentina/$slug': typeof VisionariosArgentinaSlugRoute
  '/visionarios/argentina/metodologia': typeof VisionariosArgentinaMetodologiaRoute
  '/visionarios/colombia/$slug': typeof VisionariosColombiaSlugRoute
  '/visionarios/colombia/metodologia': typeof VisionariosColombiaMetodologiaRoute
  '/contra/autor/': typeof ContraAutorIndexRoute
  '/contra/tag/': typeof ContraTagIndexRoute
  '/innovatives/pais/': typeof InnovativesPaisIndexRoute
  '/innovatives/sector/': typeof InnovativesSectorIndexRoute
  '/list/ciudad/': typeof ListCiudadIndexRoute
  '/list/sector/': typeof ListSectorIndexRoute
  '/signals/tag/': typeof SignalsTagIndexRoute
  '/visionarios/argentina/': typeof VisionariosArgentinaIndexRoute
  '/visionarios/colombia/': typeof VisionariosColombiaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anuncia': typeof AnunciaRoute
  '/briefing': typeof BriefingRoute
  '/channels': typeof ChannelsRoute
  '/indice': typeof IndiceRoute
  '/login': typeof LoginRoute
  '/obituarios': typeof ObituariosRoute
  '/piso': typeof PisoRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/innovatives/$slug': typeof InnovativesSlugRoute
  '/innovatives/metodologia': typeof InnovativesMetodologiaRoute
  '/list/$slug': typeof ListSlugRoute
  '/list/metodologia': typeof ListMetodologiaRoute
  '/section/$section': typeof SectionSectionRoute
  '/story/$slug': typeof StorySlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/under40/$slug': typeof Under40SlugRoute
  '/under40/metodologia': typeof Under40MetodologiaRoute
  '/contra': typeof ContraIndexRoute
  '/innovatives': typeof InnovativesIndexRoute
  '/list': typeof ListIndexRoute
  '/signals': typeof SignalsIndexRoute
  '/under40': typeof Under40IndexRoute
  '/visionarios': typeof VisionariosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/markets/health': typeof ApiMarketsHealthRoute
  '/api/markets/ingest': typeof ApiMarketsIngestRoute
  '/contra/autor/$autor': typeof ContraAutorAutorRoute
  '/contra/tag/$tag': typeof ContraTagTagRoute
  '/innovatives/pais/$pais': typeof InnovativesPaisPaisRoute
  '/innovatives/sector/$sector': typeof InnovativesSectorSectorRoute
  '/list/ciudad/$city': typeof ListCiudadCityRoute
  '/list/sector/$sector': typeof ListSectorSectorRoute
  '/signals/tag/$tag': typeof SignalsTagTagRoute
  '/visionarios/argentina/$slug': typeof VisionariosArgentinaSlugRoute
  '/visionarios/argentina/metodologia': typeof VisionariosArgentinaMetodologiaRoute
  '/visionarios/colombia/$slug': typeof VisionariosColombiaSlugRoute
  '/visionarios/colombia/metodologia': typeof VisionariosColombiaMetodologiaRoute
  '/contra/autor': typeof ContraAutorIndexRoute
  '/contra/tag': typeof ContraTagIndexRoute
  '/innovatives/pais': typeof InnovativesPaisIndexRoute
  '/innovatives/sector': typeof InnovativesSectorIndexRoute
  '/list/ciudad': typeof ListCiudadIndexRoute
  '/list/sector': typeof ListSectorIndexRoute
  '/signals/tag': typeof SignalsTagIndexRoute
  '/visionarios/argentina': typeof VisionariosArgentinaIndexRoute
  '/visionarios/colombia': typeof VisionariosColombiaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anuncia': typeof AnunciaRoute
  '/briefing': typeof BriefingRoute
  '/channels': typeof ChannelsRoute
  '/contra': typeof ContraRouteWithChildren
  '/indice': typeof IndiceRoute
  '/innovatives': typeof InnovativesRouteWithChildren
  '/list': typeof ListRouteWithChildren
  '/login': typeof LoginRoute
  '/obituarios': typeof ObituariosRoute
  '/piso': typeof PisoRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/signals': typeof SignalsRouteWithChildren
  '/under40': typeof Under40RouteWithChildren
  '/visionarios': typeof VisionariosRouteWithChildren
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/contra/autor': typeof ContraAutorRouteWithChildren
  '/contra/tag': typeof ContraTagRouteWithChildren
  '/innovatives/$slug': typeof InnovativesSlugRoute
  '/innovatives/metodologia': typeof InnovativesMetodologiaRoute
  '/innovatives/pais': typeof InnovativesPaisRouteWithChildren
  '/innovatives/sector': typeof InnovativesSectorRouteWithChildren
  '/list/$slug': typeof ListSlugRoute
  '/list/ciudad': typeof ListCiudadRouteWithChildren
  '/list/metodologia': typeof ListMetodologiaRoute
  '/list/sector': typeof ListSectorRouteWithChildren
  '/section/$section': typeof SectionSectionRoute
  '/signals/tag': typeof SignalsTagRouteWithChildren
  '/story/$slug': typeof StorySlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/under40/$slug': typeof Under40SlugRoute
  '/under40/metodologia': typeof Under40MetodologiaRoute
  '/visionarios/argentina': typeof VisionariosArgentinaRouteWithChildren
  '/visionarios/colombia': typeof VisionariosColombiaRouteWithChildren
  '/contra/': typeof ContraIndexRoute
  '/innovatives/': typeof InnovativesIndexRoute
  '/list/': typeof ListIndexRoute
  '/signals/': typeof SignalsIndexRoute
  '/under40/': typeof Under40IndexRoute
  '/visionarios/': typeof VisionariosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/markets/health': typeof ApiMarketsHealthRoute
  '/api/markets/ingest': typeof ApiMarketsIngestRoute
  '/contra/autor/$autor': typeof ContraAutorAutorRoute
  '/contra/tag/$tag': typeof ContraTagTagRoute
  '/innovatives/pais/$pais': typeof InnovativesPaisPaisRoute
  '/innovatives/sector/$sector': typeof InnovativesSectorSectorRoute
  '/list/ciudad/$city': typeof ListCiudadCityRoute
  '/list/sector/$sector': typeof ListSectorSectorRoute
  '/signals/tag/$tag': typeof SignalsTagTagRoute
  '/visionarios/argentina/$slug': typeof VisionariosArgentinaSlugRoute
  '/visionarios/argentina/metodologia': typeof VisionariosArgentinaMetodologiaRoute
  '/visionarios/colombia/$slug': typeof VisionariosColombiaSlugRoute
  '/visionarios/colombia/metodologia': typeof VisionariosColombiaMetodologiaRoute
  '/contra/autor/': typeof ContraAutorIndexRoute
  '/contra/tag/': typeof ContraTagIndexRoute
  '/innovatives/pais/': typeof InnovativesPaisIndexRoute
  '/innovatives/sector/': typeof InnovativesSectorIndexRoute
  '/list/ciudad/': typeof ListCiudadIndexRoute
  '/list/sector/': typeof ListSectorIndexRoute
  '/signals/tag/': typeof SignalsTagIndexRoute
  '/visionarios/argentina/': typeof VisionariosArgentinaIndexRoute
  '/visionarios/colombia/': typeof VisionariosColombiaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/anuncia'
    | '/briefing'
    | '/channels'
    | '/contra'
    | '/indice'
    | '/innovatives'
    | '/list'
    | '/login'
    | '/obituarios'
    | '/piso'
    | '/saved'
    | '/search'
    | '/signals'
    | '/under40'
    | '/visionarios'
    | '/api/markets'
    | '/contra/autor'
    | '/contra/tag'
    | '/innovatives/$slug'
    | '/innovatives/metodologia'
    | '/innovatives/pais'
    | '/innovatives/sector'
    | '/list/$slug'
    | '/list/ciudad'
    | '/list/metodologia'
    | '/list/sector'
    | '/section/$section'
    | '/signals/tag'
    | '/story/$slug'
    | '/tag/$tag'
    | '/under40/$slug'
    | '/under40/metodologia'
    | '/visionarios/argentina'
    | '/visionarios/colombia'
    | '/contra/'
    | '/innovatives/'
    | '/list/'
    | '/signals/'
    | '/under40/'
    | '/visionarios/'
    | '/api/auth/$'
    | '/api/markets/health'
    | '/api/markets/ingest'
    | '/contra/autor/$autor'
    | '/contra/tag/$tag'
    | '/innovatives/pais/$pais'
    | '/innovatives/sector/$sector'
    | '/list/ciudad/$city'
    | '/list/sector/$sector'
    | '/signals/tag/$tag'
    | '/visionarios/argentina/$slug'
    | '/visionarios/argentina/metodologia'
    | '/visionarios/colombia/$slug'
    | '/visionarios/colombia/metodologia'
    | '/contra/autor/'
    | '/contra/tag/'
    | '/innovatives/pais/'
    | '/innovatives/sector/'
    | '/list/ciudad/'
    | '/list/sector/'
    | '/signals/tag/'
    | '/visionarios/argentina/'
    | '/visionarios/colombia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/anuncia'
    | '/briefing'
    | '/channels'
    | '/indice'
    | '/login'
    | '/obituarios'
    | '/piso'
    | '/saved'
    | '/search'
    | '/api/markets'
    | '/innovatives/$slug'
    | '/innovatives/metodologia'
    | '/list/$slug'
    | '/list/metodologia'
    | '/section/$section'
    | '/story/$slug'
    | '/tag/$tag'
    | '/under40/$slug'
    | '/under40/metodologia'
    | '/contra'
    | '/innovatives'
    | '/list'
    | '/signals'
    | '/under40'
    | '/visionarios'
    | '/api/auth/$'
    | '/api/markets/health'
    | '/api/markets/ingest'
    | '/contra/autor/$autor'
    | '/contra/tag/$tag'
    | '/innovatives/pais/$pais'
    | '/innovatives/sector/$sector'
    | '/list/ciudad/$city'
    | '/list/sector/$sector'
    | '/signals/tag/$tag'
    | '/visionarios/argentina/$slug'
    | '/visionarios/argentina/metodologia'
    | '/visionarios/colombia/$slug'
    | '/visionarios/colombia/metodologia'
    | '/contra/autor'
    | '/contra/tag'
    | '/innovatives/pais'
    | '/innovatives/sector'
    | '/list/ciudad'
    | '/list/sector'
    | '/signals/tag'
    | '/visionarios/argentina'
    | '/visionarios/colombia'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/anuncia'
    | '/briefing'
    | '/channels'
    | '/contra'
    | '/indice'
    | '/innovatives'
    | '/list'
    | '/login'
    | '/obituarios'
    | '/piso'
    | '/saved'
    | '/search'
    | '/signals'
    | '/under40'
    | '/visionarios'
    | '/api/markets'
    | '/contra/autor'
    | '/contra/tag'
    | '/innovatives/$slug'
    | '/innovatives/metodologia'
    | '/innovatives/pais'
    | '/innovatives/sector'
    | '/list/$slug'
    | '/list/ciudad'
    | '/list/metodologia'
    | '/list/sector'
    | '/section/$section'
    | '/signals/tag'
    | '/story/$slug'
    | '/tag/$tag'
    | '/under40/$slug'
    | '/under40/metodologia'
    | '/visionarios/argentina'
    | '/visionarios/colombia'
    | '/contra/'
    | '/innovatives/'
    | '/list/'
    | '/signals/'
    | '/under40/'
    | '/visionarios/'
    | '/api/auth/$'
    | '/api/markets/health'
    | '/api/markets/ingest'
    | '/contra/autor/$autor'
    | '/contra/tag/$tag'
    | '/innovatives/pais/$pais'
    | '/innovatives/sector/$sector'
    | '/list/ciudad/$city'
    | '/list/sector/$sector'
    | '/signals/tag/$tag'
    | '/visionarios/argentina/$slug'
    | '/visionarios/argentina/metodologia'
    | '/visionarios/colombia/$slug'
    | '/visionarios/colombia/metodologia'
    | '/contra/autor/'
    | '/contra/tag/'
    | '/innovatives/pais/'
    | '/innovatives/sector/'
    | '/list/ciudad/'
    | '/list/sector/'
    | '/signals/tag/'
    | '/visionarios/argentina/'
    | '/visionarios/colombia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnunciaRoute: typeof AnunciaRoute
  BriefingRoute: typeof BriefingRoute
  ChannelsRoute: typeof ChannelsRoute
  ContraRoute: typeof ContraRouteWithChildren
  IndiceRoute: typeof IndiceRoute
  InnovativesRoute: typeof InnovativesRouteWithChildren
  ListRoute: typeof ListRouteWithChildren
  LoginRoute: typeof LoginRoute
  ObituariosRoute: typeof ObituariosRoute
  PisoRoute: typeof PisoRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SignalsRoute: typeof SignalsRouteWithChildren
  Under40Route: typeof Under40RouteWithChildren
  VisionariosRoute: typeof VisionariosRouteWithChildren
  ApiMarketsRoute: typeof ApiMarketsRouteWithChildren
  SectionSectionRoute: typeof SectionSectionRoute
  StorySlugRoute: typeof StorySlugRoute
  TagTagRoute: typeof TagTagRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncia': {
      id: '/anuncia'
      path: '/anuncia'
      fullPath: '/anuncia'
      preLoaderRoute: typeof AnunciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contra': {
      id: '/contra'
      path: '/contra'
      fullPath: '/contra'
      preLoaderRoute: typeof ContraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indice': {
      id: '/indice'
      path: '/indice'
      fullPath: '/indice'
      preLoaderRoute: typeof IndiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovatives': {
      id: '/innovatives'
      path: '/innovatives'
      fullPath: '/innovatives'
      preLoaderRoute: typeof InnovativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obituarios': {
      id: '/obituarios'
      path: '/obituarios'
      fullPath: '/obituarios'
      preLoaderRoute: typeof ObituariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piso': {
      id: '/piso'
      path: '/piso'
      fullPath: '/piso'
      preLoaderRoute: typeof PisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/under40': {
      id: '/under40'
      path: '/under40'
      fullPath: '/under40'
      preLoaderRoute: typeof Under40RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visionarios': {
      id: '/visionarios'
      path: '/visionarios'
      fullPath: '/visionarios'
      preLoaderRoute: typeof VisionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets': {
      id: '/api/markets'
      path: '/api/markets'
      fullPath: '/api/markets'
      preLoaderRoute: typeof ApiMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contra/': {
      id: '/contra/'
      path: '/'
      fullPath: '/contra/'
      preLoaderRoute: typeof ContraIndexRouteImport
      parentRoute: typeof ContraRoute
    }
    '/contra/autor': {
      id: '/contra/autor'
      path: '/autor'
      fullPath: '/contra/autor'
      preLoaderRoute: typeof ContraAutorRouteImport
      parentRoute: typeof ContraRoute
    }
    '/contra/tag': {
      id: '/contra/tag'
      path: '/tag'
      fullPath: '/contra/tag'
      preLoaderRoute: typeof ContraTagRouteImport
      parentRoute: typeof ContraRoute
    }
    '/innovatives/': {
      id: '/innovatives/'
      path: '/'
      fullPath: '/innovatives/'
      preLoaderRoute: typeof InnovativesIndexRouteImport
      parentRoute: typeof InnovativesRoute
    }
    '/innovatives/$slug': {
      id: '/innovatives/$slug'
      path: '/$slug'
      fullPath: '/innovatives/$slug'
      preLoaderRoute: typeof InnovativesSlugRouteImport
      parentRoute: typeof InnovativesRoute
    }
    '/innovatives/metodologia': {
      id: '/innovatives/metodologia'
      path: '/metodologia'
      fullPath: '/innovatives/metodologia'
      preLoaderRoute: typeof InnovativesMetodologiaRouteImport
      parentRoute: typeof InnovativesRoute
    }
    '/innovatives/pais': {
      id: '/innovatives/pais'
      path: '/pais'
      fullPath: '/innovatives/pais'
      preLoaderRoute: typeof InnovativesPaisRouteImport
      parentRoute: typeof InnovativesRoute
    }
    '/innovatives/sector': {
      id: '/innovatives/sector'
      path: '/sector'
      fullPath: '/innovatives/sector'
      preLoaderRoute: typeof InnovativesSectorRouteImport
      parentRoute: typeof InnovativesRoute
    }
    '/list/': {
      id: '/list/'
      path: '/'
      fullPath: '/list/'
      preLoaderRoute: typeof ListIndexRouteImport
      parentRoute: typeof ListRoute
    }
    '/list/$slug': {
      id: '/list/$slug'
      path: '/$slug'
      fullPath: '/list/$slug'
      preLoaderRoute: typeof ListSlugRouteImport
      parentRoute: typeof ListRoute
    }
    '/list/ciudad': {
      id: '/list/ciudad'
      path: '/ciudad'
      fullPath: '/list/ciudad'
      preLoaderRoute: typeof ListCiudadRouteImport
      parentRoute: typeof ListRoute
    }
    '/list/metodologia': {
      id: '/list/metodologia'
      path: '/metodologia'
      fullPath: '/list/metodologia'
      preLoaderRoute: typeof ListMetodologiaRouteImport
      parentRoute: typeof ListRoute
    }
    '/list/sector': {
      id: '/list/sector'
      path: '/sector'
      fullPath: '/list/sector'
      preLoaderRoute: typeof ListSectorRouteImport
      parentRoute: typeof ListRoute
    }
    '/section/$section': {
      id: '/section/$section'
      path: '/section/$section'
      fullPath: '/section/$section'
      preLoaderRoute: typeof SectionSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/': {
      id: '/signals/'
      path: '/'
      fullPath: '/signals/'
      preLoaderRoute: typeof SignalsIndexRouteImport
      parentRoute: typeof SignalsRoute
    }
    '/signals/tag': {
      id: '/signals/tag'
      path: '/tag'
      fullPath: '/signals/tag'
      preLoaderRoute: typeof SignalsTagRouteImport
      parentRoute: typeof SignalsRoute
    }
    '/story/$slug': {
      id: '/story/$slug'
      path: '/story/$slug'
      fullPath: '/story/$slug'
      preLoaderRoute: typeof StorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/under40/': {
      id: '/under40/'
      path: '/'
      fullPath: '/under40/'
      preLoaderRoute: typeof Under40IndexRouteImport
      parentRoute: typeof Under40Route
    }
    '/under40/$slug': {
      id: '/under40/$slug'
      path: '/$slug'
      fullPath: '/under40/$slug'
      preLoaderRoute: typeof Under40SlugRouteImport
      parentRoute: typeof Under40Route
    }
    '/under40/metodologia': {
      id: '/under40/metodologia'
      path: '/metodologia'
      fullPath: '/under40/metodologia'
      preLoaderRoute: typeof Under40MetodologiaRouteImport
      parentRoute: typeof Under40Route
    }
    '/visionarios/': {
      id: '/visionarios/'
      path: '/'
      fullPath: '/visionarios/'
      preLoaderRoute: typeof VisionariosIndexRouteImport
      parentRoute: typeof VisionariosRoute
    }
    '/visionarios/argentina': {
      id: '/visionarios/argentina'
      path: '/argentina'
      fullPath: '/visionarios/argentina'
      preLoaderRoute: typeof VisionariosArgentinaRouteImport
      parentRoute: typeof VisionariosRoute
    }
    '/visionarios/colombia': {
      id: '/visionarios/colombia'
      path: '/colombia'
      fullPath: '/visionarios/colombia'
      preLoaderRoute: typeof VisionariosColombiaRouteImport
      parentRoute: typeof VisionariosRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets/health': {
      id: '/api/markets/health'
      path: '/health'
      fullPath: '/api/markets/health'
      preLoaderRoute: typeof ApiMarketsHealthRouteImport
      parentRoute: typeof ApiMarketsRoute
    }
    '/api/markets/ingest': {
      id: '/api/markets/ingest'
      path: '/ingest'
      fullPath: '/api/markets/ingest'
      preLoaderRoute: typeof ApiMarketsIngestRouteImport
      parentRoute: typeof ApiMarketsRoute
    }
    '/contra/autor/': {
      id: '/contra/autor/'
      path: '/'
      fullPath: '/contra/autor/'
      preLoaderRoute: typeof ContraAutorIndexRouteImport
      parentRoute: typeof ContraAutorRoute
    }
    '/contra/autor/$autor': {
      id: '/contra/autor/$autor'
      path: '/$autor'
      fullPath: '/contra/autor/$autor'
      preLoaderRoute: typeof ContraAutorAutorRouteImport
      parentRoute: typeof ContraAutorRoute
    }
    '/contra/tag/': {
      id: '/contra/tag/'
      path: '/'
      fullPath: '/contra/tag/'
      preLoaderRoute: typeof ContraTagIndexRouteImport
      parentRoute: typeof ContraTagRoute
    }
    '/contra/tag/$tag': {
      id: '/contra/tag/$tag'
      path: '/$tag'
      fullPath: '/contra/tag/$tag'
      preLoaderRoute: typeof ContraTagTagRouteImport
      parentRoute: typeof ContraTagRoute
    }
    '/innovatives/pais/': {
      id: '/innovatives/pais/'
      path: '/'
      fullPath: '/innovatives/pais/'
      preLoaderRoute: typeof InnovativesPaisIndexRouteImport
      parentRoute: typeof InnovativesPaisRoute
    }
    '/innovatives/pais/$pais': {
      id: '/innovatives/pais/$pais'
      path: '/$pais'
      fullPath: '/innovatives/pais/$pais'
      preLoaderRoute: typeof InnovativesPaisPaisRouteImport
      parentRoute: typeof InnovativesPaisRoute
    }
    '/innovatives/sector/': {
      id: '/innovatives/sector/'
      path: '/'
      fullPath: '/innovatives/sector/'
      preLoaderRoute: typeof InnovativesSectorIndexRouteImport
      parentRoute: typeof InnovativesSectorRoute
    }
    '/innovatives/sector/$sector': {
      id: '/innovatives/sector/$sector'
      path: '/$sector'
      fullPath: '/innovatives/sector/$sector'
      preLoaderRoute: typeof InnovativesSectorSectorRouteImport
      parentRoute: typeof InnovativesSectorRoute
    }
    '/list/ciudad/': {
      id: '/list/ciudad/'
      path: '/'
      fullPath: '/list/ciudad/'
      preLoaderRoute: typeof ListCiudadIndexRouteImport
      parentRoute: typeof ListCiudadRoute
    }
    '/list/ciudad/$city': {
      id: '/list/ciudad/$city'
      path: '/$city'
      fullPath: '/list/ciudad/$city'
      preLoaderRoute: typeof ListCiudadCityRouteImport
      parentRoute: typeof ListCiudadRoute
    }
    '/list/sector/': {
      id: '/list/sector/'
      path: '/'
      fullPath: '/list/sector/'
      preLoaderRoute: typeof ListSectorIndexRouteImport
      parentRoute: typeof ListSectorRoute
    }
    '/list/sector/$sector': {
      id: '/list/sector/$sector'
      path: '/$sector'
      fullPath: '/list/sector/$sector'
      preLoaderRoute: typeof ListSectorSectorRouteImport
      parentRoute: typeof ListSectorRoute
    }
    '/signals/tag/': {
      id: '/signals/tag/'
      path: '/'
      fullPath: '/signals/tag/'
      preLoaderRoute: typeof SignalsTagIndexRouteImport
      parentRoute: typeof SignalsTagRoute
    }
    '/signals/tag/$tag': {
      id: '/signals/tag/$tag'
      path: '/$tag'
      fullPath: '/signals/tag/$tag'
      preLoaderRoute: typeof SignalsTagTagRouteImport
      parentRoute: typeof SignalsTagRoute
    }
    '/visionarios/argentina/': {
      id: '/visionarios/argentina/'
      path: '/'
      fullPath: '/visionarios/argentina/'
      preLoaderRoute: typeof VisionariosArgentinaIndexRouteImport
      parentRoute: typeof VisionariosArgentinaRoute
    }
    '/visionarios/argentina/$slug': {
      id: '/visionarios/argentina/$slug'
      path: '/$slug'
      fullPath: '/visionarios/argentina/$slug'
      preLoaderRoute: typeof VisionariosArgentinaSlugRouteImport
      parentRoute: typeof VisionariosArgentinaRoute
    }
    '/visionarios/argentina/metodologia': {
      id: '/visionarios/argentina/metodologia'
      path: '/metodologia'
      fullPath: '/visionarios/argentina/metodologia'
      preLoaderRoute: typeof VisionariosArgentinaMetodologiaRouteImport
      parentRoute: typeof VisionariosArgentinaRoute
    }
    '/visionarios/colombia/': {
      id: '/visionarios/colombia/'
      path: '/'
      fullPath: '/visionarios/colombia/'
      preLoaderRoute: typeof VisionariosColombiaIndexRouteImport
      parentRoute: typeof VisionariosColombiaRoute
    }
    '/visionarios/colombia/$slug': {
      id: '/visionarios/colombia/$slug'
      path: '/$slug'
      fullPath: '/visionarios/colombia/$slug'
      preLoaderRoute: typeof VisionariosColombiaSlugRouteImport
      parentRoute: typeof VisionariosColombiaRoute
    }
    '/visionarios/colombia/metodologia': {
      id: '/visionarios/colombia/metodologia'
      path: '/metodologia'
      fullPath: '/visionarios/colombia/metodologia'
      preLoaderRoute: typeof VisionariosColombiaMetodologiaRouteImport
      parentRoute: typeof VisionariosColombiaRoute
    }
  }
}

interface ContraAutorRouteChildren {
  ContraAutorAutorRoute: typeof ContraAutorAutorRoute
  ContraAutorIndexRoute: typeof ContraAutorIndexRoute
}

const ContraAutorRouteChildren: ContraAutorRouteChildren = {
  ContraAutorAutorRoute: ContraAutorAutorRoute,
  ContraAutorIndexRoute: ContraAutorIndexRoute,
}

const ContraAutorRouteWithChildren = ContraAutorRoute._addFileChildren(
  ContraAutorRouteChildren,
)

interface ContraTagRouteChildren {
  ContraTagTagRoute: typeof ContraTagTagRoute
  ContraTagIndexRoute: typeof ContraTagIndexRoute
}

const ContraTagRouteChildren: ContraTagRouteChildren = {
  ContraTagTagRoute: ContraTagTagRoute,
  ContraTagIndexRoute: ContraTagIndexRoute,
}

const ContraTagRouteWithChildren = ContraTagRoute._addFileChildren(
  ContraTagRouteChildren,
)

interface ContraRouteChildren {
  ContraAutorRoute: typeof ContraAutorRouteWithChildren
  ContraTagRoute: typeof ContraTagRouteWithChildren
  ContraIndexRoute: typeof ContraIndexRoute
}

const ContraRouteChildren: ContraRouteChildren = {
  ContraAutorRoute: ContraAutorRouteWithChildren,
  ContraTagRoute: ContraTagRouteWithChildren,
  ContraIndexRoute: ContraIndexRoute,
}

const ContraRouteWithChildren =
  ContraRoute._addFileChildren(ContraRouteChildren)

interface InnovativesPaisRouteChildren {
  InnovativesPaisPaisRoute: typeof InnovativesPaisPaisRoute
  InnovativesPaisIndexRoute: typeof InnovativesPaisIndexRoute
}

const InnovativesPaisRouteChildren: InnovativesPaisRouteChildren = {
  InnovativesPaisPaisRoute: InnovativesPaisPaisRoute,
  InnovativesPaisIndexRoute: InnovativesPaisIndexRoute,
}

const InnovativesPaisRouteWithChildren = InnovativesPaisRoute._addFileChildren(
  InnovativesPaisRouteChildren,
)

interface InnovativesSectorRouteChildren {
  InnovativesSectorSectorRoute: typeof InnovativesSectorSectorRoute
  InnovativesSectorIndexRoute: typeof InnovativesSectorIndexRoute
}

const InnovativesSectorRouteChildren: InnovativesSectorRouteChildren = {
  InnovativesSectorSectorRoute: InnovativesSectorSectorRoute,
  InnovativesSectorIndexRoute: InnovativesSectorIndexRoute,
}

const InnovativesSectorRouteWithChildren =
  InnovativesSectorRoute._addFileChildren(InnovativesSectorRouteChildren)

interface InnovativesRouteChildren {
  InnovativesSlugRoute: typeof InnovativesSlugRoute
  InnovativesMetodologiaRoute: typeof InnovativesMetodologiaRoute
  InnovativesPaisRoute: typeof InnovativesPaisRouteWithChildren
  InnovativesSectorRoute: typeof InnovativesSectorRouteWithChildren
  InnovativesIndexRoute: typeof InnovativesIndexRoute
}

const InnovativesRouteChildren: InnovativesRouteChildren = {
  InnovativesSlugRoute: InnovativesSlugRoute,
  InnovativesMetodologiaRoute: InnovativesMetodologiaRoute,
  InnovativesPaisRoute: InnovativesPaisRouteWithChildren,
  InnovativesSectorRoute: InnovativesSectorRouteWithChildren,
  InnovativesIndexRoute: InnovativesIndexRoute,
}

const InnovativesRouteWithChildren = InnovativesRoute._addFileChildren(
  InnovativesRouteChildren,
)

interface ListCiudadRouteChildren {
  ListCiudadCityRoute: typeof ListCiudadCityRoute
  ListCiudadIndexRoute: typeof ListCiudadIndexRoute
}

const ListCiudadRouteChildren: ListCiudadRouteChildren = {
  ListCiudadCityRoute: ListCiudadCityRoute,
  ListCiudadIndexRoute: ListCiudadIndexRoute,
}

const ListCiudadRouteWithChildren = ListCiudadRoute._addFileChildren(
  ListCiudadRouteChildren,
)

interface ListSectorRouteChildren {
  ListSectorSectorRoute: typeof ListSectorSectorRoute
  ListSectorIndexRoute: typeof ListSectorIndexRoute
}

const ListSectorRouteChildren: ListSectorRouteChildren = {
  ListSectorSectorRoute: ListSectorSectorRoute,
  ListSectorIndexRoute: ListSectorIndexRoute,
}

const ListSectorRouteWithChildren = ListSectorRoute._addFileChildren(
  ListSectorRouteChildren,
)

interface ListRouteChildren {
  ListSlugRoute: typeof ListSlugRoute
  ListCiudadRoute: typeof ListCiudadRouteWithChildren
  ListMetodologiaRoute: typeof ListMetodologiaRoute
  ListSectorRoute: typeof ListSectorRouteWithChildren
  ListIndexRoute: typeof ListIndexRoute
}

const ListRouteChildren: ListRouteChildren = {
  ListSlugRoute: ListSlugRoute,
  ListCiudadRoute: ListCiudadRouteWithChildren,
  ListMetodologiaRoute: ListMetodologiaRoute,
  ListSectorRoute: ListSectorRouteWithChildren,
  ListIndexRoute: ListIndexRoute,
}

const ListRouteWithChildren = ListRoute._addFileChildren(ListRouteChildren)

interface SignalsTagRouteChildren {
  SignalsTagTagRoute: typeof SignalsTagTagRoute
  SignalsTagIndexRoute: typeof SignalsTagIndexRoute
}

const SignalsTagRouteChildren: SignalsTagRouteChildren = {
  SignalsTagTagRoute: SignalsTagTagRoute,
  SignalsTagIndexRoute: SignalsTagIndexRoute,
}

const SignalsTagRouteWithChildren = SignalsTagRoute._addFileChildren(
  SignalsTagRouteChildren,
)

interface SignalsRouteChildren {
  SignalsTagRoute: typeof SignalsTagRouteWithChildren
  SignalsIndexRoute: typeof SignalsIndexRoute
}

const SignalsRouteChildren: SignalsRouteChildren = {
  SignalsTagRoute: SignalsTagRouteWithChildren,
  SignalsIndexRoute: SignalsIndexRoute,
}

const SignalsRouteWithChildren =
  SignalsRoute._addFileChildren(SignalsRouteChildren)

interface Under40RouteChildren {
  Under40SlugRoute: typeof Under40SlugRoute
  Under40MetodologiaRoute: typeof Under40MetodologiaRoute
  Under40IndexRoute: typeof Under40IndexRoute
}

const Under40RouteChildren: Under40RouteChildren = {
  Under40SlugRoute: Under40SlugRoute,
  Under40MetodologiaRoute: Under40MetodologiaRoute,
  Under40IndexRoute: Under40IndexRoute,
}

const Under40RouteWithChildren =
  Under40Route._addFileChildren(Under40RouteChildren)

interface VisionariosArgentinaRouteChildren {
  VisionariosArgentinaSlugRoute: typeof VisionariosArgentinaSlugRoute
  VisionariosArgentinaMetodologiaRoute: typeof VisionariosArgentinaMetodologiaRoute
  VisionariosArgentinaIndexRoute: typeof VisionariosArgentinaIndexRoute
}

const VisionariosArgentinaRouteChildren: VisionariosArgentinaRouteChildren = {
  VisionariosArgentinaSlugRoute: VisionariosArgentinaSlugRoute,
  VisionariosArgentinaMetodologiaRoute: VisionariosArgentinaMetodologiaRoute,
  VisionariosArgentinaIndexRoute: VisionariosArgentinaIndexRoute,
}

const VisionariosArgentinaRouteWithChildren =
  VisionariosArgentinaRoute._addFileChildren(VisionariosArgentinaRouteChildren)

interface VisionariosColombiaRouteChildren {
  VisionariosColombiaSlugRoute: typeof VisionariosColombiaSlugRoute
  VisionariosColombiaMetodologiaRoute: typeof VisionariosColombiaMetodologiaRoute
  VisionariosColombiaIndexRoute: typeof VisionariosColombiaIndexRoute
}

const VisionariosColombiaRouteChildren: VisionariosColombiaRouteChildren = {
  VisionariosColombiaSlugRoute: VisionariosColombiaSlugRoute,
  VisionariosColombiaMetodologiaRoute: VisionariosColombiaMetodologiaRoute,
  VisionariosColombiaIndexRoute: VisionariosColombiaIndexRoute,
}

const VisionariosColombiaRouteWithChildren =
  VisionariosColombiaRoute._addFileChildren(VisionariosColombiaRouteChildren)

interface VisionariosRouteChildren {
  VisionariosArgentinaRoute: typeof VisionariosArgentinaRouteWithChildren
  VisionariosColombiaRoute: typeof VisionariosColombiaRouteWithChildren
  VisionariosIndexRoute: typeof VisionariosIndexRoute
}

const VisionariosRouteChildren: VisionariosRouteChildren = {
  VisionariosArgentinaRoute: VisionariosArgentinaRouteWithChildren,
  VisionariosColombiaRoute: VisionariosColombiaRouteWithChildren,
  VisionariosIndexRoute: VisionariosIndexRoute,
}

const VisionariosRouteWithChildren = VisionariosRoute._addFileChildren(
  VisionariosRouteChildren,
)

interface ApiMarketsRouteChildren {
  ApiMarketsHealthRoute: typeof ApiMarketsHealthRoute
  ApiMarketsIngestRoute: typeof ApiMarketsIngestRoute
}

const ApiMarketsRouteChildren: ApiMarketsRouteChildren = {
  ApiMarketsHealthRoute: ApiMarketsHealthRoute,
  ApiMarketsIngestRoute: ApiMarketsIngestRoute,
}

const ApiMarketsRouteWithChildren = ApiMarketsRoute._addFileChildren(
  ApiMarketsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnunciaRoute: AnunciaRoute,
  BriefingRoute: BriefingRoute,
  ChannelsRoute: ChannelsRoute,
  ContraRoute: ContraRouteWithChildren,
  IndiceRoute: IndiceRoute,
  InnovativesRoute: InnovativesRouteWithChildren,
  ListRoute: ListRouteWithChildren,
  LoginRoute: LoginRoute,
  ObituariosRoute: ObituariosRoute,
  PisoRoute: PisoRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SignalsRoute: SignalsRouteWithChildren,
  Under40Route: Under40RouteWithChildren,
  VisionariosRoute: VisionariosRouteWithChildren,
  ApiMarketsRoute: ApiMarketsRouteWithChildren,
  SectionSectionRoute: SectionSectionRoute,
  StorySlugRoute: StorySlugRoute,
  TagTagRoute: TagTagRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
